### ISSUE TITLE
コマンド補完，オートコンプリートの項目の編集機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#10]
TeX2img に用意された2種類の補完機能

* ESCキーによって発動するコマンド補完
* キー入力した瞬間に発動するオートコンプリート

について，その内容を編集する機能を用意したい。

これらの補完内容はTeXShopと共有しているので，TeXShopの側で編集すればよいのだが，いちいちTeXShopを起動しなくてもTeX2img内で編集を完結できるようにするとより便利だろう。

**Comment by aminophen** [comment]
TeXShop と TeX2img が設定を共有しているわけですので、どちらか一方で変更すればもう一方にも反映されるますよね。そうすると TeX2img 側でも TeXShop と全く同じ編集画面を付けるわけですが、TeX2img はあくまで「補助ツール」ですので、わざわざ TeX2img 側で変更する必然性は特に感じていませんでした。そこまではサポートしなくてもよいのではないかと。

 # TeX2img に（主に非 TeXShop ユーザ向けに）独自の機能を付加するのであれば話は別ですが…
