### ISSUE TITLE
ドロワーUIの置き換え

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#100]
TeX2imgで出力ビューに用いているドロワーUIは，ずいぶん前からdeprecatedになっている。これまではとりあえず使えているのでそのままにしてきたが，macOS 10.14 Mojaveにおいて，ドロワーUIはとうとうダークモードに対応しなくなってしまったため，真剣に代替UIを考える必要がある。
Windows版のように別ウィンドウで表示するようにするのが一番手っ取り早く無難な選択肢ではある。

**Comment by Yasunari** [comment]
別ウ**イ**ンドウに賛成です。もちろんミスだと思いますが「別ウ**ィ**ンドウ」には大反対かも。macOSでいえばTeXShopのようになります。そのウインドウはユーザーが関与できる部分はあるかとなりますね。TeXShopでいえば

1. Abort
1. Trash Aux Files
1. Goto Error

があるわけで。整理すると、

1. に関しては既に`Generate`と場合によった表示になっている
1. 自動で行われている（一部のこるバグあり）
1. #81 でお願い済み

の検討が必要かもしれないという具合でしょうか。

**Comment by doraTeX** [comment]
ミスではありません。私はmacOSのUI表示上以外の日常表記では意図的に「ウィンドウ」を使います。

**Comment by doraTeX** [comment]
メモ：CotEditorのインスペクタビューのようなUIにするという手もある。


![ezgif-2-49bd26feb1f2](https://user-images.githubusercontent.com/6186180/91539400-34c3e700-e954-11ea-912f-5a1b0571a6c3.gif)

**Comment by doraTeX** [comment]
結局当初の予定通り別ウィンドウのUIとして，ドロワーUIの撤廃完了。

![image](https://user-images.githubusercontent.com/6186180/94394172-a384a200-0197-11eb-8105-4a182de37c05.png)
