### ISSUE TITLE
配布サイトの移転

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#101]
配布サイトに使っている geocities が今年の3月末をもって閉鎖されるので，それまでに配布サイトの移転を終える必要がある。移転先としては静的なウェブサイトなので Github Pages を使うのが一番楽そうだろうか。

**Comment by Yasunari** [comment]
Markdownで書いていくと楽かもしれませんね。まだまだの英語版もそれに追従します。美文書7を4月から美文書8までに買った方々は`can not connect😇`になりますが。
![screen shot 2019-01-07 at 17 08 10](https://user-images.githubusercontent.com/38091102/50756288-084ee900-129f-11e9-8095-4787abefa77d.png)

**Comment by doraTeX** [comment]
geocities の閉鎖期限が迫ってきましたので，GitHub Pages で作った新URLの新サイトに丸ごと移転しました。

https://tex2img.tech
