### ISSUE TITLE
出力ファイルパス欄の横にファイルタイプ選択ポップアップメニューを設ける

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#103]
出力ファイルパス欄の横に，次のようなファイルタイプ選択ポップアップメニューを設け，これを選ぶことでファイル形式の切り替えが簡単にできるようにする。

<img width="522" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/6186180/50780888-6f908b80-12e7-11e9-9a44-52990224a40b.png">

「ポップアップメニューからファイル形式を選択すると，それに応じて左のパス欄の拡張子が変わる」という動作をする。

検討すべきは，「ファイルタイプとしてはPDFを選択してパスの拡張子欄が `.pdf` になったが，その後ユーザが手動で拡張子を `.png` に書き換えてコンパイル開始ボタンを押した」というケースの挙動。
よくあるファイル保存ダイアログの挙動を真似るならば，その場合は「 `.png` の後ろに `.pdf` という拡張子を強制的に付与してPDFとして出力させる」ことになるだろう。

**Comment by Yasunari** [comment]
プレビューのようにここではダイアログを出すというのも手かと「サクッと感」は少し失われますが、macOS nativeとしての品格は保てます。
![screen shot 2019-01-08 at 2 02 00](https://user-images.githubusercontent.com/38091102/50781760-8932d280-12e9-11e9-8cb9-5b0320e7c13f.png)

**Comment by doraTeX** [comment]
ああ，このダイアログはいいですね。真似ましょう。

**Comment by abenori** [comment]
手元で実装して試してみました．今までの癖で手での変更を（やっぱり）してしまうのですが，ダイアログで聞かれるのはちょっと邪魔くさいですね．（慣れの問題？）

**Comment by doraTeX** [comment]
> 今までの癖で手での変更を（やっぱり）してしまうのですが，ダイアログで聞かれるのはちょっと邪魔くさいですね．

確かに考えてみるとそうですね……。

* 妥当な別の拡張子の入力を検知したらポップアップの選択状態が勝手に変わる
* 適当でない拡張子の入力状態のまま変換を開始した場合には上記ダイアログが出る

という挙動の方が「サクッと感」が維持できてよいかもしれません。

**Comment by abenori** [comment]
その方がよい気がします．

選択メニューにある拡張子と実際に処理可能な拡張子が同一であることを仮定すると，「処理できないエラーである」とのメッセージがどうせ出るので，ダイアログは不要かもしれません．

**Comment by doraTeX** [comment]
> 選択メニューにある拡張子と実際に処理可能な拡張子が同一であることを仮定すると，「処理できないエラーである」とのメッセージがどうせ出るので，ダイアログは不要かもしれません．

確かにそうですね。ではそういたしましょう。

**Comment by doraTeX** [comment]
b11beb2b9cba6f46afef05c1720ddb3b391f6497 にて上記仕様で実装完了。
