### ISSUE TITLE
カラーパレットからの色入力支援機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#11]
#9 で出た[アイデア](https://github.com/doraTeX/TeX2img/issues/9#issuecomment-76386943)。
カラーパレットで選んだ色を \color[rgb]{1,0.5,0} のような形に翻訳して入力する機能があるとよい。

**Comment by aminophen** [comment]
色変更というのは LaTeX でコマンドで指定するより、どうしてもカラーパレットのほうが便利だと感じてしまうので、色入力支援機能（色を RGB に翻訳）はあっていいのではないかと思います。ただし、LaTeXiT のようにソース入力エリアを改変してしまうのはあまり好きではないので、別ウィンドウで \color[rgb]{1,0.5,0} のように翻訳してくれるところまで、というのが良いです。ソース入力エリアの選択範囲と連動させる LaTeXiT の仕様は少々分かりにくいですので…

**Comment by doraTeX** [comment]
モックアップを作ってみました。こんな感じのイメージで合っていますでしょうか。

![2015-02-28 13 22 38](https://cloud.githubusercontent.com/assets/6186180/6424835/f45b794e-bf4c-11e4-9727-fb04fdaf67d7.png)

**Comment by aminophen** [comment]
私のイメージそのままでした。あとは「挿入」機能をどうするかというところですかね。LaTeXiT の挿入はイマイチよく理解できなかったので、単にカーソルがある位置に挿入とする感じでしょうか。

 # LaTeXiT の例の「全体の色を変える」の場合はそもそも \color コマンドがどこに入ったのか見せてくれないし、「一部だけ色を変える」にも苦戦しました。ドラッグで選択しつつボタンを色のボタンを何度もクリックしていたらいつのまにかうまくいったという結果でした。中途半端な GUI 苦手…

**Comment by aminophen** [comment]
<a href="https://twitter.com/doraTeX/status/573150753759490050">この</a><a href="https://twitter.com/doraTeX/status/573152505816727552">あたりの</a><a href="https://twitter.com/doraTeX/status/5731532866241822732">ツイートを</a><a href="https://twitter.com/doraTeX/status/573155514852368384">見ました</a>。Windows をメインで使っているユーザとしてはモーダルダイアログに慣れているので

> モーダルダイアログにすれば，色の変更のたびにいちいちダイアログを開け閉めしなくてはいけないので，それはそれで面倒だろうけれど。

についてはあまり面倒だと思ったことはありませんでした。今回の色入力補助でモーダルにすると

- エディタ上の \color または \textcolor を入れたい箇所にカーソルを置く
- どこかのメニューから「色入力支援」ダイアログを呼ぶ（例えば<a href="https://github.com/doraTeX/TeX2img/issues/11#issuecomment-76509779">これ</a>の左図）
- 色ボタンを押してカラーパレットを呼び、色を選択して OK でパレットを閉じる
- 「色入力支援」ダイアログの挿入ボタンを押す

これでカーソルの位置にコマンドが挿入される、というイメージですね（あとは、色を変えたいところだけを手動で { ... } で囲む）。手順が多い気がしないでもないですが、分かりにくさは排除されますね。

**Comment by doraTeX** [comment]
\color や \textcolor 以外に，\definecolor も選択肢にあるとよさそうですね。

Mac標準の色選択パレットはモードレスにしかできなさそうです。モーダルな色選択パネルを用意したいなら，Codaのように，そのようなGUIコンポーネントを自作する必要があるでしょうね。そしてそれはMacの標準的インターフェースからは離れてしまいます。悩ましい選択です。

> これでカーソルの位置にコマンドが挿入される、というイメージですね（あとは、色を変えたいところだけを手動で { ... } で囲む）。手順が多い気がしないでもないですが、分かりにくさは排除されますね。

このあたりの挙動のイメージは自分も同じです。色入力支援パレットは，あくまで純粋にカーソル位置に \color[rgb]{1,1,0} のような文字列を挿入することを補助するだけであって，それ以外の副作用はもたらさないのが分かりやすいと思います。

**Comment by aminophen** [comment]
もしかすると「色入力支援ダイアログ」さえあれば、モーダルにする必要はないかもしれませんね。

ダイアログで「挿入されるコマンドがプレビューされている」状態なら、そこに「目的の色らしきコマンドが現れているかどうか」でカラーパレットでの指定が反映されたかどうかわかります。それを目視で確認してから挿入ボタンをクリックするので、パレット自体がモードレスでも分かりにくいとまではいかないかも。

**Comment by aminophen** [comment]
ふと MS Word のカラーパレットを見ると、モーダルでした… Office for Mac 2011 です。

![2015-03-09 12 07 24](https://cloud.githubusercontent.com/assets/9957466/6549362/f2e64300-c654-11e4-9ec8-3e317f421021.png)

できなくはないのだと思いますが、先ほどのとおりモードレスでも良いかと。

**Comment by doraTeX** [comment]
WordのものはおそらくMac標準のものに近いものを自作で作っているのだと思います。

とりあえず，[それらしいものを作ってみました](https://dl.dropboxusercontent.com/u/5807100/TeX2img-colorTest.zip)のでお試しください。細部の詰めはまだまだですが。
表示＞色入力支援パレット から出てきます。

![2015-03-09 13 15 39](https://cloud.githubusercontent.com/assets/6186180/6549911/2f4f4832-c65f-11e4-8fee-21734b6ecce7.png)

カラーパネルの挙動がMac OS X標準のものなので，ちょっと気持ち悪い動きをします。

1. 色入力支援ウィンドウを表示する
2. カラーパネルを出す
3. 色を選んで遊ぶ
4. カラーパネルを出しっ放しにした状態で色入力支援ウィンドウを閉じる
5. するとカラーパネルだけが取り残される
6. 色入力支援ウィンドウを再表示する
7. すると，この状態では色入力支援ウィンドウとカラーパネルとの関連づけ（的なもの）が切れている状態になっているため，カラーパネルで色を選んでも色入力支援ウィンドウ上の文字列は変化しない

これが，Mac OS X としては標準の挙動なのですが，私が分かりにくいと思い，気に入らない部分なのです。

[![2015-03-09 13 19 39](https://cloud.githubusercontent.com/assets/6186180/6549900/fbb6eab6-c65e-11e4-98f1-d08e419a1a20.png)](https://twitter.com/doraTeX/status/573152505816727552)

Mac OS Xのアプリ設計の標準的考え方では，「アプリ1つにつきカラーパネルは1つで，いろんな設定項目でそれを共有する」となっており，その仕様に従ってこのような挙動となっています。

**Comment by aminophen** [comment]
> カラーパネルを出しっ放しにした状態で色入力支援ウィンドウを閉じる
> するとカラーパネルだけが取り残される

確かにそこが気持ち悪いですね。色入力支援ウィンドウを閉じると同時にカラーパネルだけが消えれば何の違和感も無いのですが…

4 つの選択肢があるのはいいですね。どれも color または xcolor を読み込めば良いのですね。

 # もちろん dvipdfmx の場合はドライバ指定を忘れずに：テンプレートのときにやっておけばよかったとちょっと後悔…

**Comment by doraTeX** [comment]
> > カラーパネルを出しっ放しにした状態で色入力支援ウィンドウを閉じる
> > するとカラーパネルだけが取り残される
> 
> 確かにそこが気持ち悪いですね。色入力支援ウィンドウを閉じると同時にカラーパネルだけが消えれば何の違和感も無いのですが…

この問題を解決し，その他細かい部分も多少詰めたバージョンを作成しました。挙動はだいぶ自然なものにできたのではないかと思います。ぜひお試しください。
[TeX2img for Mac ver. 1.8.9 beta 1](https://dl.dropboxusercontent.com/u/5807100/TeX2img1.8.9b1.zip)

> もちろん dvipdfmx の場合はドライバ指定を忘れずに：テンプレートのときにやっておけばよかったとちょっと後悔…

確かに
```tex
\usepackage[dvipdfmx]{graphicx,color}
```
とかを入れておいた方がよかったですね……。

**Comment by aminophen** [comment]
> TeX2img for Mac ver. 1.8.9 beta 1

色入力支援ウィンドウを閉じると同時にカラーパネルだけが消えるだけで、かなり自然になりました。気になるのが

ある場所にコマンドを挿入した後、色入力支援パネルを出したまま別の場所にカーソルを動かしたとき

で、この場合は連動（？）が切断されます。

- 挿入またはコピーを一度クリックしたらウィンドウを2つとも閉じる
- 連動が切断されないようにする（無理そう…）

のいずれかだとより自然です。

**Comment by aminophen** [comment]
> ある場所にコマンドを挿入した後、色入力支援パネルを出したまま別の場所にカーソルを動かしたときで、この場合は連動（？）が切断されます。

より正確には「あれ、さっきまでパレットで赤を選んでいたのに、エディタでカーソルを動かしたら途端に黒になってしまった」という感じです。

**Comment by doraTeX** [comment]
それは，色パネルの色の制御対象が，ソースエディタの文字色に移ってしまうからです。OS X の設計である「色パネルはアプリケーション単位で1つで，それが様々な対象の色をコントロールする」という仕様の結果ですね。ちなみにその状態で色を選択するとソースエディタの文字色が変わってしまうはずです。
これは嬉しくないので，何とか対処を試みてみます。

**Comment by doraTeX** [comment]
上記問題の解決も含め，だいぶ挙動を改善できてきたと思います。いかがでしょうか。
[TeX2img for Mac Ver. 1.8.9 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2img1.8.9b2.zip)

**Comment by aminophen** [comment]
> TeX2img for Mac Ver. 1.8.9 beta 2

エディタをクリックするとカラーパレットが消えるので、制御対象が移ってしまうことは考慮しなくて良くなりますね！ 入力支援ウィンドウは残るので、次の色指定もスムーズだと思います。

先ほどの「色入力支援ウィンドウを閉じると同時にカラーパネルが消える」のおかげで、例えばフォント設定ウィンドウから呼ばれたカラーパレットも取り残されなくなっていますね。挙動がわかりやすくなってきたので、良い方向だと思います。

**Comment by doraTeX** [comment]
カラーパネルの挙動はだいぶ改善されました。
今悩んでいるのは，「コピーボタンを押したときのレスポンス」です。
今はボタンを押してもコピーしたのかどうかの応答がないので分かりにくいかなと思っています。ただ，コピーが完了したことのレスポンスをどのようにするのが自然かが悩ましいところです。
いちいち

コピーしました
[OK]

のようなダイアログが出るのはあまりにうっとうしいですし。

10.8 以降であれば，OSの通知センターに通知することも可能です。これであれば，ボタンを押したりする必要はありません。ですが，たかがコピー完了程度で通知センターに通知を出す（すると履歴が残る）のも大げさな気がします。
どういう応答が自然でしょうかね。

**Comment by aminophen** [comment]
そもそもコピーボタンが必要なのかどうか、という点です。Ctrl + C で十分ではないでしょうか。

**Comment by doraTeX** [comment]
ではコピーボタンは削除しましょう。

あと，公式で色入力をサポートするからには，やはりテンプレートの修正は必要ですね。

LaTeX, XeLaTeX, LuaLaTeX については
```tex
\usepackage{graphicx,color}
```

pLaTeX, upLaTeX については
```tex
\usepackage[dvipdfmx]{graphicx,color}
```

をプリアンブルテンプレートに付加する感じでいきましょうか。

**Comment by aminophen** [comment]
付加の方針はいいと思います。早速バージョン番号で対処することになりそうですね…

ただ、既存のテンプレートを上書きするか、別名で追加するかという問題が発生してしまいました。

**Comment by doraTeX** [comment]
上書きでいいでしょう。

* LaTeX (graphicx, colorなし)
* LaTeX (graphicx, colorあり)
* pLaTeX (graphicx, colorなし)
* pLaTeX (graphicx, colorあり)
* upLaTeX (graphicx, colorなし)
* upLaTeX (graphicx, colorあり)
* XeLaTeX (graphicx, colorなし)
* XeLaTeX (graphicx, colorあり)
* LuaLaTeX (graphicx, colorなし)
* LuaLaTeX (graphicx, colorあり)

とかややこしすぎますしメリットがありませんからね😅

同名テンプレートの更新なので，以前決めた仕様通り，「バージョンアップ時の更新処理は特になし」「デフォルトテンプレートの復元を選べば更新版が復元される」という挙動でよいでしょう。

**Comment by aminophen** [comment]
> 同名テンプレートの更新なので，以前決めた仕様通り，「バージョンアップ時の更新処理は特になし」「デフォルトテンプレートの復元を選べば更新版が復元される」という挙動でよいでしょう。

勝手に上書きはしない方針でしたね。それでいきましょう。
