### ISSUE TITLE
pdftexパス

### ISSUE THREAD

**Issue by abenori** [doraTeX/TeX2img#110]
[https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2919#p17206](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2919#p17206)の件に関連してです．

こちらでは一部の処理にpdftexを使っています（そちらも同様かと思います）が，そのパスは「platexと同じ場所にあるもの」という風にしています．ただ，かなり本質的につかっていますので，パス指定の欄にpdftexも加えてよいのではないかと思いました．どうでしょう？

**Comment by doraTeX** [comment]
確かにそうですね。macOSでも，例えばDockerでplatexを起動している場合などは同様の状況に該当しそうです。そういたしましょう。

**Comment by doraTeX** [comment]
#102 に伴い，pdftex に依存する箇所がなくなったので，結果的に不要となりました。
