### ISSUE TITLE
配布サイトの再デザイン

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#12]
現在の配布サイトが縦に長くなってきたので，そろそろページを切り分けて見やすくしたい。
## ページ構成の案
- トップページ（特徴・スクリーンショット・連絡先を含む）
- 解説記事へのリンク集
- ダウンロード・動作条件
- インストール法・アンインストール法・トラブルシューティング
- Tips集
- ソースコード・ライセンス
- 更新履歴
## Tips集に載せるTipsの案
- 2種類の入力補完について
- 文字色や背景色を変える方法
- 幅を一定に保つ方法
- 画像からソースの復元
- Adobe Illustrator との連携
- 複数ページドキュメントの活用
- EPSから他形式への変換ツールとしての使用法
- \begin{document}～\end{document} 全体を自動的にディスプレイ数式にする方法
- 各スクリーンショットも一新する

**Comment by aminophen** [comment]
確かに昔に比べるとかなり伸びましたね笑
目次があるので不便は感じていませんでしたが、Tips を充実させるとなると別ページは必要ですね。例えば私なら、細分化しすぎないように

- トップページ（特徴・スクリーンショット・動作条件・ライセンス・連絡先を含む）
- ダウンロード・インストール法・アンインストール法
- 解説記事へのリンク集・Tips集
- トラブルシューティング
- ソースコード・更新履歴

くらいにします。

**Comment by aminophen** [comment]
<a href="http://island.geocities.jp/loveinequality/whitebox.html">画像の横幅を常に一定にして出力する</a>の項で、color パッケージに dvipdfmx ドライバ指定を加えるべきではないでしょうか。

**Comment by doraTeX** [comment]
ですねぇ。スクリーンショットも Mac OS X 10.5 Leopard のもので，もはや化石時代。 
#12 とあわせて一新が必要ですね。

**Comment by aminophen** [comment]
配布サイトの「特徴」で

> カラーパレットから \color など LaTeX の色命令を生成する，色入力支援機能があります（Mac版）。

とありますが、Win 版にももう色入力支援があります。

**Comment by doraTeX** [comment]
> 配布サイトの「特徴」で
> >ラーパレットから \color など LaTeX の色命令を生成する，色入力支援機能があります（Mac版）。
>
> とありますが、Win 版にももう色入力支援があります。

修正しました。情報ありがとうございます。

**Comment by doraTeX** [comment]
「[Tips・トラブルシューティング](http://island.geocities.jp/loveinequality/#tips)」は [TeX2img FAQ](http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeX2img%20FAQ) に丸投げしました。

**Comment by aminophen** [comment]
配布サイトの Tips が消えた影響で、サイト上部の

> EMF ファイル（Windows版のみ。Mac版は補助ツールで対応。）

の補助ツールへのリンクが切れていることに気づきました。[ツール](http://island.geocities.jp/loveinequality/eps2emf_1.0.zip)自体は生きているようですね。

**Comment by doraTeX** [comment]
ありがとうございます。[EMF 生成の件だけ Tips を復活させました](http://island.geocities.jp/loveinequality/#eps2emf)。

**Comment by doraTeX** [comment]
今更ながら favicon を設置しました。

**Comment by aminophen** [comment]
たしかに favicon がありませんでしたね。

ぼちぼち Wiki の TeX2img FAQ を「TeX2img/使い方」と「TeX2img FAQ」に分割したほうがよいのではないかと思っています。私のブログにある TeX2img 関連記事も近々整理しようと思っていて、もしかすると Markdown でエクスポートして GitHub に置くほうが便利かもと検討中です。時間ができたら考えてみます。

**Comment by aminophen** [comment]
> Markdown でエクスポートして GitHub に置くほうが便利かも

というのは、お察しのとおり(?)旧記事のメンテナンスに時間を割けない状態になっているためです。正式リリース前に更新するわけにはいかないため、リリース後に記憶を頼りに更新しなければならず管理効率が悪いかなと思っています。そこで

- いったん Markdown にエクスポートして、私のところに TeX2img のドキュメンテーション用リポジトリを新設する
- 開発が進んで変更が生じた場合は Markdown を逐一編集する
- 従来の解説ページなどからのリンク先はすべて GitHub リポジトリに切り替える

ただ一つ、GitHub はツイートやシェアのボタンがないので拡散されにくいというのがドキュメント置き場としてのデメリットです。はてなブログは一般に検索ヒットしやすいというのもあります。

- 完全にドキュメントを GitHub に移行して dev branch をリアルタイム修正し、正式リリース時点で master branch に移す
- あくまで GitHub のドキュメントは開発版ドキュメントという位置づけでリアルタイムに修正し、正式リリース時点でドキュメントの正式公開として私が Markdown をはてなブログに貼り付ける

もありうるかなと思いました。運用を見直そうかと思っていますが、いかがお考えでしょうか？

**Comment by doraTeX** [comment]
お忙しい中，いつもドキュメントの整備ありがとうございます。

> ただ一つ、GitHub はツイートやシェアのボタンがないので拡散されにくいというのがドキュメント置き場としてのデメリットです。はてなブログは一般に検索ヒットしやすいというのもあります。

確かに，それらは気になる点ではありますね。
それを考えると，お手間でなければ，

> あくまで GitHub のドキュメントは開発版ドキュメントという位置づけでリアルタイムに修正し、正式リリース時点でドキュメントの正式公開として私が Markdown をはてなブログに貼り付ける

の方が確実そうな気がします。

ただ，基本的には aminophen さんにとって都合のよい方法でやっていただいて一向に構わないと思います。

**Comment by aminophen** [comment]
> あくまで GitHub のドキュメントは開発版ドキュメントという位置づけでリアルタイムに修正し、正式リリース時点でドキュメントの正式公開として私が Markdown をはてなブログに貼り付ける

既に編集済みのドキュメントを開発段階で作っておきさえすれば、あとは貼るだけですので全く手間ではないです。（それに、ブログのアクセス数はまったく気にしていないのですが、やはりドキュメントは読まれないと意味がないので本件では重視することにします。）開発段階でリアルタイムで編集してよいとなると捗りそうですので、その方向で進めてみます。ご意見ありがとうございます。

**Comment by doraTeX** [comment]
favicon のおかげで Safari の表示も綺麗になりました😄

<img width="264" alt="2015-11-10 0 13 07" src="https://cloud.githubusercontent.com/assets/6186180/11037200/e6834a0c-873f-11e5-960b-0ea35ea21465.png">

**Comment by doraTeX** [comment]
配布サイトデザインをモダンな感じに再構成完了。
