### ISSUE TITLE
ghostscript に -dNOCACHE を付ける

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#13]
# 項目
gs 実行時のオプションに -dNOCACHE を付与しておいた方がよさそうです。

# 理由
現状では，gs 9.15 未満で実行したときに，一部の小さな文字がアウトライン化されず，ビットマップとして保存される現象が起こります。

# 再現例
gs 9.07 を用いて，
```tex
あ，、。．$2-1$
```
をアウトライン化したEPSやPDFに変換すると，句読点やマイナスの部分がビットマップ化されて埋め込まれていることが分かります。

![2015-03-09 22 48 42](https://cloud.githubusercontent.com/assets/6186180/6556124/c3ecc844-c6ae-11e4-8586-e641c3b1aac9.png)

-dNOCACHE を付けると正しくアウトライン化されます。

![2015-03-09 22 50 44](https://cloud.githubusercontent.com/assets/6186180/6556131/c7b4512c-c6ae-11e4-818a-5da5285e4ead.png)

**Comment by doraTeX** [comment]
195f9eccd9907ba641d24bdd43f2ea3728f0c2ce で修正。

**Comment by aminophen** [comment]
確かに。全く気づいていませんでした…

こちらも abenori さんにも相談です。現在 Windows 版は gs9.14 以前で

<pre class="code">gswin32c.exe -q -sDEVICE=epswrite -dFirstPage=1 -dLastPage=1 -sOutputFile="tmpCD2E-1.eps" -dNOPAUSE -dBATCH -r20016 "tmpCD2E.pdf"</pre>

というコマンドを渡しています。Mac 版は -dSAFER も付いているようですね。これも含めて統一を検討した方がよさそうです。

**Comment by doraTeX** [comment]
> Mac 版は -dSAFER も付いているようですね。

今ソースを検索したところ，現バージョンでは付いていないようです。[-dSAFER がONだと環境によっては日本語関係でエラーが出ることがある](http://jrf.cocolog-nifty.com/software/2006/02/post_12.html) という話を聞いたことがありますので，特に問題なければ今のままでもよいかなぁと思っていました。

**Comment by abenori** [comment]
ええと，とりあえず-dNOCACHEをつけておけばよいのかな？

**Comment by doraTeX** [comment]
> ええと，とりあえず-dNOCACHEをつけておけばよいのかな？

はい，とりあえずそれで解決するはずです。

**Comment by aminophen** [comment]
-dSAFER は勘違いでした。すみません。では Mac/Win ともに -dNOCACHE を付ければ大丈夫ですね。gs9.14 以前で起こるというおはなしですが、gs9.15 以降には付けますか？

**Comment by doraTeX** [comment]
> gs9.14 以前で起こるというおはなしですが、gs9.15 以降には付けますか？

付けておいても問題なさそうでしたので，とりあえず一律に付けておくようにしてあります。

**Comment by aminophen** [comment]
本件は「gs9.10 以前でフォントがアウトライン化されないことへの対処」ですが、以前の gs の仕様変更への対応時に得た「gs9.15 以降では -dNoOutputFonts オプションを付けると細かいグリフもアウトライン化できる」という結果は、もしかすると本質はこの -dNOCACHE なのではないかと思いました。実際に Windows 版の gs9.15（角藤版）で試してみると、-dNoOutputFonts がなくても -dNOCACHE さえあればアウトライン化に成功しているように見えます。この結果は Mac でも再現するのでしょうか。

**Comment by doraTeX** [comment]
[ここ](http://stackoverflow.com/questions/28797418/replace-all-font-glyphs-in-a-pdf-by-converting-them-to-outline-shapes) や [ここ](http://quabr.com/10773616/prevent-ghostscript-from-rasterizing-text) などの記述によると，どうも，gs 9.15 以降では -dNOCACHE は -dNoOutputFonts へ置き換えることが推奨されているようです。
（今のMac版では，gs 9.15 以降では念のため両方付けてありますが。）

**Comment by aminophen** [comment]
追加情報で、<a href="http://tex.stackexchange.com/questions/22095/how-to-prevent-ghostscript-from-rastering-the-font-when-converting-pdf-or-eps-to">もともとデバッグ用だが、-dNOCACHE はアウトライン化という点で有用である</a>旨が書かれています。グリフのアウトライン化は「劣化」だといわれるとおり、テキスト情報を失い、かつレンダリングにも時間がかかるので「デバッグ用の最終手段」として開発されたのだと思います。

一方で、より新しい情報では gs9.15 以上の pdfwrite/ps2write/eps2write に -dNoOutputFonts オプションが追加されたことの重要性は「PDF のアウトライン化」の手順において<a href="http://stackoverflow.com/questions/9106959/converting-searchable-pdf-to-a-non-searchable-pdf">従来の PDF -> EPS -> PDF という二段階を経た手順が PDF -> PDF の一段階で済むようになった</a>ことのようです。

**Comment by doraTeX** [comment]
> gs9.15 以上の pdfwrite/ps2write/eps2write に -dNoOutputFonts オプションが追加されたことの重要性は「PDF のアウトライン化」の手順において従来の PDF -> EPS -> PDF という二段階を経た手順が PDF -> PDF の一段階で済むようになったことのようです。 

なるほど，これは興味深い情報ですね。うまくいけばアウトライン化PDF出力（およびそれを経由するSVG出力）の高速化につながりそうですね。（従来のアウトライン化EPS出力と同等のハイクオリティなアウトライン化ができるのであれば。）

**Comment by aminophen** [comment]
> どうも，gs 9.15 以降では -dNOCACHE は -dNoOutputFonts へ置き換えることが推奨されているようです。
> -dNOCACHE がいわば非公式にアウトライン化を強制していたものを、gs9.15 の -dNoOutputFonts オプションで公式にサポートしたような形だと思います。

ということは、むしろ -dNOCACHE は gs9.15 以上で削除するのが推奨なのでしょうね。

**Comment by doraTeX** [comment]
> むしろ -dNOCACHE は gs9.15 以上で削除するのが推奨なのでしょうね。

そのようですね。というわけで， 74a850cf51d5443b6ea7a53dea131a28d6a8be6f ではそのように対処しておきました。
gs は想像以上に進化・変化が速くて追いつくのが大変ですねぇ……。（epswrite の削除は影響甚大でしたね😅）

**Comment by aminophen** [comment]
> > むしろ -dNOCACHE は gs9.15 以上で削除するのが推奨なのでしょうね。

> そのようですね。というわけで，  74a850c  ではそのように対処しておきました。

gs のアウトライン化の解説記事も修正しておきます。新たな知見が得られて良かったです。

**Comment by doraTeX** [comment]
> > gs9.15 以上の pdfwrite/ps2write/eps2write に -dNoOutputFonts オプションが追加されたことの重要性は「PDF のアウトライン化」の手順において従来の PDF -> EPS -> PDF という二段階を経た手順が PDF -> PDF の一段階で済むようになったことのようです。
>
> なるほど，これは興味深い情報ですね。うまくいけばアウトライン化PDF出力（およびそれを経由するSVG出力）の高速化につながりそうですね。（従来のアウトライン化EPS出力と同等のハイクオリティなアウトライン化ができるのであれば。）

gs 9.15 において，

* -sDEVICE=eps2write -dNoOutputFonts による「PDF → アウトライン化EPS」
* -sDEVICE=pdfwrite -dNoOutputFonts による「PDF → アウトライン化PDF」

を比較してみたところ，後者ではクロップがなされないことがわかりました。後者の方法の場合，別途 pdfcrop にかける必要が出てきてしまいます。そのため，どちらにせよ2段階の作業が必要になります。
そう考えると，場合分けの分岐を増やしてまで変換スキームを変更する必要はなさそうです。

**Comment by aminophen** [comment]
> 後者ではクロップがなされないことがわかりました。

なるほど、EPS を経ることでクロップが勝手に行われるのを利用していた従来のスキームのほうが良いですね。逆に「もとの PDF に余白があればそれを維持して単にアウトライン化する」ということが可能になったわけですね。これは従来できなかったことなので重要な更新ですが、TeX2img の目的にはそぐわないですね。
