### ISSUE TITLE
「少々のコンパイルエラーは無視して画像化を強行する」オプションを廃止するか？

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#15]
理由：[エラーを無視しても意図する結果はまず得られない](http://d.hatena.ne.jp/acetaminophen/20150615/1434383196)であろうから。

**Comment by aminophen** [comment]
このオプションは実用したことがないので、メリットを感じていませんでした。個人的にはなくても良いです。「Error が出て、なおかつ正常な画像が得られる例」はあるのでしょうか？ Warning ならいくらでも考えられますが…

**Comment by aminophen** [comment]
一つだけ「エラーが発生しても正常にコンパイルで DVI や PDF ができる例」を思いつきました。
~~~~ latex
\listfiles
\documentclass{jsarticle}
\usepackage[dvipdfmx]{xcolor}
\usepackage[dvipdfmx]{color}
\pagestyle{empty}
\begin{document}
あいうえお{\color[rgb]{1,0.501960784313725,0} かきくけこ}さしすせそ
\end{document}
~~~~
このソースの場合、xcolor と color のドライバ指定がともに dvipdfmx で一見正しいですが、color パッケージを読もうとして
~~~~
! LaTeX Error: Option clash for package color.
~~~~
と出ます。\listfiles を見ると、このエラーのせいで color パッケージは読み込まれません（color パッケージ側の問題でしょうか…）。しかし、\color コマンドは xcolor パッケージが定義しているので、color でエラーが発生しているにもかかわらず正常にコンパイルが通ります。

**Comment by doraTeX** [comment]
なるほど……。このオプションの存在意義が一応あったということですね。
ただ，かなり特殊な例となりますので，このオプションを存続させるメリットとデメリットはどちらが大きいでしょうかね……？

**Comment by aminophen** [comment]
選択肢は

- オプションを廃止する
- オプションを存続させるが UI に推奨しない旨を明記する（画像の成否は保証しない）

のいずれかですね。私は廃止してもよいと思っていますが、color と xcolor の問題は複雑なので、廃止すると影響が出る人が出ないとも限りませんね… なんとなく、例えば \usepackage[dvipdfmx]{xcolor} より後に読み込んだパッケージ内部が
~~~~ latex
\PassOptionsToPackage{dvipdfmx}{color}
\RequirePackage{color}
~~~~
ならセーフですが
~~~~ latex
\RequirePackage[dvipdfmx]{color}
~~~~
と書かれていると Option clash するような気がします。

**Comment by aminophen** [comment]
一つの案ですが、安全なのは

- オプションを存続させ、画像生成時に「コンパイル中にエラーが発生しました。画像は生成しましたが、期待外れかもしれません。」みたいなエラーメッセージを出す

とかでしょうか。いままでのだと、ON の場合には**ログを見なければエラーが出たかどうかわからない**という点がユーザに優しくなかったのではないでしょうか。「エラーが出たならそれをもっと目立たせる」だけでも、先日のような誤解は防げるかもしれません。

**Comment by doraTeX** [comment]
「少々のコンパイルエラーは無視して画像化を強行」がなされた場合，次のような警告ダイアログを表示するようにしてみました。

<img width="420" alt="2015-07-31 7 34 18" src="https://cloud.githubusercontent.com/assets/6186180/8996892/a1596652-3756-11e5-9a2b-c8657a5c40e3.png">

**Comment by abenori** [comment]
傍観していましたが，Mac版にあわせて（というよりはオリジナル作者の考えにあわせて）おきます．
