### ISSUE TITLE
コンパイル中断機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#16]
Windows版同様に，コンパイル中断機能を設ける。

## 仕様案
* コンパイル中には「画像生成」ボタンが「コンパイル中断」ボタンに変わる。
* ショートカットキーはコンパイルと同じ Command+T でよいか？でもそうすると二度押ししてしまったらコンパイル中断になってしまう。Macらしい「中断」のショートカットキーは Command + . だろうか。（例：スクリプトエディタでのAppleScript実行中断，Excelマクロの実行中断，Mathematicaの計算中断）

**Comment by aminophen** [comment]
早速の検討、ありがとうございます。

ショートカットキーは悩ましいです… 二度押しする可能性がどの程度あるのか分かりませんし、ここはネイティブの Mac ユーザである doraTeX さんにお任せしようと思います。

**Comment by aminophen** [comment]
やっぱり中断機能が欲しくなりました。TeXShop の中断機能は Command + Option + Control + A らしいですが、これは TeX2img にしては複雑すぎるので短い Command + . か Command + T の二択でよいですが、TeX 統合環境は Command + T で実行と中止が切り替わる（TeXworks (Win/Mac), LaTeXiT）のが目立つのと、Win 版との統一感から Command + T の方を個人的には推します。ただ、TeXstudio は F1 でタイプセットですが中断にショートカットキーは割り当てられていません。

 # ちなみに TeXShop のメニューから中断機能と作業ファイル削除機能を探すのに苦労しました… ファイルではなくタイプセットの下にあったほうがいいような。

**Comment by doraTeX** [comment]
色々と四苦八苦してみたのですが，中断機能を設けるのは原理的にかなり困難そうです。

# 理由

* コンパイル実行中に中断を受け付けるには，コンパイル処理実行中に画面のクリックやキー入力といったイベントを受け取らなければならない。
* コンパイル処理をメインスレッドで実行した場合，プログラム全体がそれが終わるのを待つため，コンパイル中はクリックやキー入力を受け取らなくなってしまう（現状はこの状態）。
* コンパイル処理中にクリックやキー入力を受け取るには，コンパイルを別スレッドに分離せねばならない。
* しかし，OS X の仕様により，別スレッドから画面の書き換えやダイアログ表示を行うとクラッシュします。すなわちUIの操作はスレッドセーフではありません。（これはWindowsとは異なる特徴です）。
* よって，画面書き換えなど伴う操作は別スレッドに分離できない。

## TeXShop はどうしているか

* TeXShop は，メインスレッド内でコンパイル処理を実行している。よってコンパイル中にログウィンドウの更新が可能。
* ただし，TeXShop は，「メインスレッドから呼び出したプロセスの終了を待たない」という方法によって，コンパイル処理を実行しつつ，クリックやキー入力を受け付けることができている。

## TeXShop と TeX2img の違い
### TeXShop の場合
* TeXShop は，プロセス呼び出しが1段階で済むようになっている。例えば pLaTeX のコンパイルの場合，ptex2pdf を呼び出すなどして，TeX→dvi→PDF の処理を1つの外部プロセスにまとめている。
* そして，コンパイル実行後は，PDFの更新を関知して，プレビューウィンドウを更新している。
* よって，「タイプセットボタンが押されたイベント処理としてコンパイルプロセスを呼び出した，後は裏で勝手にコンパイルをやっている，これでイベント処理は終了，キー入力の受付に戻ろう」という動きをしている。
* だからこそ，「コンパイル中にコンパイルプロセスを終了させるボタンを押したらそのイベント処理が発動する」という挙動が可能。

### TeX2img の場合

* それに対し，TeX2img は，何段階ものプロセス呼び出しが重なっている。「TeXのコンパイル」「その結果PDFではなくdviが生成されればdvipdfmx呼び出し」「次にgs呼び出し」……など，「前の処理が終わらないと次へ進めない」「前の処理結果を見てみないと次に呼び出すコマンドが確定しない」という連鎖になっている。
* よって，「画像生成」ボタンを押されたときに，TeXShopのように「コンパイルプロセスを呼び出したのでイベント処理はこれで終わり。クリックやキー入力の受付に戻ろう」ということができない。自分が呼び出したプロセスの終了を待ち，その後の処理をどうするかを自分で判断せねばならないので，呼び出したっきり放り投げることができず，ずっと面倒を見続けなければならない。
* メインスレッドで「呼び出したプロセスの終了を待つ」という動きをすると，その間クリックやキー入力が受け付けられなくなるので，「コンパイル中断」ボタンを押すことができなくなる。

このように，**コンパイルが単一プロセスの呼び出しだけで済んでしまうTeXShopと異なり，いくつものプロセス呼び出しを連鎖させる（かつその途中に画面の書き換えも行う）必要のあるTeX2imgでは，「コンパイル中断」ボタンを設けることが原理的に困難**となっています。

**Comment by doraTeX** [comment]
また，同じ理由で，かつてのWindows版にあったような「タイムアウト機能」を設けることも困難です。コンパイル処理実行中は，TeX2imgはメインスレッド内でそれに専念するしかなく，そこに他者が割り込むことができません。

**Comment by doraTeX** [comment]
一つ方法があるとすれば，TeX2img.app の中にCUI版のTeX2imgを内包させ，GUI版からはCUI版TeX2imgという単独のプログラムを呼び出すという形式をとることです。この場合，単一プロセスの呼び出しで済むので，GUI版としてはCUI版を起動した後は，それは放置しておいてGUIのイベント処理に戻ることができます。

ただし，この場合の欠点は，CUI版からはGUIのダイアログが表示できないことです。よって，「LaTeXのコンパイルに失敗しました」「エラーを無視して画像化を強行しました」など，状況に応じたGUIのダイアログを表示することができなくなります。
また，Illustratorへの配置など，GUI版ならではの機能も再設計が必要になります。

**Comment by aminophen** [comment]
> コンパイルが単一プロセスの呼び出しだけで済んでしまうTeXShopと異なり，いくつものプロセス呼び出しを連鎖させる（かつその途中に画面の書き換えも行う）必要のあるTeX2imgでは，「コンパイル中断」ボタンを設けることが原理的に困難

なるほど、これは TeX2img に中断機能を求めるのは酷ですね。詳しい説明、ありがとうございます。その機能だけのために再構成まで行うのはやりすぎですし、今のままで大丈夫です。検討いただきありがとうございます。

**Comment by doraTeX** [comment]
ただ，怪我の功名として，GUI版のログウィンドウの表示を「流れるように」表示させることができました。（従来はコンパイルが終了してから一括で表示される感じでした。）
この方が「頑張ってる感」が出ていいですね。

**Comment by aminophen** [comment]
> この方が「頑張ってる感」が出ていいですね。

確かに、LuaTeX-ja とかだと（あれ、始まったのかな？）と思ったりするので、頑張ってる感があると安心します。

**Comment by doraTeX** [comment]
頑張ってる感を出した，[Ver. 1.9.6 beta 4](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b4.zip) を作りました。
白紙ページの扱いの仕様が確定したら，そろそろ 1.9.6 としてリリースしてよさそうですね。

**Comment by doraTeX** [comment]
上記のバグは Ver. 1.9.6 beta 5 で解決し，無事に「頑張ってる感」が正しく出るようになりました。

**Comment by abenori** [comment]
知らないのでとんちんかんなことを言っているかもしれませんが……

> よって，画面書き換えなど伴う操作は別スレッドに分離できない。

http://shin.hateblo.jp/entry/2014/05/04/222104
にあるように，メインスレッドに呼び出しをお願いすることはできないのでしょうか？（釈迦に説法ですが，Windowsの方はこれですね．）

**Comment by doraTeX** [comment]
そうでした。確かに，`performSelectorOnMainThreadwithObject:waitUntilDone:` を使えばうまく行きそうですね。ありがとうございます。

ただ，UIに関係する部分の呼び出しを一つ残らずこの形に分離せねばならず，全体の精査が必要なので，時間があるときにぼちぼち考えてみることにします。

**Comment by doraTeX** [comment]
> ただ，UIに関係する部分の呼び出しを一つ残らずこの形に分離せねばならず，全体の精査が必要なので，時間があるときにぼちぼち考えてみることにします。

ぼちぼち考えてみてた結果，コンパイル中断機能を試験搭載した [Ver. 1.9.7 beta 7](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b7.zip) を作りました。

* ショートカットは Command+. としました。コンパイル中にこれを押すとコンパイルが中断されます。
* ログウィンドウに「TeX2img: 画像生成を中断しました。」というメッセージが表示されます。
* GUI版をマルチスレッド化したので，コンパイル実行中もソースの編集などUI操作が可能です。
* ただし「コンパイル中断」の動作はあまり安定していません。中断しようとしてもできなかったり，なぜか「画像生成を中断しました」のメッセージが表示されなかったり，中断した瞬間にTeX2imgがクラッシュしたり，中断した直後のコンパイルが1回だけ空振りしたりなど，色々と不安定な挙動を示します。（タイミング次第であり，再現性が十分でありませんが。）

このように，若干不安定な挙動ではありますが，「ないよりはマシ」くらいのノリで搭載しておいてもよいでしょう。無限ループに陥った TeX ソースのコンパイルを止めたりするには役立つはずです。
安全なマルチスレッドプログラミングは難しいです……。

**Comment by aminophen** [comment]
> ぼちぼち考えてみてた結果，コンパイル中断機能を試験搭載した Ver. 1.9.7 beta 7 を作りました。

大変な作業をしていただいたようで、感謝いたします。Ver. 1.9.7 beta 7 を試してみました。

> - ただし「コンパイル中断」の動作はあまり安定していません。…色々と不安定な挙動を示します。（タイミング次第であり，再現性が十分でありませんが。）

私の手元では Lion 上で「中断しようとしてもできない」「中断しましたのメッセージが表示されない」は起きましたが、致命的なものは起きていませんでした。確かにどのタイミングで中断するかによる気がします。テスト回数が少ないですが…

> - 無限ループに陥った TeX ソースのコンパイルを止めたりするには役立つはずです。

それは一応コンパイル最大回数が効くはずなので、中断機能が働かなくても何とかなると思います。

Windows 版と異なる点は

- 中断した場合に一時ファイルが残る（Windows 版は中断後に削除するようになっています）
- 画像ファイル生成ボタンがグレーアウトしたままになる（Windows 版は中断ボタンに切り替わる）

です。2番目のは機能が不安定だとすれば GUI に中断ボタンを表示するのはかえって危険かもしれないので、このままで良いと思います。一時ファイルが消えてくれれば嬉しいかもしれないです。

**Comment by doraTeX** [comment]
> * 無限ループに陥った TeX ソースのコンパイルを止めたりするには役立つはずです。
>
> それは一応コンパイル最大回数が効くはずなので、中断機能が働かなくても何とかなると思います。

無限ループというのは，

```tex
\loop\iftrue\repeat
```

とか

```tex
\def\hoge{\hoge}\hoge
```

のような制御綴展開の無限ループのつもりでした。

> * 中断した場合に一時ファイルが残る（Windows 版は中断後に削除するようになっています）

これは何とかしたいですね。やり方を工夫する必要がありますが，トライしてみます。

> * 画像ファイル生成ボタンがグレーアウトしたままになる（Windows 版は中断ボタンに切り替わる）

こちらもトライしてみます。安全にできそうであれば採用しましょう。

**Comment by aminophen** [comment]
> 制御綴展開の無限ループ

なるほど、そういう可能性もありました。確かに中断機能が役立つ場面ですね。

> >  - 中断した場合に一時ファイルが残る（Windows 版は中断後に削除するようになっています）
> 
> これは何とかしたいですね。やり方を工夫する必要がありますが，トライしてみます。

「一時ファイルを削除する」が ON なら削除されたほうがすっきりはしますね。よろしくお願いします。

> > - 画像ファイル生成ボタンがグレーアウトしたままになる（Windows 版は中断ボタンに切り替わる）
> 
> こちらもトライしてみます。安全にできそうであれば採用しましょう。

おお、可能ならばよろしくお願いします。

**Comment by doraTeX** [comment]
* 「一時ファイルを削除する」が ON のときには，コンパイル中断時にも一時ファイルを削除するように
* 変換作業実行中には「画像生成」ボタンが「中断」ボタンに変わるように

修正した [Ver. 1.9.6 beta 8](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b8.zip) を作りました。
そろそろ正式リリースが近づいてきましたかね!?

**Comment by aminophen** [comment]
Mac 版  Ver. 1.9.6 beta 8 を試しました。

> - 「一時ファイルを削除する」が ON のときには，コンパイル中断時にも一時ファイルを削除するように
> - 変換作業実行中には「画像生成」ボタンが「中断」ボタンに変わるように

これらは期待通りに機能していました。ありがとうございます。

制御綴展開の無限ループの場合は手元では 100% 停止に成功します。どうやら TeX が走っている間は「中断」がほとんど確実に効くので、これは助かりますね。gs が走り始めてからの中断は効かないことが多い一方で、ときどき効いたりもするのでよくわかりません。が、ここで強制停止させる必要はまずないですし #21 も大丈夫そうですので、いよいよ正式リリースですね。

**Comment by doraTeX** [comment]
足かけ6日間かかりましたが，お陰様で，とうとう新バージョン 1.9.6 としてリリースできました！

[更新履歴](http://island.geocities.jp/loveinequality/#history)上は

> * GUI版：出力に白紙ページが含まれる場合の挙動を改善。一辺がゼロになる画像は生成しないように（余白付与の結果正の幅を持つ白紙画像が生成される場合は警告）。

という一行で済んでいますが，これは考慮すべきパターンが非常に多くて大変でしたね……😅

**Comment by aminophen** [comment]
> 足かけ6日間かかりましたが，お陰様で，とうとう新バージョン 1.9.6 としてリリースできました！

本当にありがとうございました＆おつかれさまでした。目立たない割に相当大変な作業だったはずですが、無事リリースされて安心しました。場合分けは大変ですね…

**Comment by doraTeX** [comment]
確かに，今回のアップデートは，ユーザに直接役に立つ新機能としては

* コメントアウト・非コメント化・行の左右シフト
* コンパイル中断機能

程度であって，あまり大きく目立つアップデートではありませんが，内部的には色々大きく変わりましたね。

ついでに，配布サイト上のMac版のスクリーンショットがだいぶ古くなっていたので，最新版のスクリーンショットに差し替えておきました。

**Comment by aminophen** [comment]
> 最新版のスクリーンショットに差し替えておきました。

Yosemite 以降に合ったスクリーンショットになりましたね。非常に細かいですが、ソース中に `<` が一つ余分に紛れ込んでいることに気づきました。正しくは

~~~~ tex
\textgt{定理その\ajMaru{1}}

$0 \leqq m < n$に対して，
\[
  \sum_{k=m}^{n-1} \frac{1}{n-k} \binom{k}{m}
  = \binom{n}{m} \sum_{k=m+1}^n \frac{1}{k}
\]
~~~~

ですね。

Windows 版も ImageMagick を使わなくなったので、スクリーンショットを最新ベータ版に置き換えていただけるとありがたいです。[こちら](https://dl.dropboxusercontent.com/s/a8mz68o0lsklu4i/TeX2imgWin156beta-screen.zip)に一セットあります。Windows 版 Illustrator は使っていないので抜けていますが。

**Comment by doraTeX** [comment]
> 非常に細かいですが、ソース中に < が一つ余分に紛れ込んでいることに気づきました。

いつもながら細かいチェックありがとうございます。流石ですね。

> Windows 版も ImageMagick を使わなくなったので、スクリーンショットを最新ベータ版に置き換えていただけるとありがたいです。こちらに一セットあります。Windows 版 Illustrator は使っていないので抜けていますが。

ありがとうございます。差し替えました。ついでに，Mac 版 Illustator, PowerPoint の画像も最新版に置き換えました。

**Comment by doraTeX** [comment]
Ver. 1.9.6 でつまらないバグが入っていたので，急遽 Ver. 1.9.7 へバージョンアップしておきました。
（Ver. 1.10.x がいよいよ近づいてきましたね。）

**Comment by aminophen** [comment]
ありがとうございます。TeX2img 1.9.7 をインストールしました。

TeX2img FAQ の \expandafter が減ってすっきりしましたね😁
 # align* で囲むこともできたらいいなと思ったり… [bxenclose](http://d.hatena.ne.jp/zrbabbler/20150805/1438724003) でもこれは無理ですね。

**Comment by doraTeX** [comment]
> align* で囲むこともできたらいいなと思ったり… bxenclose でもこれは無理ですね。

```tex
\documentclass[fleqn,papersize]{jsarticle}
\usepackage{amsmath,amssymb}
\pagestyle{empty}
\makeatletter
\let\my@document\document
\def\document#1\end{\my@document\begin{align*}#1\end{align*}\end}
\makeatother
\begin{document}
x-1&=5\\
x&=6
\end{document}
```

のようにすれば一応通りますが，これだと数式内に array 環境など \begin～\end が入ると対応できませんので不十分ですね。

**Comment by doraTeX** [comment]
ちなみに FAQ の

> ただし，\[ ... \] 内に空行 (\par) は入れられませんので，空行を入れないように注意してください。

ですが，以前 #5 での議論で，`\end{document}` の直前に改行を入れて保存するようになったので，この「全体を \[ ... \] で囲む」設定になっている場合，行末に改行が入ると，保存されるソース上では空行が生まれてしまいます。

よって，「空行を入れない」だけでなく，「最終部にも改行を挿入しない」ことに注意せねばなりませんね。

**Comment by aminophen** [comment]
> 「最終部にも改行を挿入しない」ことに注意せねばなりませんね。

念のため書き加えておきました。align* 環境を入れるのは難しそうですね。

**Comment by doraTeX** [comment]
> align* 環境を入れるのは難しそうですね。

そう言われると挑戦したくなってしまいました😅

TeX芸人的な展開制御トリック(?)を使うことで，次のようにしてできました！

### `\begin{document} ... \end{document}` の内部を自動的に `\begin{align*} ... \end{align*}` で囲む設定

```tex
% compiler: platex
\documentclass[fleqn,papersize]{jsarticle}
\usepackage{amsmath,amssymb}
\usepackage[dvipdfmx]{graphicx,color}
\pagestyle{empty}

\makeatletter
\let\my@document\document
\def\my@doc{document}

\def\document#1\end#2{%
  \def\my@temp{#2}%
  \ifx\my@temp\my@doc
    \def\my@next{\my@document\begin{align*}#1\end{align*}\end{#2}}%
  \else
    \def\my@memory{\my@document\begin{align*}#1\end{#2}}%
    \let\my@next\my@search
  \fi
  \my@next
}
\def\my@search#1\end#2{%
  \def\my@temp{#2}%
  \ifx\my@temp\my@doc
    \expandafter\def\expandafter\my@next\expandafter{\my@memory#1\end{align*}\end{document}}%
  \else
    \expandafter\def\expandafter\my@memory\expandafter{\my@memory#1\end{#2}}%
    \let\my@next\my@search
  \fi
  \my@next
}
\makeatother

%%%% 内部に \begin ... \end が入れ子に存在する場合をテスト
\begin{document}
&\left\{
\begin{array}{l}
\sigma_0=\begin{pmatrix}
 1 && 0 \\
 0 && 1 \\
\end{pmatrix}\\[10pt]
\sigma_1=\begin{pmatrix}
 0 && 1 \\
 1 && 0 \\
\end{pmatrix}\\[10pt]
\sigma_2=\begin{pmatrix}
 0 && -i \\
 i && 0 \\
\end{pmatrix}\\[10pt]
\sigma_3=\begin{pmatrix}
 1 && 0 \\
 0 && -1 \\
\end{pmatrix}
\end{array}
\right.\\[5pt]
\Longrightarrow &
\left\{
\begin{array}{l}
\sigma_1^2=\sigma_2^2=\sigma_3^2=\sigma_0\\[3pt]
\sigma_1\sigma_2=i\sigma_3\\[3pt]
\sigma_2\sigma_3=i\sigma_1\\[3pt]
\sigma_3\sigma_1=i\sigma_2
\end{array}
\right.
\end{document}
```

**Comment by aminophen** [comment]
> > align* 環境を入れるのは難しそうですね。
> 
> そう言われると挑戦したくなってしまいました😅

藝人魂ですね😁 凄い…

このマクロを使うと align* だけでなく enumerate とか itemize とか displaymath とか \[ ... \]  とかにも使えて、bxenclose より汎用的ですね。

**Comment by doraTeX** [comment]
align* 以外の環境にも使えるように改良してみました。
`\encloseDocument{align*}` の部分を変えれば囲む環境を指定できます。

```tex
% compiler: platex
\documentclass[fleqn,papersize]{jsarticle}
\usepackage{amsmath,amssymb}
\usepackage[dvipdfmx]{graphicx,color}
\pagestyle{empty}

\makeatletter
\let\my@document\document
\def\my@doc{document}

\def\encloseDocument#1{%
  \def\document##1\end##2{%
    \def\my@temp{##2}%
    \ifx\my@temp\my@doc
      \def\my@next{\my@document\begin{#1}##1\end{#1}\end{##2}}%
    \else
      \def\my@memory{\my@document\begin{#1}##1\end{##2}}%
      \let\my@next\my@search
    \fi
    \my@next
  }%
  \def\my@search##1\end##2{%
    \def\my@temp{##2}%
    \ifx\my@temp\my@doc
      \expandafter\def\expandafter\my@next\expandafter{\my@memory##1\end{#1}\end{document}}%
    \else
      \expandafter\def\expandafter\my@memory\expandafter{\my@memory##1\end{##2}}%
      \let\my@next\my@search
    \fi
    \my@next
  }%
}
\makeatother

\encloseDocument{align*} % \begin{document} ... \end{document} の中身を \begin{align*} ... \end{align*} で囲む

\begin{document} % 内部に \begin ... \end が入れ子で存在する場合をテスト
&\left\{
\begin{array}{l}
\sigma_0=\begin{pmatrix}
 1 && 0 \\
 0 && 1 \\
\end{pmatrix}\\[10pt]
\sigma_1=\begin{pmatrix}
 0 && 1 \\
 1 && 0 \\
\end{pmatrix}\\[10pt]
\sigma_2=\begin{pmatrix}
 0 && -i \\
 i && 0 \\
\end{pmatrix}\\[10pt]
\sigma_3=\begin{pmatrix}
 1 && 0 \\
 0 && -1 \\
\end{pmatrix}
\end{array}
\right.\\[5pt]
\Longrightarrow &
\left\{
\begin{array}{l}
\sigma_1^2=\sigma_2^2=\sigma_3^2=\sigma_0\\[3pt]
\sigma_1\sigma_2=i\sigma_3\\[3pt]
\sigma_2\sigma_3=i\sigma_1\\[3pt]
\sigma_3\sigma_1=i\sigma_2
\end{array}
\right.
\end{document}
```

**Comment by doraTeX** [comment]
もっと短くできました。そろそろFAQに載せられるかも!?

```tex
% compiler: platex
\documentclass[fleqn,papersize]{jsarticle}
\usepackage{amsmath,amssymb}
\usepackage[dvipdfmx]{graphicx,color}
\pagestyle{empty}

\makeatletter
\let\my@document\document

\def\encloseDocument#1{%
  \def\my@doc{document}%
  \def\my@memory{\my@document\begin{#1}}%
  \def\my@search##1\end##2{%
    \def\my@temp{##2}%
    \ifx\my@temp\my@doc
      \expandafter\def\expandafter\my@next\expandafter{\my@memory##1\end{#1}\end{document}}%
    \else
      \expandafter\def\expandafter\my@memory\expandafter{\my@memory##1\end{##2}}%
      \let\my@next\my@search
    \fi
    \my@next
  }%
  \let\document\my@search
}
\makeatother

% \begin{document} ... \end{document} の中身を \begin{align*} ... \end{align*} で囲む設定にする
\encloseDocument{align*}

% 内部に \begin ... \end が入れ子で存在する場合をテスト
\begin{document}
&\left\{
\begin{array}{l}
\sigma_0=\begin{pmatrix}
 1 && 0 \\
 0 && 1 \\
\end{pmatrix}\\[10pt]
\sigma_1=\begin{pmatrix}
 0 && 1 \\
 1 && 0 \\
\end{pmatrix}\\[10pt]
\sigma_2=\begin{pmatrix}
 0 && -i \\
 i && 0 \\
\end{pmatrix}\\[10pt]
\sigma_3=\begin{pmatrix}
 1 && 0 \\
 0 && -1 \\
\end{pmatrix}
\end{array}
\right.\\[5pt]
\Longrightarrow &
\left\{
\begin{array}{l}
\sigma_1^2=\sigma_2^2=\sigma_3^2=\sigma_0\\[3pt]
\sigma_1\sigma_2=i\sigma_3\\[3pt]
\sigma_2\sigma_3=i\sigma_1\\[3pt]
\sigma_3\sigma_1=i\sigma_2
\end{array}
\right.
\end{document}
```

**Comment by abenori** [comment]
\encloseDocument{verbatim} といういじわるをしてみたくなりました（笑）

**Comment by doraTeX** [comment]
> \encloseDocument{verbatim} といういじわる

うわっ，それはご勘弁を😅

**Comment by aminophen** [comment]
TeX2img (Mac) 1.9.8 のコンパイル中断機能の不安定な挙動について調べていて、2点まずい挙動があったので報告します。

- プログラムのパスが間違っていた場合に「中断」から「画像生成」に復帰しない。（/Library/TeX/texbin/pplatex とかだとエラーダイアログが出た後、TeX2img を再起動しないかぎり次の画像生成ができません）
- LaTeX コンパイルエラーの場合にログが最後まで表示されない。（エラーダイアログが出た後、どこでコンパイルエラーが起きたかわからなくなっています）

なにか分かることがあればお願いします。

**Comment by doraTeX** [comment]
> * プログラムのパスが間違っていた場合に「中断」から「画像生成」に復帰しない。（/Library/TeX/texbin/pplatex とかだとエラーダイアログが出た後、TeX2img を再起動しないかぎり次の画像生成ができません）

こちらの方はすぐに対処できました。同様のケースとして，出力ファイル名の拡張子が不正な場合にも同じ現象が生じていました。こちらも修正しておきました。

> * LaTeX コンパイルエラーの場合にログが最後まで表示されない。（エラーダイアログが出た後、どこでコンパイルエラーが起きたかわからなくなっています）

こちらについては，発動する条件が不定で，再現性が乏しい感じです。エラーを含む同一のソースに対して何度もコンパイルを行った場合，毎回「どこまでログが表示されるか」が変化します。
コンパイルの間にある程度時間をおくと，ログが最後まで出力される確率が高まるようです。

これは，マルチスレッド化に伴い，コンパイルスレッド側からメインスレッド側へ「エラーダイアログ表示」と「ログ表示」の２つの指示が同時競合的に寄せられることの副作用ではないかと思われますが，よく分かりません。マルチスレッドは難しいです……。

**Comment by doraTeX** [comment]
よく調べてみると，これはコンパイルの成功・失敗とは無関係で，コンパイル成功時であっても，出力ログをよく見てみると，LaTeX コンパイラのログが途中で途切れた状態で gs の方に移っていることがあるようです。うーむ，よく分かりません……。

**Comment by doraTeX** [comment]
何とかこの問題も解決できたようです。

ここまでの改良点をまとめた [Ver. 1.9.9 beta 1](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.9b1.zip) をビルドしましたので，よろしければお試しください。

## Ver. 1.9.8 → Ver. 1.9.9 beta 1 での改良点

* Unicode 正規化機能 (#29)
* 「\makeatletter 有効」チェックボックス＋ポップアップメッセージ (#30)
* パス設定不良時や拡張子不良時にコンパイルが二度とできなくなってしまう問題を解決 (#16)
* ログが最後まで吐き出されないことがあった問題を解決 (#16)

**Comment by aminophen** [comment]
> 何とかこの問題も解決できたようです。

ありがとうございます。月曜になりそうですが、試してみます。

 ＃遅くなりましたが、ようやくブログの記事を全体的に改訂し終えました。

**Comment by doraTeX** [comment]
> ＃遅くなりましたが、ようやくブログの記事を全体的に改訂し終えました。

お疲れ様です。いつもありがとうございます！

**Comment by doraTeX** [comment]
#29 で一旦は断念していた NFKC_Casefold による Unicode 正規化のサポートを加えた，[Ver. 1.9.9 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.9b2.zip) を作りました。こちらをお試しください。

## Ver. 1.9.8 → Ver. 1.9.9 beta 2 での改良点

* NFC / Modified NFC / NFD / Modified NFKD / NFKC / NFKD / NFKC_Casefold による Unicode 正規化機能 (#29)
* 「\makeatletter 有効」チェックボックス＋ポップアップメッセージ (#30)
* パス設定不良時や拡張子不良時にコンパイルが二度とできなくなってしまう問題を解決 (#16)
* ログが最後まで吐き出されないことがあった問題を解決 (#16)

**Comment by aminophen** [comment]
Mac 版 Ver. 1.9.9 beta 2 を試してました。#16 の2つの問題点と #30 は解決していました。
