### ISSUE TITLE
タブ表示の幅がずれる

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#17]
[14pt以外の場合に不可視文字表示におけるタブ表示が幅がおかしい。](https://twitter.com/aminophen/status/616492742101721088)

![](https://pbs.twimg.com/media/CI444TCUMAAIPgl.png)

![](https://pbs.twimg.com/media/CI444T9UwAAkF22.png)

**Comment by doraTeX** [comment]
[705b10b](https://github.com/doraTeX/TeX2img/commit/705b10beb62438f3ff353d5c62cf936f20be59b1) で解決。

**Comment by doraTeX** [comment]
調べてみたところ，TeXShopでも，ソースウィンドウの右クリック→フォント→フォントパネルを表示 からフォントパネルを出して，そこで文字サイズを変更すると同じ問題が生じますね。
TeXShopは，環境設定パネルからフォント変更した場合にだけ特別な対策を講じていますが，それ以外の方法によるフォント変更については対処できていないようです。

**Comment by aminophen** [comment]
早速の対応ありがとうございます。

> TeXShopでも，ソースウィンドウの右クリック→フォント→フォントパネルを表示 から
> フォントパネルを出して，そこで文字サイズを変更すると同じ問題が生じますね。

ほんとですね。その方法は知りませんでした…

ちなみに、「半角空白の可視化」が TeX2img で強制されてしまうことがフォントの選択肢を狭めている気がしているのですが（EAW の問題のため）、合成フォント以外の対処法はないでしょうか？
（私は普段 TeXShop では半角空白だけ OFF にしているので、Osaka-等幅以外の“等幅”でも問題ないことになっています。）

**Comment by doraTeX** [comment]
そうですね，ではそれは #8 に統合し，GUIによる表示の制御をもっと自在にできるようにするという方向性がよさそうですね。

**Comment by doraTeX** [comment]
> ちなみに、「半角空白の可視化」が TeX2img で強制されてしまうことがフォントの選択肢を狭めている気がしているのですが（EAW の問題のため）、合成フォント以外の対処法はないでしょうか？
> （私は普段 TeXShop では半角空白だけ OFF にしているので、Osaka-等幅以外の“等幅”でも問題ないことになっています。）

現状でも半角スペースのみ不可視文字表示を抑えることは可能です。
![2015-07-03 13 07 06](https://cloud.githubusercontent.com/assets/6186180/8492432/7cf35454-2184-11e5-96ff-0cf891aab5cb.png)

**Comment by aminophen** [comment]
> 現状でも半角スペースのみ不可視文字表示を抑えることは可能です。

そうでした、表示タブでした… すみません。ありがとうございます。
（TeXShop や TeX2img (Win) が環境設定にあるのに引きずられて見落としていました…）

**Comment by aminophen** [comment]
Ver.1.9.4 でタブの幅の問題が修正されたことを確認しました。ありがとうございます。
