### ISSUE TITLE
gs9.14 以下の epswrite デバイスでクロップに失敗する例がある

### ISSUE THREAD

**Issue by aminophen** [doraTeX/TeX2img#18]
結城先生からいただいたバグ報告です。参考: https://twitter.com/hyuki/status/622234080587878401
~~~~ latex
\documentclass[dvipdfmx]{jsarticle}
\usepackage{tikz}
\pagestyle{empty}
\begin{document}
\begin{tikzpicture}

\draw[blue] (0,0) -- (1,1); % (1. blue)
% \draw[black] (0,0) -- (1,1); % (2. black)

\end{tikzpicture}
\end{document}
~~~~
を gs9.14 で PNG 化すると、クロップに失敗します。しかし、blue が失敗する一方で black, red, gray は成功するという報告があります。

**Comment by aminophen** [comment]
この問題は gs の epswrite デバイスに由来するもので、実際に gs9.15 以上の eps2write デバイスでは再現しません。色依存なのがよくわかりませんが、そういう仕様としかいいようがありません。

よって、根本的な解決策は

- gs9.15 以上にアップしてもらう

なのですが、これはあまり優しくありません。もう一つ Mac 版の PNG 出力に限り

- 速度優先モードにしてもらう（gs を通らないスキームだから）

がありますが、Mac 版のアウトライン化 PDF や Windows 版で同じ問題が残ってしまいます。したがって、安全策は「gs9.14 以下の epswrite デバイスのクロップ機能を信用しない」ということで

- gs9.14 以下ならば、epswrite を通す前に**必ず** pdfcrop 類似処理を通す

というのが考えられますが、いかがでしょうか。

**Comment by abenori** [comment]
「gs9.14 以下ならば、epswrite を通す前に必ず pdfcrop 類似処理を通す」でよいですかね．ちなみにgs 9.14のeps2writeは大丈夫？

**Comment by aminophen** [comment]
> ちなみにgs 9.14のeps2writeは大丈夫？

盲点でした… Mac 版は毎回 gs のバージョンチェックで「9.14 以下なら epswrite、9.15 以上なら eps2write」を強制するので gs の eps2write は原理的に使われないのですが、Win 版は 9.14 では両方選べるのでしたね。というわけで、いつもテスト用として使っている [PortableApps.com](http://sourceforge.net/projects/portableapps/files/Ghostscript%20Portable/) の Ghostscript 9.14 を入手して Windows 版 gs9.14 をチェックしました。結果は

- epswrite は失敗
- eps2write は成功

なので、先ほど提案した「epswrite を通すならば事前に pdfcrop 類似処理、eps2write を通すならば従来どおり」で問題ないです。

**Comment by abenori** [comment]
ありがとうございます．別バージョンを入れるのが面倒だったので，頼ってしまいました．2があるかどうかですね．

**Comment by doraTeX** [comment]
> 安全策は「gs9.14 以下の epswrite デバイスのクロップ機能を信用しない」ということで
>
> * gs9.14 以下ならば、epswrite を通す前に必ず pdfcrop 類似処理を通す
>
> というのが考えられますが、いかがでしょうか。

試してみました。ですが，なぜかうまく行きません……。

#### pdfcrop類似処理
まず，当該PDFをpdfcrop類似処理にかけたものが[こちら](https://dl.dropboxusercontent.com/u/5807100/test-pdfcrop.pdf)です。

#### pdfinfo-extractbb によるBB情報

```
 Page    1 MediaBox:     0.00     0.00    29.00    29.00   [dvipdfmx BB]
 Page    1 CropBox:      0.00     0.00    29.00    29.00   [Implicit]
 Page    1 BleedBox:     0.00     0.00    29.00    29.00   [Implicit]
 Page    1 TrimBox:      0.00     0.00    29.00    29.00   [Implicit]
 Page    1 ArtBox:       0.00     0.00    29.00    29.00   [Implicit]
```

#### epswrite で処理

それを美文書付属の gs 9.07 の epswrite で処理しました。

```sh
 $ gs -dNOPAUSE -dBATCH -r20016 -sOutputFile=test-pdfcrop.eps -sDEVICE=epswrite -dNOCACHE -dFirstPage=1 -dLastPage=1 test-pdfcrop.pdf  2>&1
```

#### 生成EPSのBB情報

その結果得られたEPSが[こちら] (https://dl.dropboxusercontent.com/u/5807100/test-pdfcrop.eps)です。

```sh
 $ head test-pdfcrop.eps
 %!PS-Adobe-3.0 EPSF-3.0
 %%BoundingBox: 0 0 612 792
 %%HiResBoundingBox: 0.000000 0.000000 612.000000 792.000000
```

どうも，gs<9.15 の epswrite デバイスは，このPDFのBB把握を苦手としているようですね……。

#### 考えられる対策

対策としては，この結果得られたEPSのBB情報を，pdfcrop類似処理の結果得られたPDFのBB情報で上書きしてしまうという手が考えられます。いかがいたしましょう？弊害は考えられないでしょうか……。

**Comment by doraTeX** [comment]
> この結果得られたEPSのBB情報を，pdfcrop類似処理の結果得られたPDFのBB情報で上書きしてしまうという手が考えられます。

pdfcrop類似処理の中身を考えてみると，これは冗長ですね。いちいち pdfTeX で処理する必要性がありません。

1. 普通に TeXで生成したPDFを epswrite で処理する。
1. 得られたEPSのBB情報を，元PDFを gs -sDEVICE=bbox の出力内容で上書きする

という手順でよさそうです。

**Comment by aminophen** [comment]
> > 安全策は「gs9.14 以下の epswrite デバイスのクロップ機能を信用しない」ということで
> > 
> > - gs9.14 以下ならば、epswrite を通す前に必ず pdfcrop 類似処理を通す
> > 
> > というのが考えられますが、いかがでしょうか。
> 
> 試してみました。ですが，なぜかうまく行きません……。

すみません、どうやら私がテストしたとき「pdfcrop 類似→epswrite」とするつもりが「pdfcrop 類似→eps2write」に通っていたようです。なので doraTeX さんが正しいです。

> 1. 普通にTeXで生成したPDFを gs (<9.15) の epswrite で処理する。
> 2. 得られたEPSのBB情報を，「元PDFに対する gs -sDEVICE=bbox の出力内容」で上書きする

これが無駄もなく良さそうです。全くその発想がありませんでした。

**Comment by doraTeX** [comment]
epswrite デバイス利用時には

> 1. 普通にTeXで生成したPDFを gs (<9.15) の epswrite で処理する。
> 1. 得られたEPSのBB情報を，「元PDFに対する gs -sDEVICE=bbox の出力内容」で上書きする

という手順を必ず行うように修正した，Ver. 1.9.4 をリリースしておきました。

**Comment by abenori** [comment]
速いですね．こちらも時間がとれたら対処します．

**Comment by aminophen** [comment]
遅くなりましたが、Mac 版の動作確認しました。PDF ファイルの読み込み機能 #19 と合わせて、ともに期待通りでした（[マスクメロン](http://www.muskmelon.jp/?page_id=75)の Ghostscript.app 9.05 と MacPorts の gs9.16 で確認）。

**Comment by abenori** [comment]
ちょっと書いてみました．
http://1drv.ms/1uwNVCs
Ghostscriptを入れるのが面倒で試せていません……試してもらえるとありがたいです．

「TeXソースファイルを読み込む」の部分もPDFを受けつけるようにしています．が，「TeX」2imgじゃないよなぁという気もするので，現段階では「裏技」とさせてください．

**Comment by aminophen** [comment]
gs9.10 の epswrite、gs9.14 の epswrite/eps2write、gs9.16 の eps2write ですべて正常でした。「epswrite ならば bbox を上書き」で大丈夫そうです。

> 現段階では「裏技」とさせてください．

了解しました。あくまで裏ワザですね（まだ tex2imgc のほうが PDF を受け付けてくれませんし）。GUI のほうは「すべてのファイル」にすると PDF をこっそり受け付けてくれました。ありがとうございます。

**Comment by abenori** [comment]
ありがとうございます．tex2imgcの方は後でと思ってサボっていました．
何故か作業フォルダがカレントフォルダになっていたのを直して更新しました．

**Comment by doraTeX** [comment]
結城浩さんが先月の[ブログ](http://snap.textfile.org/20150718112823/)や[メルマガ](http://ch.nicovideo.jp/hyuki/blomaga/ar835179)で TeX2img を紹介してくださっていますね。
ありがたい限りです。
