### ISSUE TITLE
外部ファイル入力で PDF も受け入れられないか？

### ISSUE THREAD

**Issue by aminophen** [doraTeX/TeX2img#19]
おもしろくかつ有用そうな機能拡張を思いついたので、提案します。

「外部ソースファイル入力」は現状で .tex しか受け付けない仕様ですが、ここに .pdf も受け付けるのはどうかという思いつきです。最も有用そうな実用例としては「既存の PDF ファイルをアウトライン化する」という用途です。現在、TeX2img は

- TeX ソースをエディタに入力（GUI 版）
- 外部ソースファイルを入力（GUI/CUI 版）

の2つの処理が可能です（一つ目のほうには「インポート機能」すなわち TeX ソースインポート・画像ファイルからのソース復元も含むつもり）。この二つ目の機能を拡張すれば、TeX2img の用途が大幅に広がる気がします。TeXtoPDF と PDFtoIMG は独立なはずですので、実装としては「.tex なら TeXtoPDF してから画像変換スキームへ、.pdf なら直接画像変換スキームへ」でいけそうですが、いかがでしょうか。

 # 今回の #18 で「pdfcrop してから…」の事前チェック中に、「今クロップした .pdf をそのまま GUI でも epswrite に通せたらなあ」と思ったのがきっかけです。

**Comment by doraTeX** [comment]
PDFインプット機能を搭載し，Ver. 1.9.4 としてリリースしておきました。
