### ISSUE TITLE
コンパイル後にクリップボードにコピーする

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#20]
Windows版にならってMac版にもコンパイル後にクリップボードにコピーする機能を加える。

* 複数ファイル生成時は全ファイル一括コピーで。（PowerPoint や KeyNote は複数ファイルペーストに対応している。）
* CUI版にも加えよう。オプションは `--copy` でよいか？

**Comment by doraTeX** [comment]
[追加してみました](https://github.com/doraTeX/TeX2img/commit/24c964b0619af719a0ec50eedc491035775655ec)。CUI版には --copy として追加。

**Comment by abenori** [comment]
こちらもCUIにもつけてみました．まぁなくてもよいかなぁという気もしますが．オプションはつけていないです．--copyだとよくわからないかなぁ，なんて悩み中……．
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

**Comment by doraTeX** [comment]
オプション名は改善の余地があり得ますね。
ただ `--copy-to-clipboard` とかだと長すぎますし……

**Comment by abenori** [comment]
--to-clipboardってどうだろう？と思ってみました．

**Comment by doraTeX** [comment]
確かにそれは一案ですね。
ただ，動詞である copy は入っていた方が，やりたいことが直接的で直観的な気もします。

**Comment by aminophen** [comment]
Windows 版が GUI で「[送る](https://twitter.com/aminophen/status/625278206384320512)」なので、copy か send かも悩みます。以前悩んだ --delete-display-size のような長い例は既にあるので、動詞付きで --copy-to-clipboard とか --send-to-clipboard でも気にしなくて良いかと。（長さを考えるといっそ --clipboard かなあと思いましたが、分かりにくいですし今後ナントカ clipboard というオプションがないとはいえない…？）

**Comment by doraTeX** [comment]
> 以前悩んだ --delete-display-size のような長い例は既にあるので、動詞付きで --copy-to-clipboard とか --send-to-clipboard でも気にしなくて良いかと。

確かに。では --copy-to-clipboard にしてみます。Windowsでcopyかsendかは悩ましいですね。

**Comment by abenori** [comment]
copyの方がよいでしょうね．GUIも変えておきます．
