### ISSUE TITLE
出力に白紙ページが含まれる場合に挙動がおかしい

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#21]
出力に白紙ページが含まれる場合，モードによって色々とおかしな挙動を示す。

特に，「速度優先モード かつ ビットマップ出力」の場合に，出力に白紙ページが含まれると，コンパイル後は二度と Command+T によるコンパイルが効かなくなってしまう。

**Comment by doraTeX** [comment]
出力に白紙ページが含まれる場合，どの画像形式への出力の場合でも，元の用紙サイズを保持した白紙画像を出力する（余白付与はしない）ように修正。

**Comment by aminophen** [comment]
うちの [bcpdfcrop](https://github.com/aminophen/bcpdfcrop) でもやっと応急処置したところでした。ありがとうございます。

**Comment by doraTeX** [comment]
bcpdfcrop の \procinclude を参考にさせてもらいました😊

**Comment by aminophen** [comment]
bcpdfcrop では 0 0 0 0 な場合しかハンドルしていませんが、オリジナルの pdfcrop.pl は x 座標と y 座標をそれぞれ比較して、逆転がある場合を含めて対処していました。gs が返す座標が逆転したり 0 0 0 0 でない場合があり得るのか解らなかったので、手抜きです😅

**Comment by doraTeX** [comment]
なるほど，本当はそのような場合への対処も必要ですね……。
ただ，TeXによる組版結果のPDFの gs -sDEVICE=bbox 結果がそんなものになる可能性はたぶんないだろうから，TeX2imgとしては現状の例外処理で実用上十分ではないかと思います。

**Comment by aminophen** [comment]
> TeXによる組版結果のPDFの gs -sDEVICE=bbox 結果がそんなものになる可能性はたぶんないだろうから

私も同じことを考えていました。いまの例外処理で十分でしょう。

**Comment by aminophen** [comment]
EPS を経由する画像化の場合の挙動は問題ないでしょうか。eps(2)write を通る処理では白紙ページの扱いが気になりました。特に、epswrite のときに #18 対策で bbox を上書きしていた部分を確認したいと思います。

**Comment by doraTeX** [comment]
> 特に、epswrite のときに #18 対策で bbox を上書きしていた部分を確認したいと思います。

図星でした。その場合に問題が生じていましたので解決しておきました。
現在の最新版を [Ver. 1.9.6 beta 1](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b1.zip) として置いておきます。よろしければテストをお願いします。

ちなみに，変換経路が複雑化してきて，新機能を加えるたびにどのようなパターンをテストすべきかを見落としやすくなってきましたので，備忘録としてテストすべき項目を列挙しておきます。

## gsを通さない経路

1. 速度優先モードでのビットマップ生成 (PDF →[Quartz API でビットマップ化＋余白付与]→ JPEG/PNG/GIF/TIFF/BMP)
1. テキスト情報を残したPDF生成 (PDF →[pdfcrop類似処理でクロップ＋余白付与]→ PDF)
1. テキスト情報を残したSVG生成 (PDF →[pdfcrop類似処理でクロップ＋余白付与]→ PDF →[mudraw]→ SVG)

## gsを通す経路
1. 画質優先モードでのビットマップ生成 (PDF →[gsでアウトライン化＋クロップ]→ EPS →[epstopdf(gs)]→ PDF →[Quartz API でビットマップ化＋余白付与]→ JPEG/PNG/GIF/TIFF/BMP)
1. アウトライン化PDF生成 (PDF →[gsでアウトライン化＋クロップ] → EPS →[epstopdf(gs)]→ PDF →[pdfcrop類似処理で余白付与]→ PDF)
1. アウトライン化EPS生成 (PDF →[gsでアウトライン化＋クロップ] → EPS →[BB情報を編集して余白付与] → EPS)

gsを通す経路については，そのそれぞれについて，

1. gs<9.15 の epswrite デバイス，画質優先モード(-r20016 固定)
1. gs<9.15 の epswrite デバイス，速度優先モード(-rの値は解像度レベル設定に従う)
1. gs>=9.15 の eps2write デバイス，画質優先モード(-r20016 固定)
1. gs>=9.15 の eps2write デバイス，速度優先モード(-rの値は解像度レベル設定に従う)

の4通りのテストが必要です。

**Comment by aminophen** [comment]
これからテストしますが、上記の「gs を通さない経路」の 1. 速度優先モードでのビットマップ生成は

PDF →[pdfcrop類似処理でクロップ＋余白付与]→ PDF →[OS XのQuartz API]→ JPG/PNG/BMP/GIF/TIFF

だと思っていましたが、そうではなかったのでしたっけ…

**Comment by doraTeX** [comment]
どちらでもなくて，

PDF →[pdfcrop類似処理でクロップ]→ PDF →[Quartz API でビットマップ化＋余白付与]→ JPEG/PNG/GIF/TIFF/BMP

でした。上の書き込みも訂正しておきます。

**Comment by aminophen** [comment]
> どちらでもなくて，

もはや把握できなくなってしまいました…😅 Windows 版と合わせて頭の中が混乱しそうですが、私の記事も今度直します…

**Comment by aminophen** [comment]
gs9.16 と gs9.05 で上の全ての場合をテストしました（つもりです）。真っ白な EPS をプレビューしようとすると、gs9.16 の eps2write で吐いた場合のみ「Preview.app の前処理 epstopdf (?) が Warning を吐いてプレビューが開かない」という現象が起きました。ほかは問題なさそうです。

![gs916-epstopdf-error](https://cloud.githubusercontent.com/assets/9957466/9001908/902707e4-3798-11e5-9544-5f2569207da1.png)

**Comment by doraTeX** [comment]
> 「Preview.app の前処理 epstopdf (?) が Warning を吐いてプレビューが開かない」という現象が起きました。

これはコマンドラインから呼び出しても同じですので，OS X の仕様ということで仕方なさそうです。

```sh
$ pstopdf hoge.eps
%%[ Warning: Empty job. No PDF file produced. ] %%
```

**Comment by aminophen** [comment]
> OS X の仕様ということで仕方なさそうです。

ありがとうございます。ではこれで全て解決ですね。

**Comment by abenori** [comment]
あんまりよくわかっていないのですが，空白ページにはpdfcropを通さないと言うことでしょうか？

**Comment by doraTeX** [comment]
> あんまりよくわかっていないのですが，空白ページにはpdfcropを通さないと言うことでしょうか？

はい，それで大丈夫なはずです。
とはいっても，PDFのページをバラで切り出すのも一苦労なので，[bcpdfcrop.bat](https://github.com/aminophen/bcpdfcrop) にならって，

```tex
\pdfoutput=1\pdfhorigin=0bp\relax\pdfvorigin=0bp\relax\setbox0=\hbox{\pdfximage page ページ番号 mediabox{ファイル名}\pdfrefximage\pdflastximage}\pdfpagewidth=\wd0\relax\pdfpageheight=\dimexpr\ht0+\dp0\relax\shipout\hbox{\raise\dp0\box0\relax}\end
```

のような pdfTeX ソースをコンパイルして切り出すようにしています。

**Comment by aminophen** [comment]
Windows 版の場合、空白ページが問題になるのは

- テキスト保持 PDF と SVG 出力で pdfcrop 類似処理するとき
- EPS を経由するスキーム（＝上記以外全て）で gs9.14 以下の epswrite デバイス時に bbox 上書きする工程

だと思います（eps2write で空白ページを処理すると元の bbox が維持されるっぽいので大丈夫）。この2パターンに対して bbox = 0 0 0 0 への例外処理を加えれば良さそうです。

**Comment by abenori** [comment]
ええと，「白紙ページが存在したらそのページはそのまま出力される」と言うことですよね．なんだかあまりこれを意図して使われるところが想像できないのですが……
エラーにした方がユーザの意図にあいませんか？

**Comment by aminophen** [comment]
> エラーにした方がユーザの意図にあいませんか？

白紙ページを見つけたら単にそのページをスキップして、空白でないページだけ出力するということでしょうか。うーん、どちらがよいでしょう？ 私の bcpdfcrop は複数ページ処理を単一ファイル出力と分割ファイル出力の両方に対応すべく、枚数を維持する方を優先しました。真っ白なページは要らないという考えも一理ありますね。

 # あと、bbox が 0 0 0 0 になる他の例としては「CropBox の内側は確かに真っ白だが、その外側でかつ MediaBox に入っている部分にはなんか物体があるとき」です。gs の bbox デバイスは CropBox の中しか検知しない一方、pdfTeX に mediabox を使わせるのでインクルードすればその外側が描画されて出てくるという現象が起きます。TeX2img で意図する人はいないでしょうが…

**Comment by abenori** [comment]
> 白紙ページを見つけたら単にそのページをスキップして、空白でないページだけ出力するということでしょうか

そうではなく，「白紙ページがあったらユーザにその旨を伝える」というのが一番の意図です．（既にそうなっていたらすみません．）（基本的にはエラー扱いして何も出さなくてよいかなとも思っていますが．）意図して空白ページを生成するよりも，間違って白紙ページを作ってしまう方が遙かに多いだろうというわけです．

pdfcropの場合は白紙ページが入力に意図して含まれることも多いと思います．そもそもTeX2imgとは目的が異なるものですし……

**Comment by aminophen** [comment]
> 基本的にはエラー扱いして何も出さなくてよいかなとも思っていますが

それだと golden_lucky さんの[牛耕式](https://www.overleaf.com/read/rypkqvwxxrrn)みたいなのが通らなくなってしまうなあと思います。意図していない空白ページが末尾にあって、でも対処法がよくわからないみたいなのは往々にしてあるかなと。

**Comment by abenori** [comment]
繰り返しますが，「白紙ページがあったらユーザにその旨を伝える」のがどうかと言うことです．

**Comment by aminophen** [comment]
> 「白紙ページがあったらユーザにその旨を伝える」

そこまで必要性を感じていません。この場合は出力を見れば明らかなので敢えて言わなくても、と思います。

**Comment by abenori** [comment]
うーん，「勝手に空白ページはそのままページをはき出す」という仕様が「最も自然である」とはやはりまだ思えていません．

**Comment by abenori** [comment]
うーん，「勝手に空白ページはそのままページをはき出す」という仕様が「最も自然である」とはやはりまだ思えていません．

# ついでに上の例が「対処法がよくわからない」のかも理解していません．がこれはまた別の話．

**Comment by doraTeX** [comment]
私はこの件に関しては特に強い意見は持っておりませんので，いずれの形であれ，皆様のご判断に沿った仕様で実装いたします。
（Mac版では，従来「速度優先モードかつビットマップ出力」かつ「出力に白紙ページが含まれる」という場合に，コンパイル後に操作不能になる致命的バグがありましたので，それを解決することが最優先目標でした。）

**Comment by abenori** [comment]
試してみましたがなんかエラーが出たので，対処はこちらも必要そうです．

ちょっと考えてみましたが……．書き散らかします．

* そもそも白紙ページは予定外（捨てる運命）だとすると出力は「どーでもいい」という気もしてきました．（なので，特に何もしないというのは一つの妥協点としてありかもしれません．）
* そこをあえて出力したい人がいたとして，彼（女）の想定はどうなるかというと
  * 全体に10の余白をつけている場合，出力はどれが自然？
    * 縦横20
    * 紙サイズ
    * 紙サイズ+縦横20
  * 他とのcompatibilityを考えると最初ですが……余白無しだと縦横0になってまずそうです．（がとりあえず無視する．）
* 逆に白紙ページから紙サイズが出力されるならば，他はクロップしないと整合的．
* 「サイズを文書サイズにあわせる」的なオプションを入れるとこのオプションの有無で切り替えられるだろうか．（http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeX2img%20FAQ#s84b19a5 もこれで解決できるかなと思ったけど，これは横方向だけだった……．）
* 縦横0の画像を生成することになって，それを画像フォーマットが許容していないのならば，エラーとして出力しないのはどうだろう．

**Comment by aminophen** [comment]
私は予期せぬエラーさえ出なければいいという程度しか考えておらず、doraTeX さんの今の「余白無視でサイズ保持」が回避策として有効だった時点で思考停止していました。自然な挙動を考えていただきありがとうございます。

> 全体に10の余白をつけている場合，出力はどれが自然？

これを見て最初は「縦横20」だと思ったのですが、3つの選択肢どれだとしても「その白紙画像が必要だ」という人はいない気がしてきました。フォーマット的に縦横0が認められていないかどうかと、使用するツールやビューアが対応しているかはまた別問題かもしれないですし…。だとすると、難しく考えずに白紙ページはスキップするのが良いでしょうか。具体的には

- まず何はともあれ gs の bbox を実行し、返す値が 0 0 0 0 だったらそのページをスキップ
- そうでないならば、pdfcrop 類似処理なり eps(2)write なりを実行（epswrite なら値の上書きも）して画像変換を継続
- 出力するファイル名の番号は、元の PDF のページ番号を引き継ぐ（欠番を認める）
- スキップしたことについては何も言わない（ただし、仮に出力する全ページがスキップされてしまったらエラーメッセージ？）

**Comment by abenori** [comment]
> これを見て最初は「縦横20」だと思ったのですが、3つの選択肢どれだとしても「その白紙画像が必要だ」という人はいない気がしてきました。

先のを書いたときはそう思ったのですが，パッケージか何かの紹介をしていて，オプションを色々変えて試してみた，みたいな画像を貼りたいときに，空っぽが現れる可能性はゼロではないかなという気もしてきました．（本当にそんなことあるかは書いていても疑問ですが……．）なので，「縦横20」を採用してみようかなと思いつつあります．ただ，縦横0の画像は怖いので，TeX2imgではエラー扱いすることにしてスキップすればよいように思えています．

> 出力するファイル名の番号は、元の PDF のページ番号を引き継ぐ（欠番を認める）

これはこの方がよいように思えますよね．（そうしようかなと思っていたところでした．）

**Comment by abenori** [comment]
とりあえずスキップするようにだけしてみました．
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

あって困る物ではないと思うのでスキップしたら通知しています．

**Comment by doraTeX** [comment]
ではその方針で実装してみます。
色々な変換経路がありますので，その全てに対応するには多少時間がかかりそうです。

**Comment by doraTeX** [comment]
一応全ての場合に対応できたのではないかと思います。
[Ver. 1.9.6 beta 5](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b5.zip) としてまとめておきましたので，よろしければテストをお願いします。

# テストすべき経路

## gsを通さない経路

1. 速度優先モードでのビットマップ生成 (PDF →[pdfcrop類似処理でクロップ]→ PDF →[Quartz API でビットマップ化＋余白付与]→ JPEG/PNG/GIF/TIFF/BMP)
1. テキスト情報を残したPDF生成 (PDF →[pdfcrop類似処理でクロップ＋余白付与]→ PDF)
1. テキスト情報を残したSVG生成 (PDF →[pdfcrop類似処理でクロップ＋余白付与]→ PDF →[mudraw]→ SVG)

## gsを通す経路
1. 画質優先モードでのビットマップ生成 (PDF →[gsでアウトライン化＋クロップ]→ EPS →[epstopdf(gs)]→ PDF →[Quartz API でビットマップ化＋余白付与]→ JPEG/PNG/GIF/TIFF/BMP)
1. アウトライン化PDF生成 (PDF →[gsでアウトライン化＋クロップ] → EPS →[epstopdf(gs)]→ PDF →[pdfcrop類似処理で余白付与]→ PDF)
1. アウトライン化EPS生成 (PDF →[gsでアウトライン化＋クロップ] → EPS →[BB情報を編集して余白付与] → EPS)

gsを通す経路については，そのそれぞれについて，次の2経路存在する。

1. gs<9.15 の epswrite デバイス，画質優先モード(-r20016 固定)
1. gs<9.15 の epswrite デバイス，速度優先モード(-rの値は解像度レベル設定に従う)
1. gs>=9.15 の eps2write デバイス，画質優先モード(-r20016 固定)
1. gs>=9.15 の eps2write デバイス，速度優先モード(-rの値は解像度レベル設定に従う)

また，ビットマップ画像のうち PNG/GIF/TIFF の場合は

1. 透過
1. 非透過

が選択できる。

# テストすべきソース

1. 通常の文書
1. 白紙ページを含む文書（余白設定：左右余白量の和，上下余白量の和の少なくとも一方がゼロ）
1. 白紙ページを含む文書（余白設定：左右余白量の和，上下余白量の和がともに正）

# 挙動の仕様が次に沿っているか

1. 縦横の少なくとも一方の辺の長さがゼロになってしまう画像は生成しない。
1. そのような画像になってしまうページはスキップし，equation.png, equation-2.png,... といったナンバリングにおいては欠番が生じる。（元のPDFのページ番号に合わせるため）
1. 文書中に1ページでもスキップしてしまうページが生じた場合には，「白紙ページが生じたのでスキップしました」という警告ダイアログを表示する。
1. スキップされたページに対して，プレビュー処理やクリップボードへのコピー処理など，その後の後処理を誤発動しないこと。
1. 一方，白紙ページが存在しても，余白付与の結果空のキャンバスが存在できる場合は，ただの真っ白（or透明）な画像を生成する。その際は警告ダイアログを出さない。

**Comment by aminophen** [comment]
まず Windows 版を試してみました。なるほど、ログに「空白だったため画像生成をスキップしました」が出るのはよいですね。出力ウィンドウに「まず gs の bbox 実行→縦横とも0でない場合だけ先のステップを実行」となっているのが見えて、いちいち手前に別のダイアログが出てくるよりうるさくないので快適です。

![tex2imgwin155-skip-blank](https://cloud.githubusercontent.com/assets/9957466/9020392/fd650922-3843-11e5-97ef-5473ae4df805.png)

doraTeX さんのチェック項目については以下のように解釈し、確認しました。

1. 縦横の少なくとも一方の辺の長さがゼロになってしまう画像は生成しない → OK
2. そのような画像になってしまうページはスキップし、欠番が生じる → OK
3. （別ダイアログではなく）**出力ウィンドウ末尾に**スキップしたページ番号情報が出る（複数のページがスキップされたら何行もメッセージが並ぶけど、わかりやすい） → OK
4. スキップされたページに対して、後処理を誤発動しない → OK
5. 白紙ページが存在しても、余白付与の結果空のキャンバスが存在できる場合はただの真っ白（or透明）な画像を生成する → NG

pdfcrop 類似処理経由の処理・EPS 経由の処理の両方で、「余白付与があって真っ白なキャンバスが縦横ともに0でない場合」にもスキップされてしまいました。「上下左右余白10だと20」というのができないことになるので、あとは上記5.への対応だと思います。

**Comment by doraTeX** [comment]
確かにログウィンドウに表示するとうるさくなくてよいですね。
後でMac版もそう改変しておきます。

**Comment by aminophen** [comment]
Mac 版 beta5 を試しました。ログウィンドウに表示するのはお願いします。

1. 縦横の少なくとも一方の辺の長さがゼロになってしまう画像は生成しない → OK
2. そのような画像になってしまうページはスキップし、欠番が生じる → OK
3. 出力ウィンドウ末尾にスキップしたページ番号情報が出る（複数のページがスキップされたら何行もメッセージが並ぶけど、わかりやすい） → これからですね。
4. スキップされたページに対して、後処理を誤発動しない → OK
5. 白紙ページが存在しても、余白付与の結果空のキャンバスが存在できる場合はただの真っ白（or透明）な画像を生成する → OK?

で気づいたのは

- テキスト保持 PDF で余白0だとメッセージが出ませんでした。
- アウトライン化 PDF で余白を10ずつにすると、PDF は出てくる一方で gs9.10 の epstopdf が凄いエラーを吐いていますが、大丈夫でしょうか。
~~~~
$ export PATH="/opt/local/bin";/usr/bin/perl "/home05/1477147641/Downloads/TeX2imgMac1/TeX2img.app/Contents/Resources/epstopdf" --outfile=temp27376-9DCDC418-EA48-4604-A42F-D7A00DB5E1D5-2.eps.trim.pdf temp27376-9DCDC418-EA48-4604-A42F-D7A00DB5E1D5-2.eps  2>&1
Error: /configurationerror in --setpagedevice--
Additional information: [/PageSize [0 0]]
Operand stack:
   false   --dict:1/1(L)--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1916   1   3   %oparray_pop   1915   1   3   %oparray_pop   --nostringval--   1899   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   1878   1   3   %oparray_pop   --nostringval--   --nostringval--   --dict:1/10(L)--   --nostringval--   14   %dict_continue
Dictionary stack:
   --dict:1178/1684(ro)(G)--   --dict:0/20(G)--   --dict:81/200(L)--
Current allocation mode is local
Last OS error: Invalid argument
GPL Ghostscript 9.10: Unrecoverable error, exit code 1
epstopdf ($Id: epstopdf.pl 36129 2015-01-24 00:30:11Z karl $) 2.23
!!! Error: Writing to gs failed, error code 1

$ /usr/texbin/pdftex -no-shell-escape -interaction=batchmode temp27376-9DCDC418-EA48-4604-A42F-D7A00DB5E1D5-pdfcrop  2>&1
epstopdf ($Id: epstopdf.pl 36129 2015-01-24 00:30:11Z karl $) 2.23
!!! Error: Writing to gs failed, error code 1
~~~~

**Comment by abenori** [comment]
自分で言い出しておいて何ですが，結構面倒ですね．あまり例外処理をしたくないのですが．

ところで，eps->画像の変換では，新しくepsを作りそれに古いepsを取り込ませているようですが，そうしている理由は何かあるのでしょうか？単にもともとのepsにGhostscriptをかますだけでは何か不都合がある？

**Comment by abenori** [comment]
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

上のを単にかますだけに変更したので，何か不具合があるかもしれません．
それと，別件ですがHiResBoundingBoxがあるときはそちらを優先して使うようにしました．

**Comment by doraTeX** [comment]
[Ver. 1.9.6 beta 6](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b6.zip) を作りました。

> ログウィンドウに表示するのはお願いします。

→ 対応しました。

> 3. 出力ウィンドウ末尾にスキップしたページ番号情報が出る（複数のページがスキップされたら何行もメッセージが並ぶけど、わかりやすい） → これからですね。

複数ページがスキップされた場合は，最後にまとめて

```
TeX2img: [警告] 1, 3 ページ目が空白ページであったためスキップしました。
```

のように表示させるようにしました。

> - テキスト保持 PDF で余白0だとメッセージが出ませんでした。

→ 修正できたはずです。

> - アウトライン化 PDF で余白を10ずつにすると、PDF は出てくる一方で gs9.10 の epstopdf が凄いエラーを吐いていますが、大丈夫でしょうか。

→ epstopdf はゼロ幅のEPSを処理するとエラーを吐くようですので，ゼロ幅のページは epstopdf を経由しない別経路を通るように例外対応することで修正しました。

> eps->画像の変換では，新しくepsを作りそれに古いepsを取り込ませているようですが，そうしている理由は何かあるのでしょうか？

どうでしたっけね……。Windows版を作ったのはかなり昔だったので記憶にありません……。（現在のMac版ではその変換法は用いておりません。）
直接Ghostscriptにかけて問題なさそうならそれでよいと思います。

> それと，別件ですがHiResBoundingBoxがあるときはそちらを優先して使うようにしました．

Mac版では，HiResBoundingBox を用いて EPS からビットマップ画像に変換すると，小数点以下の値を持つ BoundingBox から整数値の縦横ピクセル幅を持つビットマップ画像に変換する際に，丸め誤差で BoundingBox の端の方が切り捨てられる現象が見られました。
非HiResBoundingBoxの方は，HiResBoundingBox を内包する整数値のBoundingBoxがとられていますので，変換しても端が欠けることがありません。
非HiResBoundingBoxを使うことで，「余白量がゼロ設定の場合でも厳密にタイトではない画像」が生成されますが，端が切れるよりはましだと思って，非HiResの方を採用しています。

**Comment by abenori** [comment]
> どうでしたっけね……。Windows版を作ったのはかなり昔だったので記憶にありません……。

ありがちですね（笑）とりあえず問題なさそうなので変更してみます．

> Mac版では，HiResBoundingBox を用いて EPS からビットマップ画像に変換すると，小数点以下の値を持つ BoundingBox から整数値の縦横ピクセル幅を持つビットマップ画像に変換する際に，丸め誤差で BoundingBox の端の方が切り捨てられる現象が見られました。

なるほど，とりあえずBoundingBoxを使うように戻しました．（PDFに変換するときは大丈夫ですかね？）

**Comment by aminophen** [comment]
丸一日外出していたので、テストが遅くなりました…すみません。

Mac 版 Beta 1.9.6 beta6 で、「余白をつけたビットマップ画像」が画質優先・速度優先ともに「スキップするのにメッセージを出さない」状態になっていることが分かりました。意図しているのは「スキップせず余白の分のキャンバスを持つビットマップ画像を出す」だと思います。他は動いているようです。

 # 例外処理、スキームが多いと難しいですね…

**Comment by doraTeX** [comment]
> Mac 版 Beta 1.9.6 beta6 で、「余白をつけたビットマップ画像」が画質優先・速度優先ともに「スキップするのにメッセージを出さない」状態になっていることが分かりました。意図しているのは「スキップせず余白の分のキャンバスを持つビットマップ画像を出す」だと思います。

テストありがとうございます。[Ver. 1.9.6 beta 7](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b7.zip) で修正できたはずです。

**Comment by aminophen** [comment]
Windows 版、ようやくテストしました。遅くなって申し訳ありません。

- 余白付きの白紙がスキップされる問題はほぼ解消したようです。「空でした」と言いながら出力するわけですね。一つだけ「ビットマップ出力で、かつ px 単位の余白が小さい場合」に画像が出てこないようです（たとえば上下左右 5px だと出てきませんが、100px だと出てきます。桁落ちしているのでしょうか）。

あとは大丈夫そうです。でも上に書いたのもそんなに問題ない気がします…

**Comment by abenori** [comment]
> 余白付きの白紙がスキップされる問題はほぼ解消したようです。「空でした」と言いながら出力するわけですね。

あくまで「白紙ページはミスだろう」と思っての警告です．

>  一つだけ「ビットマップ出力で、かつ px 単位の余白が小さい場合」に画像が出てこないようです（たとえば上下左右 5px だと出てきませんが、100px だと出てきます。桁落ちしているのでしょうか）。

あーそうですね．epsのマージンを増やすときにいったん解像度レベルで割っているので，5/6 = 0となっているんだと思います．ページが空とか関係なく問題になる気がしますね．極力分岐を起こさないようにしたのが失敗しました．少し考えてみます．

**Comment by aminophen** [comment]
> あくまで「白紙ページはミスだろう」と思っての警告です．

白紙だったら心配されかねないので、警告があるとありがたいでしょうね。

> epsのマージンを増やすときにいったん解像度レベルで割っているので

やはりそこでしたか。余白のつき方が白紙かどうかにかかわらず本来と違うことになるのはそのとおりですね。

**Comment by abenori** [comment]
うーん，上で書いたEPS→IMGの処理方式の変更が早速裏目に出たようです．（とはいえ問題自身は前々からあったように思われますが．）translateは多分整数じゃなくても大丈夫ですよね？仕方ないので戻します．

**Comment by aminophen** [comment]
> テストありがとうございます。Ver. 1.9.6 beta 7 で修正できたはずです。

Mac 版 Ver. 1.9.6 beta 7 では画像変換およびメッセージはすべて意図したとおりになっているように思います。空白ページの扱いがキャンバスが0の場合も余白付きの場合も、ビットマップでもベクターでも、画質優先でも速度優先でも、テキスト保持でもアウトライン化でも正常のようです。ありがとうございます。

**Comment by doraTeX** [comment]
Windows版のように，「白紙ページに余白付与した結果白い画像が生成された」場合にその警告を出すようにもしてみようと思います。今しばらくお待ちください。

**Comment by doraTeX** [comment]
#16 とあわせて，[Ver. 1.9.6 beta 8](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b8.zip) で，「白紙ページに余白付与した結果白い画像が生成された場合に警告を表示」する機能を付けました。

**Comment by aminophen** [comment]
Mac 版 Ver. 1.9.6 beta 8 を試しました。

> 「白紙ページに余白付与した結果白い画像が生成された場合に警告を表示」する機能を付けました。

警告が出るようになったのを確認しました。問題ないと思います。

**Comment by doraTeX** [comment]
> >どちらでもなくて，
>
> もはや把握できなくなってしまいました…😅 Windows 版と合わせて頭の中が混乱しそうですが、私の記事も今度直します…

今改めて確認しました。[TeX2img (Windows/Mac) の動作の詳細（改訂版）](http://acetaminophen.hatenablog.com/entry/tex2img-converter)の

> **【JPG/PNG/BMP/GIF/TIFF 出力（速度優先モード）の場合】**
>
> TeX →…→ PDF →[pdfcrop類似処理でクロップ＋余白付与]→
  PDF →[OS XのQuartz API]→ JPG/PNG/BMP/GIF/TIFF

は，正しくは

> TeX →…→ PDF →[pdfcrop類似処理でクロップ]→
>  PDF →[OS XのQuartz API＋余白付与]→ JPG/PNG/BMP/GIF/TIFF

となります。（PDF→PDF の変換においては，px 単位の余白付与ができないからです。）

**Comment by aminophen** [comment]
> 今改めて確認しました。TeX2img (Windows/Mac) の動作の詳細（改訂版）

ありがとうございます。記事を修正しました。

**Comment by abenori** [comment]
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

eps --> jpg等を元に戻して，更にtranslateに整数に切らない値を与えることにしました．PostScript全然知らないのでいいのかわかりませんが……とりあえず動いているっぽいです．

>    TeX →…→ PDF →[gs (eps(2)write)でアウトライン化＋クロップ]→ EPS →[BB情報を編集して余白付与]→[gs (jpeg/pngalpha/bmp16m)]→ JPG/PNG/BMP

も厳密にはかつある意味では嘘ですね．しかし細かいことはうるさい気もするのでまぁいいか……．

> これは考慮すべきパターンが非常に多くて大変でした

実はこっちは（結果的には）あまり手を加えていません．例外処理もあまり無し．API呼び出しによる複雑さ故でしょうか．

**Comment by aminophen** [comment]
Windows 版を試しました。

> eps --> jpg等を元に戻して，更にtranslateに整数に切らない値を与えることにしました．

大丈夫そうです。ひとつだけ、Windows 版は生成画像のうち最初の一枚をプレビューする仕様ですが、1ページ目がスキップされた場合に欠番となった equation-1 がプレビューされうることに気づきました（前回の TeX2img 処理で当該ファイルが生成していた場合など）。画像が全てスキップされた場合はプレビューしないので大丈夫そうですが、「同じディレクトリにある“数字がいちばん小さいファイル”をプレビュー」になっているような気がして若干気になりました。

> 実はこっちは（結果的には）あまり手を加えていません．例外処理もあまり無し．API呼び出しによる複雑さ故でしょうか．

確かに Mac 版は「画質優先モード」と「速度優先モード」で gs を使ったり OS X の API を使ったりしているので、複雑になった感じはありますね。

**Comment by abenori** [comment]
> 「同じディレクトリにある“数字がいちばん小さいファイル”をプレビュー」になっているような気がして若干気になりました。

別のプログラムが生成している可能性を忘れていました．生成された一番最初のファイルをプレビューするようにしました．（前々から）複数ページの場合はどれをプレビューするべきかは悩んでいます．

**Comment by aminophen** [comment]
> 生成された一番最初のファイルをプレビューするようにしました．

Windows 版、確認しました。ありがとうございます。

> （前々から）複数ページの場合はどれをプレビューするべきかは悩んでいます．

Mac 版は「生成した画像全て」をプレビューするようになっていますが、これは合わせても合わせなくても良いと思っていました。

別件ですが、#23 で「[CUI 版の「ソース埋め込み」をデフォルトで OFF にしよう（プレビュー同様に GUI の設定を無視しよう）](https://github.com/doraTeX/TeX2img/issues/23#issuecomment-128034512)」という話が出ていますが、いかがでしょう。

**Comment by abenori** [comment]
> Mac 版は「生成した画像全て」をプレビューするようになっていますが、これは合わせても合わせなくても良いと思っていました。

あ，そうなのですね．どっちが便利ですかねぇ．まぁとりあえず今のままでよいか……．

> 別件ですが、#23 で「CUI 版の「ソース埋め込み」をデフォルトで OFF にしよう」という話が出ていますが、いかがでしょう。

これはあっちに書いた方がよいですね．
