### ISSUE TITLE
行単位のコメントアウト・アンコメント機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#22]
TeXShop の Command + { や Command + } と同じコメントアウト・アンコメント機能を同じショートカットキーで付与したい。

**Comment by doraTeX** [comment]
機能を追加しました。[Ver. 1.9.6 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b2.zip) として置いておきます。

## 検討項目

- 行の左右シフト機能にもショートカットキーを設けるべきか。設けるならばどのようなショートカットか。
- 現在は行のシフトで挿入されるインデントはタブ文字に固定されている。スペースでのインデントも可能にすべきか。すると環境設定パネルに「インデント時にタブの代わりにスペースを挿入」のようなチェックボックスを設けることになる。（スペースの個数は「タブ幅」の設定に従うとして。）

**Comment by aminophen** [comment]
コメントアウト・アンコメント機能を確認しました。

> - 行の左右シフト機能にもショートカットキーを設けるべきか。

使用頻度がどの程度か分かりませんが、あったほうが良いのは確かですね（そもそも今のメニューだけだったら手動でタブ文字を消すほうが早そうですから）。TeXShop でも使ったことはなかったのですが、ショートカットキーがなかったのですね… Command + > とか Command + < とかは TeXShop では使っていましたっけ？

> - スペースでのインデントも可能にすべきか。

確かに、タブ幅の設定ができるようになったのでスペース置換しやすくなりましたね。私は個人的にタブよりスペースが好きなのでありがたいですが、UI の増大との兼ね合いなのでお任せします。

**Comment by doraTeX** [comment]
* 行の右・左シフトをそれぞれ ⌘>，⌘< に割り当て。
* 環境設定パネルに「タブインデント」というチェックボックスを追加。これがON（デフォルト）だとシフト時にタブが，OFFだとシフト時にスペース（個数は「タブ幅」に従う）が挿入・削除される。

とした，[Ver. 1.9.6 beta 3](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.6b3.zip) を作りました。

> TeXShop でも使ったことはなかったのですが、ショートカットキーがなかったのですね… Command + > とか Command + < とかは TeXShop では使っていましたっけ？

TeXShop の場合，メニューにショートカットキーをたくさん割り当てるほど，「マクロ」メニューでユーザが自由に割り当てられるショートカットキーの種類が減ってしまうというジレンマがあるので，あまりむやみにショートカットキーを割り当てまくることができないという悩みがあります。
