### ISSUE TITLE
「文字情報」機能を設ける

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#26]
* TeXShop に導入したのと同じ「文字情報」を機能を TeX2img にも設ける。
* Inspect, Information ということで，ショートカットキーは Command+Option+I でどうだろう。（TeXShop ではショートカットキーを設けていない。）

**Comment by aminophen** [comment]
TeXShop でも「文字情報」や「統計情報」は使ったことがありませんでした…

FAQ も出来上がっていない部分ですね。どんな機能でしょう？

**Comment by aminophen** [comment]
> どんな機能でしょう？

ああ、選択した部分の「文字情報」を表示する機能ですね！

![texshop-charinfo](https://cloud.githubusercontent.com/assets/9957466/9159822/0722951e-3f6b-11e5-8d14-cf4870da3992.png)

**Comment by doraTeX** [comment]
次のような仕様にしてみました。

* 「表示」メニューの中に「文字情報」メニューを追加。
* 「表示」メニューの中の他の項目が Command + Shift のショートカットキーなので，それに合わせて Command + Shift + I としてみました。

# 使用例

## BMP内文字（単独）
![2015-08-10 15 34 38](https://cloud.githubusercontent.com/assets/6186180/9160669/5ccf677e-3f77-11e5-922d-9100e744cac2.png)

## BMP内文字＋結合用文字
![2015-08-10 15 34 47](https://cloud.githubusercontent.com/assets/6186180/9160668/5a64dbea-3f77-11e5-8208-82c9476ea94f.png)

## BMP内絵文字（単独）
![2015-08-10 15 42 17](https://cloud.githubusercontent.com/assets/6186180/9160665/5632ef94-3f77-11e5-8dd6-4d0e2aed0689.png)

## BMP内絵文字＋絵文字セレクタ（テキストスタイル）
![2015-08-10 15 42 23](https://cloud.githubusercontent.com/assets/6186180/9160661/52965380-3f77-11e5-8ed4-840b2fbaeea2.png)

## BMP内絵文字＋絵文字セレクタ（絵文字スタイル）
![2015-08-10 15 42 31](https://cloud.githubusercontent.com/assets/6186180/9160660/508156c6-3f77-11e5-8664-07b4ee962ceb.png)

## BMP外文字（単独）
![2015-08-10 15 42 51](https://cloud.githubusercontent.com/assets/6186180/9160658/4e2aa030-3f77-11e5-83b0-7f6223bc4a6f.png)

## BMP外文字＋結合用文字
![2015-08-10 15 43 03](https://cloud.githubusercontent.com/assets/6186180/9160656/4b3ac97c-3f77-11e5-8d69-14da6cc94d9a.png)

## BMP外絵文字（単独）
![2015-08-10 15 43 59](https://cloud.githubusercontent.com/assets/6186180/9160649/1a28d464-3f77-11e5-9593-cd36343873a9.png)



## BMP外絵文字（複数結合）
![2015-08-10 15 44 37](https://cloud.githubusercontent.com/assets/6186180/9160647/178b0222-3f77-11e5-8cfe-bc49b20bda0a.png)


## BMP外絵文字＋スキントーンセレクタ
![2015-08-10 15 44 52](https://cloud.githubusercontent.com/assets/6186180/9160642/1345ac94-3f77-11e5-97b8-80a076bbe6dd.png)


## 国旗絵文字
![2015-08-10 15 45 10](https://cloud.githubusercontent.com/assets/6186180/9160638/0da7a2e2-3f77-11e5-91fb-fbe606d1cdf3.png)

## 複数文字
この場合は「文字数・単語数・行数」の統計情報を表示します。

![2015-08-10 15 46 16](https://cloud.githubusercontent.com/assets/6186180/9160636/0a50b89a-3f77-11e5-9553-e0dea7f50d05.png)

**Comment by doraTeX** [comment]
日本語対応も問題ありません。バイト数にかかわらず，「見た目の文字数」を計算します。

![2015-08-10 16 14 28](https://cloud.githubusercontent.com/assets/6186180/9161318/bee1516c-3f7b-11e5-854d-025d4b4281c9.png)

なお，単語数は「英単語数」ということで，上記スクリーンショットでは単語数は 0 と表示されています。（実装上では，英語スペルチェックカを起動し，それが認識した単語数をとっています。）
