### ISSUE TITLE
制御綴の色分けにおいて，\makeatletter を有効扱いにするか否かを選べるようにする

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#30]
環境設定パネルの「色」の設定で，制御綴の色分けにおいて，\makeatletter を有効扱い・無効扱いのどちらにするかを選べるようにする。
つまり，`\hoge@fuga` のような並びに対し，`\hoge` までを制御綴と見なすか，`\hoge@fuga` 全体を制御綴と見なすかを選べるようにする。
この設定は，hoge の部分をダブルクリックしたときに，自動的に広がる選択範囲をどこまで伸ばすかにも影響させるようにする。

**Comment by doraTeX** [comment]
次のようなボタンを設置。

![2015-08-18 16 01 30](https://cloud.githubusercontent.com/assets/6186180/9324173/dd97f032-45c2-11e5-9f3e-a90864a5056d.png)

**Comment by aminophen** [comment]
もう commit されたようですが、なんだか一般ユーザに馴染みのない名前がメニューで出てきて怖いかなあと思いました。従来は \hoge@fuga 全体を制御綴とみなす仕様でしたので、本機能は「\hoge@fuga のうち \hoge だけが制御綴で @ 以下が地の文」という場合を考慮してのことですね。ですが、事象自体が極めて少なそうで、敢えて設定する人はいないだろうという気がします。色の設定に「\makeatletter 有効」という項目があっても、用途がわからないひとが多そうです。

**Comment by doraTeX** [comment]
では，このようにマウスオーバー時にポップアップで説明を出すという案はどうでしょう？
<img width="623" alt="2015-08-23 1 18 15" src="https://cloud.githubusercontent.com/assets/6186180/9424810/fe87e282-4934-11e5-8c54-8a48943c1157.png">

**Comment by aminophen** [comment]
> マウスオーバー時にポップアップで説明を出すという案

LaTeX 的に文書全体が \makeatletter 有効とみなされるのではなく、「色づけとダブルクリック選択時の挙動だけ」に影響するものであることがわかる説明ですね。それだと機能の意味はわかるようになるので良いかもしれません。でも今のままだと標準で ON なので、そこから OFF にしたい人がいるとは思わないです…（\makeatletter を知っていてそれが必要な人はそもそも ON にして制御綴に @ を混ぜるだろうし、\makeatletter を知らない人はそんなポップアップも読まないだろう）

とすると、標準を「\makeatletter 無効」な状態にして置き、\makeatletter を使いたい人だけ ON にするようにするのがよいでしょうか。（他の統合環境はほとんど @ を含めて制御綴として着色するので、それらとは標準が違うことになりますが）

**Comment by doraTeX** [comment]
* おっしゃるように，\hoge@fuga のような並びで \hoge で制御綴を切りたい状況が滅多にない
* それよりは，プリアンブル部で \makeatletter を効かせて @ 入りの命令を改変したい場合の方が多そう
* 他の統合環境は @ を制御綴として着色する

といった事情を考えると，現行通り，

* デフォルトは「\makeatletter 有効」のチェックがON
* \makeatother 下において \hoge@fuga のような並びを使用したい特異な人だけにOFFにして使ってもらう

という扱いの方がよいのではと思いますが，いかがでしょう？
