### ISSUE TITLE
bxjsarticle v1.x への対応

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#31]
[BXjscls](http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?BXjscls) が v.1.0 以降，ドキュメントクラスオプションなどの仕様が若干変更になっています。
TeX2img がデフォルトで内蔵している XeLaTeX 用プリアンブルテンプレートもそれに応じて変更すべきでしょうか？
それとも，最新版を使っていないユーザの利便性を考えて，現行ソースが v.1.x でも通るならそのまま使い続けることにしましょうか。（和文文書で XeLaTeX を使っているような新しい物好きのユーザーなら最新版を使っていることを仮定してもよさそうな気もしますが，不安もあります。）

```tex
% compiler: xelatex
\documentclass[fleqn]{bxjsarticle}
\usepackage{zxjatype}
\setCJKmainfont[BoldFont=ヒラギノ明朝 ProN W6]{ヒラギノ明朝 ProN W3}
\setCJKsansfont[BoldFont=ヒラギノ角ゴ ProN W6]{ヒラギノ角ゴ ProN W3}
\usepackage{amsmath,amssymb}
\usepackage{graphicx,color}
\pagestyle{empty}
```

**Comment by aminophen** [comment]
仕様変更後のソースが昔の XeLaTeX とか BXjscls のバージョン次第で通らないというのであれば、あまり変えたくないのが本音です。まだ BXjscls 1.0 が CTAN に出て半月も経っていないので怖いです。

別件ですが、いま久々に TeX Wiki の「LaTeX 入門」を見て、すべてあたかも bxjsarticle で upLaTeX するのが普通であるかのような記述に全部いつの間にか変わっているのに驚きました。私は jsarticle で pLaTeX するのが一番多くの環境で動くと思っていたのですが、もはや BXjscls で upLaTeX が標準にしたいのでしょうか。履歴をみると編集合戦の跡がみえますね…

 # ふつう心配すべきは BXjscls が入っているかどうかより upLaTeX が入っているかどうかが先決だと思うのですが、その辺の論理は私の記述がそのまま残っているせいでちぐはぐですし…大丈夫かな。

**Comment by doraTeX** [comment]
では当面は現在のテンプレートを維持することをいたしましょうか。

> 別件ですが、いま久々に TeX Wiki の「LaTeX 入門」を見て、すべてあたかも bxjsarticle で upLaTeX するのが普通であるかのような記述に全部いつの間にか変わっているのに驚きました。

それはさすがに急進的に過ぎるような気がしますね……
