### ISSUE TITLE
gs9.15 以上の eps2write デバイスでもクロップに失敗する例がある

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#37]
#18 「gs9.14 以下の epswrite デバイスでクロップに失敗する例がある」と同様の問題が，gs9.15 以上の eps2write デバイスでも起こることがある模様。

* [再現PDF](https://dl.dropboxusercontent.com/u/5807100/sushi.pdf)

このPDFは，`gs -sDEVICE=eps2write` で生成されるEPSのbboxと，`gs -sDEVICE=bbox` で得られるbboxが一致しません。

対策としては，#18 と同様に，

**gs の eps(2)write デバイスで得られたEPSのBB情報は信用せず，生成したEPSのBB情報を，「元PDFに対する `gs -sDEVICE=bbox` の出力内容」で上書きする**

とすることが考えられます。

**Comment by aminophen** [comment]
回転寿司ですね！ 手元のこれもかつての「epswrite を使うと無数の細かいパスに分割されてオーバーフローする」例のようで、eps2write だとビットマップ化されています。…あれ、Windows 版ってもともと eps2write でも epswrite でも bbox を使って上書きするようになっているっぽいです。
