### ISSUE TITLE
PDF出力のときに単一PDFとして出力する機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#38]
#36 の

> Acrobat と異なり TeX2img では全ページバラバラにされてしまいますが。

というのを書いた後に，単一PDFとして出力する機能があると便利だろうと思いました。

## 方法
「出力画像の設定」のところに

- [x] 単一ファイルにまとめる (PDF)

のような設定項目(CUI: --merge-files)を追加する。
PDF結合処理は OS X のAPI で可能。

**Comment by aminophen** [comment]
> PDF結合処理は OS X のAPI で可能。

実装についてはまだ中立ですが：

- pdfcrop 類似処理は本来の「一つにまとめて」というスキームにすれば可能
- gs の pdfwrite 経由時はそもそも pdfwrite デバイスが「複数ページ PDF を吐ける」仕様なので可能

な気がします。自前で実装するのとどちらが手っ取り早いでしょう？

**Comment by doraTeX** [comment]
> pdfcrop 類似処理は本来の「一つにまとめて」というスキームにすれば可能

この方法では「ページごとにMediaBoxがバラバラ」のPDFは作れないのではないでしょうか。

> gs の pdfwrite 経由時はそもそも pdfwrite デバイスが「複数ページ PDF を吐ける」仕様なので可能

この場合アウトライン化PDFが作れないのでは。

**Comment by aminophen** [comment]
MediaBox がそれぞれ違うテキスト保持 PDF というのは本家の pdfcrop が吐いているのとどこが違うのか分かっていません（あれはページごとに適切にクロップしていろんなサイズのページが一つのファイルにできる）。

アウトライン化のほうは

~~~~
gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -sOutputFile=combined.pdf first.pdf second.ps third.eps
~~~~

みたいな mixture ができるので、直接 EPS から PDF を作れます。

**Comment by doraTeX** [comment]
なるほど，確かにそれぞれ可能ではありますね。

ですが，実装の利便性からは，従来の経路の最後に「生成物を1つにまとめる」という処理を付け加える方が変換経路の場合分けを増やさなくて楽ですので，OS X API で行こうと思います。
