### ISSUE TITLE
マスクメロン版 Ghostscript のサポート解除

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#41]
標準で日本語設定がなされているという理由で，[Ver. 1.9.9 から採用された](https://github.com/doraTeX/TeX2img/issues/28#issuecomment-135743647)「マスクメロン版 Ghostscript のサポート」（パスの自動判定のサーチ対象に含め，かつ優先順位を最高に）ですが，これは X11 依存性があることが判明。
X11が標準でインストールされていない 10.8 Mountain Lion 以降で実行すると，次のようなダイアログが出てエラーとなってしまいます。

<img width="652" alt="2015-09-10 3 21 38" src="https://cloud.githubusercontent.com/assets/6186180/9770553/ac72ce4a-576b-11e5-96f4-2784fe42b838.png">

10.8 以降では，X11依存性のあるアプリは XQuartz を別途インストールせねばなりません。ですが XQuartz は一度インストールすると完全なアンインストールが難しい（OS再インストール or OSアップデートするしかない）ので，インストールを勧めるのは気が進みません。個人的にも，一度インストールしてしまうとX11依存・非依存の判定が難しくなることもあり，極力インストールしたくないところです。

「10.8 以降で標準で動かない」という理由で，マスクメロン版 Ghostscript.app はサポート対象から外すのがよいのではないかと思います。

**Comment by doraTeX** [comment]
解除しておきました。

一方で，10.6 では標準でX11がインストールされているので，v.1.10.x 系列では引き続きマスクメロン版サポートを続けてよいと思います。

**Comment by aminophen** [comment]
了解しました。設定が完了していない環境については [Ghostscript/OS X - TeX Wiki](http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?Ghostscript%2FOS%20X) を参考にやってもらうしかないですね。

**Comment by aminophen** [comment]
小川版 UpTeX.app が BasicTeX + texlive-collection-langjapanese ベースになって復活したので、Windows で dmg を解凍して README.pdf やら本体やらを見ているところです。TeX Live バイナリへのシンボリックリンクたちが /Applications/UpTeX.app/Contents/Resources/texbin/ に入るようになっているので、こちらには対応してもいいかも？（Yosemite / El Capitan に対応しているそうですが、実機がないので試せないので）

**Comment by doraTeX** [comment]
>  /Applications/UpTeX.app/Contents/Resources/texbin/ に入るようになっているので、こちらには対応してもいいかも？

Ver. 2.0.x, Ver.1.10.x の両系列で対応しておきました。

**Comment by aminophen** [comment]
ありがとうございます。El Capitan のフォント周りは UpTeX.app に先を越されてしまいました（texmf-local/fonts 以下にヒラギノ ttc たちへのシンボリックリンクと北川さんの jfontmaps が取り込まれている）が、ぼちぼち Golden Master 版も固まってきたようなので TeX Live 側の対応を始めてもらうことになりますね。TeX Wiki もこの方法を書くべき時期に入ってきたと思います。

**Comment by doraTeX** [comment]
まだ UpTeX.app を見ていないのですが，UpTeX.app のシンボリックリンクの張り方は[munepiさんの案](https://gist.github.com/munepi/396ef67e3ad051663399)に沿う感じでしょうか？
シンボリックリンクの張り方はディストリビューション間で統一されていた方がよいですね。

**Comment by aminophen** [comment]
そうなっているように見えます（Windows で HFSExplorer からモニターできる範囲で）。ヒラギノと游について Yosemite 付属 otf へのシンボリックリンクの姿があり、ヒラギノに限って新しい El Capitan 付属 ttc のシンボリックリンクが用意されているようです。これらの貼り方は北川さんの jfontmaps からも一意に決まると思うので、これは TeX Live 本体でも同様になると思います。

**Comment by doraTeX** [comment]
ありがとうございます。
では，今後のロードマップとしては，

* TeX Live に北川さんの hiragino-elcapitan を取り込んでもらう
* TeX Live 2015 ユーザには，TeX Live のレポジトリ更新 ＋ [lnsysfnt.sh](https://gist.github.com/munepi/396ef67e3ad051663399)の実行 ＋ updmap 変更をしてもらうよう告知する
  * sudo tlmgr update --self --all
  * sudo ./lnsysfnt.sh
  * sudo mktexlsr
  * sudo kanji-config-updmap-sys hiragino-elcapitan
* 美文書第6版ユーザには，手動でこれと同じことを実現する方法を提示する（？）

という感じでしょうか。

**Comment by aminophen** [comment]
おそらくそれが一番良いと思います。実機がある doraTeX さんに lnsysfnt.sh と新しい jfontmaps の TeX Live での動作確認および UpTeX.app の挙動確認はお願いしたいと思いますが、それで問題なければロードマップどおりに進めていきましょう。

**Comment by aminophen** [comment]
> 美文書第6版ユーザには，手動でこれと同じことを実現する方法を提示する（？）

できればサポートページに「lnsysfnt.sh 実行 → jfontmaps の新しいものを texmf-local に入れる → mktexlsr → sudo kanji-config-updmap-sys hiragino-elcapitan」をまとめた AppleScript でも置いておいて、自動でやると楽でしょうね。

**Comment by aminophen** [comment]
小川版 UpTeX.app が10月9日の変更でシンボリックリンク作成先を

`UpTeX.app/Contents/Resources/texbin/` から `UpTeX.app/Contents/Resources/TEX/texbin/ へ

変更したようです（TEX は大文字らしい）。こちらも追加しなければならないでしょうね。

**Comment by doraTeX** [comment]
対応しておきました。次回アップデート時に反映されます。

**Comment by aminophen** [comment]
ありがとうございます。
