### ISSUE TITLE
マルチページTIFF形式での出力に対応する

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#44]
Windows版がマルチページTIFF形式での出力に対応したようなので，Mac版でも対応しよう。

# 実装法の案

* OS X のAPI ➡ マルチページTIFF出力に非対応の模様
* Ghostscript ➡ マルチページTIFFは作れるが，背景透過のTIFF出力ができない模様
* [libtiff](http://libtiff.maptools.org) 付属の [tiffcp](http://www.remotesensing.org/libtiff/man/tiffcp.1.html) コマンド ➡ 便利！

というわけで，

* SVG出力における mudraw 同様に，TeX2img.app の中に tiffcp コマンドを内包しておきそれを使う。
* tiffcp コマンドは 10.6 以降で動くようにビルドしておく。
* CUI版でマルチページTIFF出力を行いたい場合は，ユーザが各自 tiffcp コマンドをインストールしておくか，または /Applications 内に TeX2img.app を入れておくことを要求する。
* 単一PDF出力機能と同様に，既存の「バラバラTIFF出力」を行った後に，最後に tiffcp コマンドで単一ファイルにまとめるステップを挟み込む。

という方法で実装しよう。

**Comment by aminophen** [comment]
いま Mac が手元にないのですが、あまり色々抱え込まなくても Win 版のような自前の tiffconcat ができれば理想ではあります。マルチページ化だけために抱え込むのはなんだか勿体無い気がします。

**Comment by doraTeX** [comment]
調べてみたところ，tiffcp コマンドを抱え込んだり，自前でTIFF連結処理を実装したりしなくても，OS X には標準で tiffcp をベースにした [/usr/lbin/tiffutil](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/tiffutil.1.html) というツールが存在していました。
OS X には遙か昔から（10.2くらいから？）存在していたようです。

これを使うように直ちに切り替えます。

**Comment by aminophen** [comment]
> tiffcp をベースにした /usr/lbin/tiffutil というツールが存在していました。

おお…より良い方法が見つかってよかったです。Apple スゴイ…

**Comment by aminophen** [comment]
TIFF やってしまったら animation GIF もという欲が生じ、調べたら Objective-C の[短いコード例](http://anz-note.tumblr.com/post/92059538906/objective-c%E3%81%A7%E8%A4%87%E6%95%B0%E7%94%BB%E5%83%8F%E3%81%8B%E3%82%89gif%E3%81%A4%E3%81%8F%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%88)が出てきました。C# のほうは[こっち](http://dobon.net/vb/dotnet/graphics/createanimatedgif.html)にありそうです。TikZ の連成振動を直接 animation GIF にできたら楽しそうです（前にも言った気がする…）。
