### ISSUE TITLE
SVGのコメントにもソース情報を保存する？

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#50]
PDFについては，注釈情報を経由することで Mac ⇄ Windows のソースの互換性が確保できました。
他にソース情報をデータフォーク側に容易に埋め込めるフォーマットとしては，SVGが挙げられます。

例えば，`<svg>` の前に，次のようなコメントを追加するというような方法です。
XMLの禁止文字 (`&	< > " ' `) を回避するために，ソースをBASE64エンコーディングしています。

```html
<!--
%%TeX2img Document
JSBMYVRlWCBjb21waWxlcjogcGxhdGV4CiUgRFZJIGRyaXZlcjogZHZpcGRmbXgKXGRvY3Vt
ZW50Y2xhc3NbZmxlcW4scGFwZXJzaXplXXtqc2FydGljbGV9Clx1c2VwYWNrYWdle2Ftc21h
dGgsYW1zc3ltYn0KXHVzZXBhY2thZ2VbZHZpcGRmbXhde2dyYXBoaWN4LGNvbG9yfQpccGFn
ZXN0eWxle2VtcHR5fQoKXGJlZ2lue2RvY3VtZW50fQrjgYrjga/jgojjgYbjgZTjgZbjgYTj
gb7jgZnjgIIKXFtcemV0YSgyKT1cc3VtX3tuPTF9XntcaW5mdHl9XGZyYWN7MX17bl4yfT1c
ZnJhY3tccGleMn17Nn1cXQoKXGVuZHtkb2N1bWVudH0K
-->
```

ただ，SVGソースが若干大きくなってしまうという欠点はあります。
SVGの利用法としてはウェブやepubへの埋め込みが主と考えられるため，余計なコメントによるファイルサイズの増加は好まれないかもしれません。

また，PDFの注釈情報へのソース埋め込みは，PowerPointからのソース復元という大きなメリットがありましたが，SVGについてはPowerPointやKeynoteに埋め込めないため，SVGコメントにソースを埋め込んでも，

* Mac ⇄ Windows のソースの互換性向上
* 拡張属性が失われたときの保険

というメリットしかなく，ありがたみが薄いかもしれません。

**Comment by aminophen** [comment]
> SVGの利用法としてはウェブやepubへの埋め込みが主と考えられる

> PDFの注釈情報へのソース埋め込みは，PowerPointからのソース復元という大きなメリットがありましたが，SVGについてはPowerPointやKeynoteに埋め込めない

私も、PDF のアノテーションは実用性がありますが SVG は用途が異なるので実用性はないと考えています。ソースを SVG の注釈に埋め込むことは特に希望しておりません。

**Comment by doraTeX** [comment]
では不要ということでよさそうですね。
