### ISSUE TITLE
アプリケーションアイコンの再デザイン

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#51]
現行のアプリケーションアイコンは，TeX2img を作り始めた2007年に30分くらいで即興で作ったもので，正直言って完成度は高くありません。

特に，Yosemite で OS X のデザインがフラットデザインに移行した今，現行の TeX2img のアイコンは「旧世代臭」がしてしまいます。

TeXShop も昨年，長年使ってきたアイコンを捨てて Yosemite 風の丸いデザインのアイコンに変更したことですし，TeX2img もモダンなデザインのアイコンに移行すべきかと考えています。
- Safari, Mac App Store, iTunes, iBooks, Photos, そして TeXShop 同様の丸いデザイン
- または Notes, Calender, Text Edit, Script Editor, Xcode のような斜め右上がり長方形のデザイン
- テクスチャや陰影は抑えめでフラットに近いデザインだが，控えめの光沢は入っており，完全なフラットデザインではない。
- Retinaディスプレイ時代の今，1024x1024の拡大に耐えるだけの作り込まれたデザインである必要がある。

iOS アプリの売り上げはアイコンで半分決まると言われるほど，アプリアイコンの印象は重要です。
ですが，このような細かい要件に応えようとすると，もはや素人の片手間では不可能です。
そこで，クラウドソーシングでプロのデザイナーに発注するとよいのではと考えています。
相場を調べてみると，数万円程度の予算で可能そうです。
# 検討課題
- デザインに TeX や img といった文字を大きく入れるか？それともアプリの働きを絵で表現するか？
- Windows 版も合わせて提供できるようなセットでデザイン発注すべきか。その場合，Windows のアイコンのデザイン要件は？

<img width="260" alt="2015-10-13 1 18 10" src="https://cloud.githubusercontent.com/assets/6186180/10432951/8c3b1450-7149-11e5-9da6-bb58a8330d60.png">
<img width="274" alt="2015-10-13 1 18 30" src="https://cloud.githubusercontent.com/assets/6186180/10432953/8c738286-7149-11e5-99bd-6210e33b6af7.png">
<img width="255" alt="2015-10-13 1 18 47" src="https://cloud.githubusercontent.com/assets/6186180/10432957/8c790bd4-7149-11e5-8359-28df2aab75aa.png">
<img width="291" alt="2015-10-13 1 19 06" src="https://cloud.githubusercontent.com/assets/6186180/10432954/8c75057a-7149-11e5-8fac-ac1face6931a.png">
<img width="262" alt="2015-10-13 1 28 05" src="https://cloud.githubusercontent.com/assets/6186180/10432993/b7a4fdae-7149-11e5-81c9-9fd99775eb82.png">
<img width="242" alt="2015-10-13 1 20 27" src="https://cloud.githubusercontent.com/assets/6186180/10432955/8c76afba-7149-11e5-94c4-f0789477e03b.png">
<img width="269" alt="2015-10-13 1 20 31" src="https://cloud.githubusercontent.com/assets/6186180/10432956/8c77222e-7149-11e5-8bd1-9e7473fa88b5.png">
<img width="249" alt="2015-10-13 1 20 43" src="https://cloud.githubusercontent.com/assets/6186180/10432952/8c6071b4-7149-11e5-88a6-ad93d2671698.png">
<img width="290" alt="2015-10-13 1 20 48" src="https://cloud.githubusercontent.com/assets/6186180/10432958/8c82f66c-7149-11e5-991c-4406dada34b3.png">

**Comment by aminophen** [comment]
恐ろしい気合いの入れ方ですね😮しかしアイコンは確かに重要ですね。

- TeXShop の逆三角形は斬新だったのであれは残ってよかったかなあと思っていた（今のは言ってしまえばなんの面白みもない…）
- うちでは（Lion ですが）Adobe のアプリの四角アイコンと並んでいるので違和感を感じたことがなかった（ちょっと小さいかな？くらい）

などを思いました。それらを払拭するようなアイコンなら歓迎です。（ハードル↑↑）

**Comment by aminophen** [comment]
全然関係ないですが、最近 Twitter で流れてくる結城さんの絵が可愛いですね😊

**Comment by doraTeX** [comment]
自分もあのように気の利いた絵心があればいいのですが……😓

**Comment by aminophen** [comment]
doraTeX さんの Avatar もかなりイケてるじゃないですか！

**Comment by abenori** [comment]
> 恐ろしい気合いの入れ方ですね

同感です……．こっちは気合いが入っていないので，アイコンはあればありがたく使わせてもらうと思います．（なければそのまま）

**Comment by doraTeX** [comment]
> doraTeX さんの Avatar もかなりイケてるじゃないですか！

これは自分で描いたものではなく，絵心が達者（というか，東大工学部建築学科→工学系研究科建築学専攻→建築設計会社 という経歴の方なのでプロ）な元生徒さんが描いてくれた似顔絵です。

いろんなバージョンがあります。

### 3D版
![twitter 3d](https://cloud.githubusercontent.com/assets/6186180/10594968/c19941f2-770d-11e5-8a69-3f4055f03bc9.jpg)

### ステッカー版
![img_2067](https://cloud.githubusercontent.com/assets/6186180/10594977/d928943a-770d-11e5-9407-d687a21b8302.JPG)

### アルバム・ネクタイ版
![10882320_748263635257351_3322295104688901896_n](https://cloud.githubusercontent.com/assets/6186180/10594980/e3f590d4-770d-11e5-9554-518a2a302d18.jpg)

**Comment by doraTeX** [comment]
Ver. 2.2.1 にてアプリアイコンを変更。
