### ISSUE TITLE
EMF出力のサポート

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#57]
Mac版 Office 2016 は，Windows版との互換性を向上させた結果，PDFサポートが苦手という特徴まで受け継がれてしまい，PDFサポートが後退してしまったとの話が出ています。
詳細は未確認ですが，Office 2016 for Mac でまともに扱えるベクター形式は EMF だけだという話も聞こえてきます。

現在は100MB超の Inkscape を内包した外部ツールを提供してEMF出力に対応していますが，それ以外の方法でTeX2imgからのEMF直接出力ができればいいですね。

方法を検討してみます。

**Comment by doraTeX** [comment]
pstoedit のEMF出力はベジエ曲線が使えず，文字のアウトラインが折れ線のみで構成されるため，仕上がりがひどいガタガタの文字になってしまうのですが，pstoedit のソースを改修することで仕上がり品質を上げることに成功しました。
しかもライブラリ込みで100MB超の Inkscape と異なり，pstoedit はライブラリ込みでもわずか800KB程度で済みました。
これで高品質なEMF出力の目処が立ちました。あとは TeX2img に組み込んで変換ルーチンを実装するだけです。

**Comment by doraTeX** [comment]
実装も完了しました。白紙ページを含む場合など，例外的ケースへの対応をこれからテストします。

**Comment by aminophen** [comment]
これは朗報です！ Office 2016 の改悪は当面私も確認できないのですが、EMF なら扱えそうですね。CUI 版の場合はどうしましょう？ 独自改変版は TeX2img.app にしか存在しないことになりますので、プログラム名が同じだと混同しそうです。

**Comment by doraTeX** [comment]
それも想定済みです😏
独自改変版は、eps2emf という独自の名前にしてあります。CUI版は、GUI版に内包された eps2emf をサーチして利用します。したがってEMF出力にはGUI版を /Applications または /Applications/TeXLive 内に置いておく必要があります。

**Comment by aminophen** [comment]
さすがです😄 eps2emf という名前もわかりやすいですね。

**Comment by doraTeX** [comment]
EMF出力をサポートした [Ver. 2.0.8 beta 1](https://dl.dropboxusercontent.com/u/5807100/Tex2imgMac2.0.8b1.zip) が完成しました。

## 制約

1. pstoedit がベジエ曲線を使えないので，アンカーポイントをたくさん取って対応していますが，あくまで折れ線の集合体です。大きく拡大するとギザギザが気になります（が，多くの場合概ね許容範囲ではあるでしょう）。
1. Mac 標準で EMF を閲覧するソフトがないので，EMF出力の場合は「コンパイル後プレビュー」機能は無効化してあります。
1. 余白が 0 でも，Office に貼ると一定の余白が勝手に付くようです。左余白・下余白を正の値に指定した場合，Office デフォルトの余白に加えてさらに余白が付きます。逆に，右余白・上余白は切られるので，Office デフォルトの余白以上の余白は付けられません。

このような制約はありますが，それでもEMF出力をサポートする価値はあるでしょう。1. の制約が気に入らず，真になめらかな EMF が欲しい場合は，現状の Inkscape を使う外部ツールで処理すればよいでしょう。

**Comment by aminophen** [comment]
今日はありがとうございました。まだ Mac 版 beta は試していないのですが、脱線中の #56 にコメントしていて思い出したので：[pdfiumdraw の場合](https://github.com/doraTeX/TeX2img/issues/56#issuecomment-154707337)のような、破線が描画されないようなことは起きていませんかね？ たとえば

~~~~ tex
\begin{tikzpicture}
\draw[dashed](0,0)--(1,0);
\end{tikzpicture}
~~~~

の場合などに pdfiumdraw で破線が飛んでしまうのですが、eps2emf も内部的に座標拡大しているというお話を伺ったので pdfiumdraw と似た状況ではないかと気になりました。

**Comment by doraTeX** [comment]
今日は楽しかったですね。色々直接お話しできて大変有意義でした。

> pdfiumdraw の場合のような、破線が描画されないようなことは起きていませんかね？ たとえば

「描画されない」わけではありませんが，確かに何かヘンです。

<img width="578" alt="2015-11-07 23 30 02" src="https://cloud.githubusercontent.com/assets/6186180/11015601/b95e07f4-85a7-11e5-87a4-4194ce060d6f.png">

上が変換前のEPS，下が eps2emf で（100倍拡大→100倍縮小を経由しつつ pstoedit にかけた）EMFを Illustrator で開き上下に並べてみたものです。
パスとして認識されている部分の長さは同じですが，破線としての描画のされかたが異なります。

一方，同じEPSとEMFを Office 2011 に貼ってみたところ，EMFの描画のされ方は Illustrator とも異なりました。

<img width="448" alt="2015-11-07 23 35 40" src="https://cloud.githubusercontent.com/assets/6186180/11015618/4e13c4ba-85a8-11e5-9851-106e07be42dd.png">

このように，EMFの破線というのは，描画のされ方がビューアに依存して大きく変わってしまうようです。EPSの段階で「パスのアウトライン化」をかけることができればよいのですが……。

**Comment by aminophen** [comment]
> 破線としての描画のされかたが異なります。

おっと、それは pdfiumdraw と同じ現象です。[パターンが変わってしまう](https://twitter.com/aminophen/status/608066189135347712)のですね。以前の調査だと破線のパスを分解するために[相当頑張る](http://d.hatena.ne.jp/acetaminophen/20150610/1433937845)か [Inkscape の機能を使う](http://d.hatena.ne.jp/acetaminophen/20150607/1433684008)かが有効でしたが、自動化はどちらも一筋縄ではいかないと思っていました。

**Comment by doraTeX** [comment]
過去の調査を再読し，一通り状況を把握しました。
これは確かに現状ではどうしようもないとして諦めるしかなさそうな状況ですね……。

**Comment by aminophen** [comment]
Ver. 2.0.8 beta 1 のアーカイブが壊れているっぽいです。

**Comment by doraTeX** [comment]
すみません，差し替えました。

**Comment by aminophen** [comment]
EMF 出力を確認しました。上記3点および破線パターンが変わるという制約はありますが、実用上問題ないレベルだと思います。FAQ に「ベジエの EMF を作るための方法」「破線パターンが変わって困る場合の方法」として、それぞれ「いったん EPS を作って Inkacape ベースの補助ツールで EMF に変換」「いったん EPS に変換して Inkscape で開き、パスの変形を行った EPS を補助ツールで EMF に変換」を解説しておけばよいと思います。

**Comment by doraTeX** [comment]
よし，ではそろそろ Ver. 2.0.8 正式リリースですかね。
なお，状況整理のために，[Mac版の変換経路の図](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf) を作りました。

**Comment by aminophen** [comment]
リリースよろしくお願いします！ 変換経路の図も分かりやすいです。

**Comment by doraTeX** [comment]
リリースしておきました。

**Comment by doraTeX** [comment]
変換経路の図をアップデートし，[補足情報を詳しくしました](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf)。Ghostscript が苦手とするタイプの図の話，元のページサイズを維持する場合の処理について加筆。
おそらく正しいと思いますが，なにぶんかなり複雑なので，どこかに認識の誤りがあるかもしれません。

**Comment by aminophen** [comment]
変換経路の図を確認しました。とくに誤りはないと思います。

**Comment by aminophen** [comment]
PDF を Office 2016 で従来どおりとりこめるという話は（私が Office 2016 を持っていないので）確認できていませんが、「EMF の分数とルートの横線が太くなる」という現象は再現しました（下は Illustrator で表示したもの。Word 2011 でも同じ見え方）。

![emf-boldline](https://cloud.githubusercontent.com/assets/9957466/11056997/b79fe2fa-87ca-11e5-8598-f58d3249ba50.png)

[奥村先生のご指摘](https://twitter.com/h_okumura/status/663899681685024768)のほうも備忘録としてここに残しておきます。原因がわからないので対策は保留です。

**Comment by doraTeX** [comment]
原因は概ね想像が付きます。うまく出ている部分は，「パスに囲まれた塗り」の部分です。それに対して太くなっているのは「パスの線」です。「破線の見た目がビューアによって変わる」のを含め，おそらく「EMFの『パスの線』の表示はビューア依存」ということなのでしょう。
これを防ぐにはやはり事前に「パスのアウトライン化」をかけておくのが確実でしょうね。
GhostscriptでEPSを出すときに「パスを使わず塗りだけで表現する」ことができればいいのですが……。

**Comment by doraTeX** [comment]
Windows版TeX2imgのEMF出力をWindows版Officeに取り込んだときはどうなのでしょう？

**Comment by aminophen** [comment]
では、以下のソースを Win / Mac 両方で処理してみます。少々お待ちください。

~~~~ tex
\documentclass[fleqn,dvipdfmx]{jsarticle}
\usepackage{amsmath,amssymb}
\usepackage{tikz}
\pagestyle{empty}
\begin{document}
EMF 出力のテストです。
\[
\left( \int _0 ^\infty \frac{\sin x}{\sqrt{x}} dx \right) ^2
= \sum _{k=0} ^\infty \frac{(2k)!}{2^{2k} (k!)^2} \frac{1}{2k+1}
= \prod _{k=1} ^\infty \frac{4 k^2}{4 k^2 - 1}
= \frac{\pi}{2}
\]
破線のテストです。
\begin{tikzpicture}
\draw[dashed](0,0)--(1,0);
\end{tikzpicture}
\end{document}
~~~~

**Comment by doraTeX** [comment]
こちらでもテストしてみましたら，意外な結果が得られました。

## Illustrator に貼った結果

![2015-11-10 18 02 28](https://cloud.githubusercontent.com/assets/6186180/11058392/e7681fe2-87d5-11e5-8d51-0e440f6ef839.png)

上が改良版 pstoedit による出力，下が Inkscape による出力です。
上はフォント由来でない線の部分が太くにじんでしまっているのに対し，下はEPSやPDFと遜色ない美しさです。

## Word 2011 に貼った場合
![2015-11-10 18 08 42](https://cloud.githubusercontent.com/assets/6186180/11058422/2a0e8cbe-87d6-11e5-8c70-eaf958461fff.png)

やはり上が改良版 pstoedit による出力，下が Inkscape による出力です。
上はフォント由来でない線の部分が太くにじんでしまっているのは相変わらずです。破線の見た目が少し変わっています。

それに対し，Illustrator 上では美しかった下のEMFが，Word 2011 上ではとんでもなくぼけています。
印刷してもこれは同じでした。
Word 2011 / Excel 2011 / PowerPoint 2011 で全て同じでした。
Office 2011 は EMF の扱いが逆に苦手ということでしょうか……？

Inkscape の出力を Office 2016 for Mac に食わせればどうなるかが気になるところですが，未調査です。

出力ファイルを置いておきますので，ぜひWindowsにも食わせてみてください。

* [改良版 pstoedit から出力したEMF](https://dl.dropboxusercontent.com/u/5807100/emf_test/pstoedit.emf)
* [Inkscape から出力したEMF](https://dl.dropboxusercontent.com/u/5807100/emf_test/inkscape.emf)

**Comment by aminophen** [comment]
私も Mac で Illustrator と Office 2011 に貼り付けて、同じ現象に驚きました…

Mac 版 PowerPoint 2011 に貼り付けた結果：
![mac-emftest](https://cloud.githubusercontent.com/assets/9957466/11058716/1a3d409e-87d8-11e5-9746-79e36079a492.png)

Windows 版 PowerPoint 2010 に貼り付けた結果：
![win-emftest](https://cloud.githubusercontent.com/assets/9957466/11058701/f85a0eb2-87d7-11e5-9fd9-faf881371586.png)

Windows 版はこのパターンの破線は偶然(?)うまく処理できるようになっています（abenori さんがオプションを[調節している](https://github.com/doraTeX/TeX2img/issues/56#issuecomment-154761638)ので）。一般にすべての破線が正しく描画される保証はありません。

**Comment by aminophen** [comment]
作成したファイルも[置いておきます](https://dl.dropboxusercontent.com/s/xdvv3o2lpshbubr/emftest-aminophen.zip?dl=0)。

**Comment by doraTeX** [comment]
Macで Win-EMF.emf を使ってみました。

* Office 2011 に貼るとすごく綺麗。ただし Mac-EMF.emf と異なり，背景が透明ではなく白塗りになっている。また，Mac-EMF.emf と比べて Office 上での元のサイズが大きく表示される。
* Illustrator では Win-EMF.emf  をうまく開けない。

**Comment by aminophen** [comment]
> 背景が透明ではなく白塗りになっている

すみません、--transparent を付けるのを忘れていました… その差は無視してください。

> Office 上での元のサイズが大きく表示される。

--scale=10 の影響です。画像のサイズ自体を拡大してあります（そのほうが[ペイントで開いたときに見やすく、端が切れにくい](https://github.com/doraTeX/TeX2img/issues/56#issuecomment-154707337)ので）。

**Comment by doraTeX** [comment]
EMF画像の扱いは難しいですね……
[ここ](http://anago.2ch.net/test/read.cgi/mac/1419600815/989-)に書いてある「emf形式で取り込めばベクター形式で尚且つWindows版とも互換性がある」って大嘘な気がします……。

**Comment by aminophen** [comment]
Windows 環境で作った EMF を Mac の Office 2011 に貼ると：

![mac-emftest-win](https://cloud.githubusercontent.com/assets/9957466/11058828/dd954514-87d8-11e5-81ed-6b5f614b004b.png)

一方、Mac 環境で作った EMF を Windows の Office 2010 に貼ると：

![win-emftest-mac](https://cloud.githubusercontent.com/assets/9957466/11059123/10b276d6-87db-11e5-8899-8217324e8310.png)

あれれ、さっき汚かった Mac-EPS.emf（つまり Inkscape ベースの補助ツール eps2emf.app 使用）が綺麗になっている…

**Comment by doraTeX** [comment]
ということは，Windows 版との互換性が高まったという Office 2016 for Mac なら，Inkscape で出力した EPS が綺麗に表示できるのかもしれませんね。
試したみたいものの，クレジットカード必須の[サブスクリプション契約の体験版](https://products.office.com/ja-jp/try)しかなくて体験しにくいです……。

**Comment by aminophen** [comment]
> Windows 版との互換性が高まったという Office 2016 for Mac なら，Inkscape で出力した EPS が綺麗に表示できるのかもしれませんね。

かもしれません… PDF がとりこめる・とりこめないとか錯綜していて何が正しいのやら、検証したいとは思いますが私の周囲にも Office 2016 はありません…

**Comment by aminophen** [comment]
先ほど作った PowerPoint ファイルを Win と Mac で行き来させてみると、同一ファイルを見ているにもかかわらず Inkscape で作った EMF の表示が綺麗だったり (on Windows) 汚かったり (on Mac) して厄介です。これまたトラブルの原因ですね。

> 「emf形式で取り込めばベクター形式で尚且つWindows版とも互換性がある」って大嘘な気がします……。

まったく同意です。

**Comment by abenori** [comment]
> Illustrator では Win-EMF.emf をうまく開けない。

ちなみに下のequation.emfだとどうなります？

https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

**Comment by doraTeX** [comment]
前のは，

* Office では綺麗に貼れる
* Illustrator で開くと真っ白になった

のですが，今度の equation.emf は，Office でも Illustrator でも開くことすらできませんでした。

![2015-11-10 19 42 22](https://cloud.githubusercontent.com/assets/6186180/11060384/36b3f320-87e3-11e5-8db5-3b57eb7ccee7.png)

**Comment by abenori** [comment]
拡張子をwmfに変えてみるとどうでしょう？

**Comment by doraTeX** [comment]
> 拡張子をwmfに変えてみるとどうでしょう？

状況は同じでした。

**Comment by abenori** [comment]
ありがとうございます．「pstoeditはベジェ曲線が使えない」とかいう話から「もしかして：WMF」と想像したのですが，そういうわけではなかったようです．（先ほどのequation.emfは生成したEMFをWMFに変換して，拡張子だけemfにしたものでした．）

**Comment by doraTeX** [comment]
Office 2016 for Mac を持っている人のMacをちょっとだけ借りることができたので，試してみました。

![2015-11-10 19 30 08](https://cloud.githubusercontent.com/assets/6186180/11060426/7ba14550-87e3-11e5-90a9-fa3dc5e38cfd.png)
![2015-11-10 19 30 15](https://cloud.githubusercontent.com/assets/6186180/11060400/4f2115b4-87e3-11e5-88ac-2bd111f8fc58.png)
![2015-11-10 19 30 23](https://cloud.githubusercontent.com/assets/6186180/11060398/4f1ebcd8-87e3-11e5-9561-b819a08b9159.png)
![2015-11-10 19 30 30](https://cloud.githubusercontent.com/assets/6186180/11060402/4f2514ac-87e3-11e5-93de-68b7f770e345.png)
![2015-11-10 19 30 36](https://cloud.githubusercontent.com/assets/6186180/11060401/4f21ce6e-87e3-11e5-9771-249ccba0880b.png)
![2015-11-10 19 30 44](https://cloud.githubusercontent.com/assets/6186180/11060397/4f1a42e8-87e3-11e5-9334-f5540f786495.png)

## 調査結果

* pstoedit で出力したEMFの表示においてパスが太くなるのは 2011 と同様。
* Inkscape で出力したEMFの表示においてひどくぼやけるのも 2011 も同様。
* EPSの表示はぼやける。（2011では綺麗だった）
* Windows で作成したEMFは綺麗。（2011と同様）
* PDFは，テキスト保持・アウトライン化ともに綺麗。（2011と同様）

というわけで，2011と2016はほとんど変わりませんでした。
違いは，EPSの表示が汚くなったという改悪点だけでしょうか……。

**Comment by aminophen** [comment]
ありがとうございます。Office 2016 でも PDF を綺麗に貼れるらしいことがわかったのが幸いでした。EMF を敢えて選択する必要性がなさそうで良かったです。pstoedit 改変版 eps2emf のほうが（なんか汚いとはいえ）OS 非依存な EMF を作れるので、Inkscape 版 eps2emf.app より気に入っています。

**Comment by doraTeX** [comment]
もう一つ改悪点を見つけました。最新版のKeynoteと同様に，貼り付けたPDF画像のアノテーション情報が削除されるようです。
よって，パワポから画像をコピー＆ペーストすることでTeX2imgにソース復元することができなくなり，貼り付け前のファイルをとっておく必要が生じます。

**Comment by doraTeX** [comment]
結局，幸いにも，Mac版にEMF出力を設けた意義は特になかったということが分かりましたが，まああっても困らないので削除する必要もないでしょう。（例の「斜め書き」みたいなもの？^^;）

**Comment by aminophen** [comment]
#68 の議論で出てきた[期待以上の結果](https://github.com/doraTeX/TeX2img/issues/68#issuecomment-162326263)というのは、[ここ](https://github.com/doraTeX/TeX2img/issues/57#issuecomment-155352404)でおっしゃっていた

> GhostscriptでEPSを出すときに「パスを使わず塗りだけで表現する」ことができればいいのですが……。

だったのですね。なるほどやっと結びつきました。

**Comment by doraTeX** [comment]
その通りです。Ghostscriptで「パスのアウトライン化」をかける方法が見つかった意義は大きいです。
これで見た目がビューアに依存する可能性を極力減らすことができました。

**Comment by aminophen** [comment]
ちなみに、gs9.14 以下でアウトライン化するときも EPS 経由でなく、PostScript の `charpath` あたりでゴニョゴニョすれば PDF to PDF にできるんだと思います。gs9.15 で付いた `-dNoOutputFonts` は実はユーザからの要望を受けて[かなりギリギリのタイミングで追加された](http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=8d3081c0403a1d911a79dce57008ede4279d050a)ものです。これがなくてもゴニョゴニョすればアウトライン化できるわけですが、ユーザが使いやすいインタフェースを用意してくれたにすぎないのです。

**Comment by aminophen** [comment]
アッ、EMF 出力で epstopdf で PDF にいったん戻していた理由が、このスレッドで分かりました… PDF にしたときに bbox がリセットされることを使って左下の余白を確保しているのでした… 右上は余白がなくなるけどしょうがないという話でしたね… うわあ😓

**Comment by doraTeX** [comment]
いえ，現状で大丈夫ですよ。
gs 9.15 以上・未満どちらの過程でも，EMF出力においては，最初の一手で pdfTeX によるクロップ処理が入ります。このとき，余白を含めた左下が MediaBox の原点になり，それがその後のEPSへも受け継がれます。EMFの Office への貼り付けにおいては，変換前EPSの ``%%BoundingBox`` の値に関わらず，EPSの座標系の原点を左下，右上は「図版のギリギリの右上」として描画されます。そのため，左下余白は現状のルーチンで確保できます。（右上余白を確保する方法はなさそうです。）

**Comment by aminophen** [comment]
安心しました… 難しいですね。
