### ISSUE TITLE
CUI版の背景色指定機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#63]
#60 の[議論](https://github.com/doraTeX/TeX2img/issues/60#issuecomment-158254719)から分岐。

> 将来的に CUI で背景色塗りを指定できるようにする場合（Mac 版は計画がありそうな気がするので）> のことをちょっと考えてみました。たとえば背景色指定を
> ~~~~
> --background-color <r g b>
> ~~~~
> などで実装した場合、`--[no-]transparent` との兼ね合い（順序も含めて）がどうあるべきかというとこ ろが論点になると思います。
> 
> + `--transparent` 単独なら？
> + `--background-color <r g b>` 単独なら？
> + `--transparent --background-color <r g b>` なら？
> + `--background-color <r g b> --transparent` なら？
> 
> ということも意見が分かれると思います。#62 でも挙がっていますが、CUI とあまりにもかけ離れないように GUI 検討の段階で UI 整理の方向性を決めたほうがよいのかもしれませんね。

「`--transparent` と `--background-color` は排他で，後から指定した方が先にあった方の効果を（可能な場合）上書きする」という挙動がよいのではないかと思います。

CUI版はデフォルトで `--transparent` 有効の設定ですので，

* 無指定なら → 可能なら背景透過，そうでなければ白色塗り
*  `--transparent` 単独なら →  可能なら背景透過，そうでなければ白色塗り
*  `--no-transparent` 単独なら →  白色塗り
* `--background-color <r g b>` 単独なら → 指定された背景塗り
* `--transparent --background-color <r g b>` なら → `--transparent` は無効化され，指定された色で背景塗り
* `--background-color <r g b> --transparent` なら → 可能なら背景透過，そうでなければ指定された色で背景塗り

いかがでしょう，直観的でしょうか？

あと，`<r g b>` の部分の指定の書式も詰める必要があります。

* 0以上1以下の小数値で指定する
* 0以上255以下の整数値で指定する
* 00以上FF以下の16進値で指定する

などの指定法が考えられます。

**Comment by aminophen** [comment]
まあ CUI 版はそうなるだろうなという印象です。「排他的」はすなわち「GUI で透過のチエックボックスがが有効でも背景色指定はグレーアウトしない；背景色のデフォルトは白」と合致しますね。Win と Mac の完全統一はまったく意図していないのですが、GUI と CUI が乖離してほしくないので。

**Comment by abenori** [comment]
色指定はFF00FFみたいな書式で良いような気がします．それとredとかいくつかの名前をデフォルトで入れておきたいですね．xcolorにあるのをと思ったけど，結構多いなぁ……．

「透明も背景色の一種」という扱いだとどうでしょう．--background-color=transparentという書式を用意して，--transaparentはこれと同等．--transparent-は互換性を考慮に入れると--background-color=whiteが妥当でしょうか．
GUIの方もボタンに「透明」とか書いちゃう．

**Comment by aminophen** [comment]
> 色指定はFF00FFみたいな書式で良いような気がします．それとredとかいくつかの名前をデフォルトで入れておきたいですね．xcolorにあるのをと思ったけど，結構多いなぁ……．

書式は小数だとわかりにくいので16進数に賛成です。デフォルトで名前があると助かりますね。とりあえず color.sty で使えるものから始めて、需要がありそうなら後から足してもよいのではないでしょうか。

> 透過も背景色の一種

まだ GUI が想像ついていないのでなんともいえません… 「透明」を選んだときに JPG は背景が何色になるのかがみえたほうがよいと思うのですが、「透明または白」みたいな表示にするのは収まりが悪いし。その点からは、今の「可能なら」は気に入っています。

**Comment by doraTeX** [comment]
```
--background-color FF00FF
```
の書式に加えて，Photoshop スタイルの 

```
--background-color "255 119 225"
```

のような指定もできるようにしておくと分かりやすいのではと思いました。
クオート必須になってしまうのが難点ですが。

![2015-11-21 22 55 46](https://cloud.githubusercontent.com/assets/6186180/11318765/2ccf5070-90a3-11e5-92de-281fca0f8d36.png)

```

**Comment by abenori** [comment]
> 「透明」を選んだときに JPG は背景が何色になるのかがみえたほうがよいと思うのですが、

ボタンを白くして，「透明」とボタン名をつけるとか？設定は悩みますが，カラーダイアログに「透明」っていうチェックボックスを入れるのが良いでしょうか．

しかし，透明ってのは色の種類ではない（青い透明だってある）ので，概念的に良くない気もしてきました．

**Comment by aminophen** [comment]
> カラーダイアログに「透明」っていうチェックボックスを入れるのが良いでしょうか．

透過か非透過かは（私の場合は）設定を変える頻度が高い部類に入るので、カラーダイアログに入れ込まれるとちょっと面倒になります。（そういってしまうと既に「透明が色の一つ」とは相容れないわけですが…）

> 透明ってのは色の種類ではない（青い透明だってある）ので，概念的に良くない気もしてきました

「透過指定の有無」と「背景色指定」が独立だと“青い透明”と思われかねないので、色ボタンをグレーアウトさせるのはやっぱり正解でしょうね（Mac 版でこの解釈を避けるにはどうすればよいのだろう…）。全ての画像が透過可能なら話は簡単でいまの Win 版の状態で良いと思うのですが、JPG のわかりにくさがネックになっています。やっぱり GUI は色指定ボタンをグレーアウトさせる今の状態で「可能なら；不可能な場合は白」と書き加えるのが簡単だと思いました。

> クオート必須になってしまうのが難点ですが。

これは既に `--margins` がその書式を使っているのでアリだと思います（引数 1, 2, 4 個を許容し、2, 4 ならクオート必要）。16進数 00..FF より10進数 0..255 のほうがわかりやすい人もいると思いますし、案自体には賛成です。むしろ問題は「FF00FF のように16進数なら…」「10進数の3つの番号をクオートで渡せば…」という仕様をヘルプで説明する難しさでしょうか？

**Comment by abenori** [comment]
むしろ「青い透明」を避けるために，ユーザに「透明は色の一つ」と見なすようにさせよう，という意図でした．これが意識されれば「青」と「透明」は同時には存在し得ない野で，「青い透明」はあり得ません．
とここまで書いて，「透明」じゃなくて「透過」だったことを思い出しました．「透過」ならば概念的にも良いかも？

>  --transparent --background-color <r g b> なら → --transparent は無効化され，指定された色で背景塗り

というのはそういう方向かなと思ったので．

> 透過か非透過かは（私の場合は）設定を変える頻度が高い部類に入るので、カラーダイアログに入れ込まれるとちょっと面倒になります。

これは別件といえば別件ですが，使用頻度が高そうなのはメニューにも表示させても良いかもしれません．といっても透過くらいかもしれませんが……

**Comment by doraTeX** [comment]
>> クオート必須になってしまうのが難点ですが。
>
> これは既に --margins がその書式を使っているのでアリだと思います（引数 1, 2, 4 個を許容し、2, 4 ならクオート必要）。16進数 00..FF より10進数 0..255 のほうがわかりやすい人もいると思いますし、案自体には賛成です。むしろ問題は「FF00FF のように16進数なら…」「10進数の3つの番号をクオートで渡せば…」という仕様をヘルプで説明する難しさでしょうか？

こんな感じでどうでしょうか？

```
  --background-color COLOR   : set the background color (default: enabled)
   *COLOR format examples:
      FF00FF      : CSS-style HEX format
      "255 0 255" : RGB integers (0..255)
```

**Comment by aminophen** [comment]
> むしろ「青い透明」を避けるために，ユーザに「透明は色の一つ」と見なすようにさせよう，という意図でした．これが意識されれば「青」と「透明」は同時には存在しえないので，「青い透明」はあり得ません．

青と透過は同時に存在し得ないことを意識してもらうなら、確かに透過も色の一つとみなすのがよいですね（いまちょっと青いセロハンを透過する光が青というような「物理的な透明」と、青を透過色に選択して PNG アルファチャネルを指定するような「画像処理的な色透過」に両方が頭をよぎったのですが、色の一つとみなす仕様だとどちらも起きないはず）。そのうえで「よく使うものを UI で表に出す」という案との両立ができたら良さそうです。

> こんな感じでどうでしょうか？

おお、分かりやすいです。あとはデフォルトの色をどのくらい用意するかでしょうか？（white, red, etc. transparent も色の一つとして含めるか？）

**Comment by abenori** [comment]
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

「透過も色の一つ」というのに従い，内部では「背景色」のみを持っていると思ってください．
* --background-colorはこの背景色を切り替えます．
* --transparentはこの背景色を「透過」にします．
* --transparent-はこの背景色を白にします．
* GUIのカラーダイアログは--background-colorと同じ．
* GUIの透過ボタンをONにすることは--transparentと同じ．
* GUIのボタンには「背景色」を表示する．従って「透過」の時はその旨を表示する．（実際には白背景に透過と書いてみている．）

この流れだとGUIの透過ボタンをOFFにするのは--transparent-と同じが自然ですが，実際には「透過にする直前の色」を復帰させるようにしています．

「透過」「背景色」を分離させるよりいい気がしてきました．もし分離させるならば，内部には「背景色」と「透過フラグ」があり，
* --background-colorは背景色を切り替えます．
* --transparent[-]は「透過フラグ」をON/OFFします．
* GUIのカラーダイアログは--background-colorと同じ．
* GUIの透過ボタンをON/OFFにすることは--transparent[-]と同じ．
* 実際の背景色は，透過がONならば透過or白，そうでなければ背景色となる．
* 従って--transparent --background-color=redとすると「透過か白」となる．
* 背景色設定ボタンは透過にかかわらず背景色を表示する．

となるでしょうか．

 > あとはデフォルトの色をどのくらい用意するかでしょうか？

HTML色を解釈できるようだったので，それに突っ込んでみました．たぶん
https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A7%E3%83%96%E3%82%AB%E3%83%A9%E3%83%BC#X11.E3.81.AE.E8.89.B2.E5.90.8D.E7.A7.B0
あたりのが使えるのではないかと思いますが．

**Comment by doraTeX** [comment]
[TeX2img for Mac Ver. 2.1.2 beta 1](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.2b1.zip) を作成しました。

# Ver. 2.1.1 → 2.1.2 beta 1 の新機能
## 背景色関係

* 背景色選択・透過のUIを #62 のように整理
* CUI版：新オプション `--background-color` を追加
```
  --background-color COLOR   : set the background color (default: white)
   *COLOR format examples:
      magenta     : CSS-style color name
      FF00FF      : CSS-style HEX format
      "255 0 255" : RGB integers (0..255)
```

  * `CSS-style color name` の名称は，[CSS に規定された141種類の名称](http://www.w3schools.com/cssref/css_colornames.asp)に対応。
  * [最近新しく増えた](http://it.srad.jp/story/14/06/24/0149232/) RebeccaPurple にも対応。
  * `CSS-style color name`, `CSS-style HEX format` いずれも，大文字・小文字は区別しない。

## 作業ディレクトリ指定機能

* GUI版：環境設定→変換ツール の中に「入力ファイルと同じフォルダ上で作業する（外部ファイル入力時）」というチェックボックスを追加
* CUI版：新オプション `--workingdir` を追加

```
  --workingdir DIR           : set the working directory (tmp|file|current) (default: tmp)
   *DIR values:
      tmp            : Standard user temporary directory ($TMPDIR)
      file           : The same directory as the input file
      current        : Current directory
```

## 既知の制約

作業ディレクトリとして $TMPDIR 以外を指定できるようになった結果，作業ディレクトリのパスにスペースが含まれる可能性が生じるようになりました。その場合の対策は不十分です。

**Comment by aminophen** [comment]
> 「透過も色の一つ」というのに従い，内部では「背景色」のみを持っていると思ってください．
> 
> [...]
> 
> この流れだとGUIの透過ボタンをOFFにするのは--transparent-と同じが自然ですが，実際には「透過にする直前の色」を復帰させるようにしています．

Windows 版を動かしてみました。GUI はこれでわかりやすいです。

![tex2imgwin168beta-bgcolor-onandoff2](https://cloud.githubusercontent.com/assets/9957466/11338603/6de2f184-9238-11e5-8ba7-02681e02e393.png)

「GUIの透過ボタンをOFFにするのは…」のところが若干気になります。`--transparent-` を白に固定する必要はないかなと思います。そのほうが GUI とも相性がよいです。

**Comment by aminophen** [comment]
Mac 版 beta 2.1.2 beta 1 を試しました。CUI 版で RGB の値を指定した場合に Abort trap 6 で落ちました。他の指定法は設計どおりになっているようです。

~~~~
 $ tex2img --background-color "0 1 0" source.tex out.png
2015-11-24 12:26:54.038 tex2img[870:707] +[NSColor colorWithRed:green:blue:alpha:]: unrecognized selector sent to class 0x7fff7c974c10
2015-11-24 12:26:54.039 tex2img[870:707] An uncaught exception was raised
2015-11-24 12:26:54.040 tex2img[870:707] +[NSColor colorWithRed:green:blue:alpha:]: unrecognized selector sent to class 0x7fff7c974c10
2015-11-24 12:26:54.040 tex2img[870:707] (
	0   CoreFoundation                      0x00007fff96952f56 __exceptionPreprocess + 198
	1   libobjc.A.dylib                     0x00007fff8efa2d5e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff969df0fe +[NSObject doesNotRecognizeSelector:] + 190
	3   CoreFoundation                      0x00007fff9693fe23 ___forwarding___ + 371
	4   CoreFoundation                      0x00007fff9693fc38 _CF_forwarding_prep_0 + 232
	5   tex2img                             0x0000000106624afa generateConverter + 5709
	6   tex2img                             0x0000000106626276 main + 38
	7   tex2img                             0x00000001066136dc start + 52
)
2015-11-24 12:26:54.041 tex2img[870:707] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSColor colorWithRed:green:blue:alpha:]: unrecognized selector sent to class 0x7fff7c974c10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff96952f56 __exceptionPreprocess + 198
	1   libobjc.A.dylib                     0x00007fff8efa2d5e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff969df0fe +[NSObject doesNotRecognizeSelector:] + 190
	3   CoreFoundation                      0x00007fff9693fe23 ___forwarding___ + 371
	4   CoreFoundation                      0x00007fff9693fc38 _CF_forwarding_prep_0 + 232
	5   tex2img                             0x0000000106624afa generateConverter + 5709
	6   tex2img                             0x0000000106626276 main + 38
	7   tex2img                             0x00000001066136dc start + 52
)
terminate called throwing an exception
Abort trap: 6
~~~~

**Comment by doraTeX** [comment]
ご指摘ありがとうございます。修正した [Ver. 2.1.2 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.2b2.zip) を用意しました。

**Comment by aminophen** [comment]
Ver. 2.1.2 beta 2 で、なんだかよくわからないのですが `--background-color "60 120 180"` を指定すると Settings に

~~~~
Background color: #4E8DBF (R=78, G=141, B=191)
~~~~

と出ています。これでよいのかどうかよくわかりません…

**Comment by doraTeX** [comment]
> これでよいのかどうかよくわかりません…

よくないですね……😓
[Ver. 2.1.2 beta 3](https://dl.dropboxusercontent.com/u/5807100/tex2imgcMac2.1.2b3.zip) を作りました。今度こそ大丈夫では。

**Comment by aminophen** [comment]
Ver. 2.1.2 beta 3 は大丈夫でした。古い OS への対応、ありがとうございます。色指定の種類っていろいろあるのですね。

**Comment by aminophen** [comment]
毎度で申し訳ないのですが、微妙に作業ディレクトリ指定の UI が切れています… あと、「コンパイル後処理」の画面の「作業フォルダを開く」が「一時フォルダを開く」のほうがよいと思います。

![tex2imgmac212b1-workingdir](https://cloud.githubusercontent.com/assets/9957466/11358428/18501d3c-92b5-11e5-9f7f-49463520b5cf.png)

作業フォルダを選択するチェックボックスの配置場所が「変換ツール」タブにあることで、見つけやすくてよいと思いました。確かに「コンパイル後」でないのでそのほうが合致します。

**Comment by doraTeX** [comment]
[Ver. 2.1.2 beta 4](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.2b4.zip) を作りました。

* 「作業する」の「する」を抜いて短くしました。
* 「作業フォルダを開く」を「一時フォルダを開く」に修正しました。
* 英語版GUIで a Adobe Illustrator document となってしまっていたので冠詞を an に修正しました😓
* 作業フォルダのパスにスペースが含まれる場合への対処を行いました。

**Comment by aminophen** [comment]
Ver. 2.1.2 beta 4 は問題ないようです。「作業フォルダのパスにスペースが含まれる場合」も大丈夫でした。

**Comment by abenori** [comment]
--transparent-で白くするのは

 > --no-transparent 単独なら → 白色塗り

というのとあわせたのと，あまり御利益がないかなと思ったからです．むしろ--transparent-をしたときに何色になるのか予想できないケースの方が多いかと思いました．デメリットの方が多いかと思っています．白以外を指定したいときにはおとなしく--background-colorでやってもらえば良いかと．

**Comment by doraTeX** [comment]
[CUI版 Ver. 2.1.2 beta 5](https://dl.dropboxusercontent.com/u/5807100/tex2imgcMac2.1.2b5.zip) を作りました。

* `--background-color "#FF00FF"` のように，CSS風に `#` 付きでも受け付けるようにしました。（この場合はシェルに解釈されるのを防ぐためクオート必須）
* `--background-color F0F` のようなCSSの16進3桁指定も受け付けるようにしました。CSSにならい，`#F0F` は `#FF00FF` と解釈されます。

**Comment by aminophen** [comment]
> --transparent-で白くするのは
> 
> > --no-transparent 単独なら → 白色塗り
> 
> というのとあわせたのと，あまり御利益がないかなと思ったからです．

Mac 版は CUI が別なので、単にそれは「デフォルト値の白」が出てくるだけなのだと思います。だから[エイリアスでデフォルト値を変え](http://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeX2img%20FAQ#i77b89d8)れば、むしろ見た目上 Win 版の「設定ファイルに書かれている値が使われる」に対応します。

> むしろ--transparent-をしたときに何色になるのか予想できないケース

は単に「現在：ナントカ」で出て解りますので、それで困れば `--load-defaults` を使えます。むしろ「設定ファイルは赤背景＋透過フラグ ON」の状態で、透過だけキャンセルする方法が欲しい場合が多いと予想しました。

**Comment by abenori** [comment]
前の実装は「内部には背景色のみがあり，透過はその色の一つ」という扱いだったので

> 単に「現在：ナントカ」で出て解りますので、

では「transparent」とか出るようにしていたと思いますが，

> むしろ「設定ファイルは赤背景＋透過フラグ ON」の状態で、透過だけキャンセルする方法が欲しい場合が多いと予想しました。

ということは，背景色＋透過フラグでの管理が良いと言うことですね．だとすると

https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

となるでしょうか．--background-colorの現在の値がFF00FF 透過とか出るのが判断に迷いそうではあります．

**Comment by aminophen** [comment]
Ver.2.1.2b5 を確認しました。どちらの指定も正常でした。実行直後に出てくる `{0, 6}` というのはデバッグコードですね。

**Comment by aminophen** [comment]
Win 版は前におっしゃっていた

> もし分離させるならば，内部には「背景色」と「透過フラグ」があり，

になったということですね。透過のチェックボックスがある以上、完全に統合するのは難しいように思えたので、別のフラグがあるほうが逆に自然です。今度は GUI と CUI が同じになった気がします。

**Comment by doraTeX** [comment]
[CUI版 Ver. 2.1.6 beta 6](https://dl.dropboxusercontent.com/u/5807100/tex2imgcMac2.1.2b6.zip) を作りました。

* 余計なデバッグメッセージを消去しました。
* `--background-color "255 255 255"` 形式の指定において，指定された値のエラーチェックが不十分でしたので，0～255 以外の値が指定されたときにエラーを表示するようにしておきました。

**Comment by aminophen** [comment]
CUI版 Ver. 2.1.6 beta 6

~~~~
error: --background-color is invalid. Each RGB value must be less than 256.
~~~~

これでもう大丈夫ですね！

**Comment by doraTeX** [comment]
ではそろそろリリース作業に入りましょうかね！😏

**Comment by doraTeX** [comment]
* GUI版で「入力ファイルと同じフォルダ上で作業」のチェック状態が保存されない不具合があったので修正。
* Snow Leopard 版には，作業フォルダ指定機能(`--workingdir`)は追加し，背景色指定機能(`--background-color`)は追加しないことにします。

**Comment by aminophen** [comment]
Win 版の 1.6.8 をダウンロードしたのですが、背景色がなぜか全く付かなくなっているみたいです。

**Comment by abenori** [comment]
ありゃ，失敗しました．こっそり直しました．

なんかそれでやってみたら，epsをPS_Viewで見たらでかく表示されてしまっているようです．BoundingBoxは正しく入っているように見えるのですが……

**Comment by aminophen** [comment]
PS_View と GSview はバウンディングボックスの外側まで描画する仕組みになっているっぽいです（BoundingBox 行を無視してクロップ前の A4 サイズを表示したかのように塗る）。ちなみに Inkscape で開いてもまた違った見え方になります（これは左下だけバウンディングボックスに合わせて右上はだだっ広く A4 サイズ分塗って表示）。ビットマップ画像にすると正しくクロップされているのは、バウンディングボックスがちゃんと描かれている証拠だと思います。

**Comment by abenori** [comment]
そうすると塗る範囲をきちんと取得したBoundingBoxに併せておいた方が良さそうですね．後でやっておきます．

**Comment by aminophen** [comment]
Windows 版は「TeX → … → PDF →[必要なら塗る (pdfTeX)]→ PDF →[gs or pdfTeX]→ …」になっているのですね。どこで塗っているのかよく分かっていませんでした… この塗る作業は現状では[元サイズに合わせて `0 0 x y` で塗っている](https://github.com/doraTeX/TeX2img/issues/60#issuecomment-157212735)ので、これを BoundingBox に合わせて `x1 y1 x2 y2` にすればよいわけですね。なるほど。

**Comment by abenori** [comment]
一応今の段階のをtex2img_generate.pdfに書いてみました．（寺田くんのと違ってきれいでなくてすみません……．）

https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

**Comment by abenori** [comment]
せっかくなので「透明の青」もやってみようかと思って次のようなソースをかけてみました．

    %#! pdflatex
    \documentclass{article}
    \begin{document}
    \pdfpageresources{/ExtGState<</TRP<</ca 0.5>>>>}
    \pdfliteral{q 0 0 0 rg n /TRP gs 0 0 100 100 re f Q}
    aiueo
    \end{document}

なんだか変です……Ghostscriptがやたら遅いし，EPSを作るとPS_Viewで開いても変です．

**Comment by aminophen** [comment]
> Ghostscriptがやたら遅いし，EPSを作るとPS_Viewで開いても変です．

gs9.16 で試してみました。確かにアウトライン化されていませんね。[TikZ の shadows ライブラリを含む場合にアウトライン化に失敗する](https://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeX2img%20FAQ#lb8a48e0)と同じ現象が起きている気がします。

**Comment by aminophen** [comment]
どうやら gs9.15 以降で pdfwrite にも新設された `-dNoOutputFonts` を使えば、[半透明でもアウトライン化できる](http://d.hatena.ne.jp/acetaminophen/20151129/1448787127)ようです。eps(2)write はとにかく半透明が苦手な模様です。

**Comment by doraTeX** [comment]
なるほど，TikZの shadows ライブラリを含む場合など，半透明のサポートを考えると，[変換経路図](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf) の右のエリアにある「途中に eps2write を経由しているが最終出力がEPSではない場合」については，pdfcrop類似処理 + pdfwrite + NoOutputFonts のコンボにするのがよいということになるでしょうかね。

**Comment by aminophen** [comment]
> 変換経路図 の右のエリアにある「途中に eps2write を経由しているが最終出力がEPSではない場合」については，pdfcrop類似処理 + pdfwrite + NoOutputFonts のコンボにするのがよいということになるでしょうかね。

「gs9.15 以上」かつ「現状で途中に eps2write を経由」かつ「最終出力が EPS ではない」の場合に pdfwrite の `-dNoOutputFonts` で処理すると、処理が格段に速くなるのは確かです。「背景色を半透明にできるように」はさておき、TikZ の shadows がアウトライン化できない事態はなんとかしたいというのであれば、この方法を使えばよいのでしょうね。しかし、また大規模改修と大規模なテストが必要な予感…
