### ISSUE TITLE
非アニメーションSVG生成時にGhostscriptによるPDFアウトライン化を行う経路を設ける

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#69]
[変換経路図](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf) に現れているように，

* 非アニメーションSVG生成時は mudraw がPDFのアウトライン化を行い，テキストも埋め込む
* アニメーションSVG生成時は，まずは pdfwrite でPDFのアウトライン化を行った上で mudraw にかける（その結果テキストを保持しないSVGになる）

となっています。
「非アニメーションSVG生成時にも pdfwrite にかける」という経路を用意しておいた方が安全ではないかという気がしてきました。

「テキストを保持する」(`--with-text`) をSVGにも適用させるようにし，PDFと同様，このオプションの状態に応じて変換経路を分けるのがよいのでは。（Windows版は既にそうなっている？）

**Comment by abenori** [comment]
> （Windows版は既にそうなっている？）

今出している1.6.8はなっていないです．手元の新しいやつはそうしています．
