### ISSUE TITLE
pdftopsを通す「プレーンテキストのEPS出力」時にアウトラインがとられていない / 半透明が含まれるページ以降を eps(2)write で処理すると汚くなる

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#70]
[変換経路図](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf)に反して，pdftopsを通す「プレーンテキストのEPS出力」を行うと，pdfwrite によるアウトライン化を行わずにEPS変換に進んでしまっている。変換の実装が誤っているので修正すべき。

**Comment by aminophen** [comment]
テキスト形式 EPS 出力でもう一つ問題を見つけました。途中の「pdfTeX でクロップ＋余白追加したことで生き残った白紙ページの temp***-trim.pdf を gs9.16 の pdfwrite によるアウトライン化にかける段階」で警告が出ます。

~~~~
$ /usr/local/bin/gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dNoOutputFonts -r2160 -sOutputFile=temp-pdfwrite.pdf -dFirstPage=1 -dLastPage=1 -dAutoRotatePages=/None -c .setpdfwrite -f temp-trim.pdf 2>&1
Processing pages 1 through 1.
Page 1
   **** Warning:  File has an empty MediaBox. Using the current page size instead.
   **** Warning:  File has an empty MediaBox. Using the current page size instead.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> pdfTeX-1.40.16 <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
~~~~

この結果、クロップしたはずなのにページが A4 サイズに戻されてしまいます。

**Comment by aminophen** [comment]
gs9.16 で試していますが、アウトライン化した PDF の場合は

+ gs(bbox)：bbox 取得
+ pdfTeX：バラバラ＋クロップと余白付与
+ gs(pdfwrite-nooutputfonts)：アウトライン化

で警告なし。ということは、アウトライン化したテキスト EPS の場合も

+ gs(bbox)：bbox 取得
+ pdfTeX：**バラバラ＋**クロップ＋余白付与
+ gs(pdfwrite-nooutputfonts)：~~バラバラ＋~~アウトライン化
+ pdftops

でいいのではないでしょうか？

**Comment by aminophen** [comment]
Ver. 2.1.4 beta 4 で直りました。ありがとうございます。

**Comment by aminophen** [comment]
gs9.05 で実験したところ、EPS 出力時に余白0で「TeX2img: [警告] 1, 3, 5 ページ目が空白ページであったためスキップしました。」といいながら真っ白な EPS を吐いていることに気づきました…

**Comment by doraTeX** [comment]
手元の gs 9.10 ではそれを再現することができておりません……。
他のパラメータに依存している可能性もあります。
CUI版でも再現するでしょうか。再現できる場合はそのインプットファイルとCUIオプションの状態をお願いいたします。

一カ所，それとは直接の関係はないかもしれませんが，「単一ファイルにまとめる」のチェックボックスの状態のON/OFFが，単一ファイルにまとめられない出力形式の場合の作業ファイルの削除の仕方にも影響を及ぼしている不具合を見つけましたので，そこを修正した [Ver. 2.1.4 beta 5](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.4b5.zip) を作りました。
こちらで改めてお試しください。

**Comment by aminophen** [comment]
> 単一ファイルにまとめられない出力形式の場合の作業ファイルの削除の仕方

確かにそのバグも先ほど見つけましたが、それとは別でした。Ver. 2.1.4 beta 5 でも

~~~~
./tex2img --workingdir=current --quick --margins 0 --background-color 00CC88 "sam ple.tex" "a b.eps"
~~~~

で起きます。Quartz の背景色塗りが例外処理できていなくて、起きてその先に進むようです。

**Comment by doraTeX** [comment]
[Ver. 2.1.4 beta 6](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.4b6.zip) で対処できたと思います。

**Comment by aminophen** [comment]
> Ver. 2.1.4 beta 6 で対処できたと思います。

直りました。ありがとうございます。

 # 全然テストが終わらない…😱

**Comment by aminophen** [comment]
gs9.05 でアウトライン化 PDF を出力すると「ほげほーげ」より後の全てのページが汚くなることを見つけました。汚くなくていいはずの数式のページも汚くて、原因が全く分かりません…

**Comment by doraTeX** [comment]
> ちなみに test.sh がそのままだと VMError で落ちるので、この部分が検証できませんでした

gs 9.15 未満で実験する際には，`sam ple.tex` の 「ほげほーげ」のページはコメントアウトして実験していましたので，この問題には気づいていませんでしたが，本当ですね。

不思議なことに，この現象は，事前にPDFを1枚ずつpdfcrop類似処理で砕いておいてもなお発生します。
元々「shadowsがある以降のページ」であったページは，たとえその後バラバラに砕いても，何かその名残が残っているのか，epswrite の結果が汚くなりますね。

これは gs のバグとして放置するということでよいのではないかと思います。

**Comment by aminophen** [comment]
> これは gs のバグとして放置するということでよいのではないかと思います。

そうしましょう。

**Comment by aminophen** [comment]
gs9.05 の EMF 出力で、白紙ページがそのまま出てくるようです。背景が透過でも塗りでも、余白が0なら起こります。epswrite が次の警告を出しています：

~~~~
   **** Warning:  File has an empty MediaBox. Using the current page size instead.
   **** Warning:  File has an empty MediaBox. Using the current page size instead.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> pdfTeX-1.40.16 <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
~~~~

**Comment by doraTeX** [comment]
[2.1.4 beta 7](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.4b7.zip) で修正できたと思います。

**Comment by aminophen** [comment]
beta 7 は大丈夫でした。ちまちま粗探ししているようでなんだかすみません😥 gs9.14 以下のスキームが複雑すぎて、把握するのに手間取っているもので…

**Comment by doraTeX** [comment]
いえいえ，きめ細かいチェック，大変助かります m(__)m

**Comment by aminophen** [comment]
いちばん謎なのが gs9.15 未満の赤い波線の経路です…「非透過アウトライン化 PDF」を経由する画像だけいったん pdfTeX を通す理由がわかっていません… ほかは意図がなんとなく読み取れるのですが。

**Comment by doraTeX** [comment]
Quartz API で背景塗りをするときは，

1. ファイルからPDFデータを読み込む
1. 背景を塗る
1. データをPDFとして書き込む

という動きをするのですが，3. において，ページごとにMediaBoxの大きさが異なるPDFを書き出すことができないようなのです。それゆえ背景塗りを行う前に，PDFをページごとにバラバラに砕いています。

**Comment by aminophen** [comment]
ありがとうございます。[先ほどの「ほげほーげ」以降が全て汚くなる件](https://github.com/doraTeX/TeX2img/issues/70#issuecomment-162500813)をもう少し調べると

- `./tex2img --quick --background-color 00CC88 "sam ple.tex" abc.pdf` は汚い
- `./tex2img --quick --background-color 00CC88 "sam ple.tex" abc.eps` は Distiller で PDF にすると綺麗
- `./tex2img --quick "sam ple.tex" abc.pdf` は汚い
- `./tex2img --quick "sam ple.tex" abc.eps` は Distiller で PDF にしても汚い

という挙動を示します。さきほど

> たとえその後バラバラに砕いても，何かその名残が残っているのか，epswrite の結果が汚くなりますね。

とおっしゃっていましたが、背景色塗りを入れた EPS だけ綺麗になります。なにか変換経路と関係ありますでしょうか？

**Comment by doraTeX** [comment]
余白なしなら，

* 透過EPS：pdfcrop類似処理でページごとにばらす → epswrite
* 非透過EPS：pdfcrop類似処理でページごとにばらす  → Quartz APIで背景塗りしたPDFを保存 → epswrite 

という経路の違いとなります。

透過EPSの場合，epswrite が処理する対象は「pdfTeXによってページごとにばらされたPDF」であるのに対し，非透過EPSの場合，「Quartz API が保存したPDF」になります。

先程の

> たとえその後バラバラに砕いても，何かその名残が残っている

という仮説に基づいてさらに推測すると，

「Quartz API でPDFを保存し直すと，その『名残』が消える『PDFロンダリング』が行われる」

という仮説を立てることができます。

**Comment by doraTeX** [comment]
このロンダリング仮説に基づけば，

> `./tex2img --quick --background-color 00CC88 "sam ple.tex" abc.pdf` は汚い

は，次のように説明できます。

* 余白なしアウトライン化PDF：pdfcrop類似処理でページごとにばらす → epswrite → epstopdf → Quartz API で背景塗りしたPDFを保存

という経路になります。
これは epswrite によってロンダリング前のPDFのアウトライン化が行われて「汚さが確定」してしまうため，後から Quartz API 保存してもロンダリングできない，と説明することができます。

**Comment by aminophen** [comment]
> Quartz API でPDFを保存し直すと，その『名残』が消える『PDFロンダリング』が行われる」

それはありえますね。一度試してみる価値はあると思います。（仮にその方法が成功すれば、gs あるいは pdfTeX で何かまたフィルタを見つければ回避できるかも！？）

**Comment by doraTeX** [comment]
そのためには，透過ベクター画像を出力する場合にも，まずは赤波線の経路を通し，pdfcrop類似処理にかけてPDFをページごとにばらす必要がありますね。

**Comment by aminophen** [comment]
> 透過ベクター画像を出力する場合にも，まずは赤波線の経路を通し，pdfcrop類似処理にかけてPDFをページごとにばらす必要がありますね。

確かに。「半透明のページ以降の描画が綺麗になるようにする」というモチベーションは大きいです。まだ gs9.15 未満の経路は最適化の余地があるということですね。

**Comment by aminophen** [comment]
> まだ gs9.15 未満の経路は最適化の余地があるということですね。

gs9.15 以上の eps2write もやはり同じ問題が発生するようです。「EPS 透過」を出力するときが該当しますね。こちらも一律に pdfTeX にかけたほうがよさそうです。

**Comment by doraTeX** [comment]
eps(2)write 実施前にPDFロンダリングを行うようにしてみました。
ここまでに挙がってきた「汚い出力」のパターンはつぶせたように見えますが，いかがでしょうか。
[Ver. 2.1.4 beta 8](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.4b8.zip)

**Comment by aminophen** [comment]
beta 8 は明日にでも試します…

Quartz が有効ということは、なにか鍵になるフィルタがあるのだと思います。半透明より後のページを

1. Quartz を通さずに gs9.10 でアウトライン化した場合
2. Quartz を通してから gs9.10 でアウトライン化した場合

の EPS か、もしくは Quartz を通す前後の PDF をいただければ、中身を読んで違いを見つけられると思います。解析する価値はあります。

**Comment by doraTeX** [comment]
[テストファイル一式](https://dl.dropboxusercontent.com/u/5807100/PDFlaunderingTest.zip) を用意しました。

* `original.pdf` : 元のPDF
* `gs907-epswrite.eps`: `original.pdf` の7ページ目を gs 9.07 の epswrite で切り出したもの
* `gs918-eps2write.eps`: `original.pdf` の7ページ目を gs 9.18 の eps2write で切り出したもの
* `page7-beforeLaundering.pdf` : `original.pdf` の7ページ目を pdfTeX で切り出したもの
* `page7-afterLaundering.pdf` : `page7-beforeLaundering.pdf` を Quartz API で開いて再保存したもの
* `gs907-beforeLaundering.eps` : gs 9.07 で `gs -dNOPAUSE -dBATCH -dAutoRotatePages=/None -r2160 -sOutputFile=gs907-beforeLaundering.eps -dFirstPage=1 -dLastPage=1 -sDEVICE=epswrite -dNOCACHE page7-beforeLaundering.pdf` としたもの
* `gs907-afterLaundering.eps` : gs 9.07 で `gs -dNOPAUSE -dBATCH -dAutoRotatePages=/None -r2160 -sOutputFile=gs907-afterLaundering.eps -dFirstPage=1 -dLastPage=1 -sDEVICE=epswrite -dNOCACHE page7-afterLaundering.pdf` としたもの
* `gs918-beforeLaundering.eps` : gs 9.18 で `gs -dNOPAUSE -dBATCH -dAutoRotatePages=/None -r2160 -sOutputFile=gs918-beforeLaundering.eps -dFirstPage=1 -dLastPage=1 -sDEVICE=eps2write -dNoOutputFonts -dCompressPages=false -dASCII85EncodePages=true page7-beforeLaundering.pdf` としたもの
* `gs918-afterLaundering.eps` : gs 9.18 で `gs -dNOPAUSE -dBATCH -dAutoRotatePages=/None -r2160 -sOutputFile=gs918-afterLaundering.eps -dFirstPage=1 -dLastPage=1 -sDEVICE=eps2write -dNoOutputFonts -dCompressPages=false -dASCII85EncodePages=true page7-afterLaundering.pdf` としたもの

Quartz API によるロンダリング仮説がますます実証されてきています……。

**Comment by aminophen** [comment]
beforeLaundering の PDF には `/Group<</S/Transparency/CS/DeviceGray>>` が登場していて、 afterlaundering の PDF には登場していないのがチョット怪しいです。

**Comment by doraTeX** [comment]
[こちらです](https://dl.dropboxusercontent.com/u/5807100/PDFlaunderingTest2.zip)。

**Comment by aminophen** [comment]
Quartz 前後の EPS を比べると、page 4 同士はほぼ変化なし・page 6 同士は両方とも“汚さ”が同等ですね。page 7 以降だけが Quartz 前後で EPS に大きな変化が表れているということです。

先ほどの指摘はビンゴでした。PDF の中を見ると

- page 4 は before / after ともに `/Transparency` オペレータが存在しない
- page 6 は before / after ともに `/Transparency` オペレータが存在する
- page 7 は before には `/Transparency` オペレータが存在するが、after には存在しない

このオペレータの存在がカギになるようなにおいです。さて、Quartz の代替が pdfTeX にできるでしょうか？（仮にできれば「ページをばらしながらロンダリングする」という処理ができ、Win / Mac ともに有用そう）

**Comment by aminophen** [comment]
gs の pdfwrite を通すだけで Quartz と同じことができますね。

~~~~
$ gs -sDEVICE=pdfwrite -dBATCH -dNOPAUSE -sOutputFile=out.pdf -c .setpdfwrite -f in.pdf
~~~~

これだけで「半透明が実在するページは現状維持（`/Transparency` を残す）」「半透明が実在しないページは `/Transparency` を排除」が可能です。ただ、問題点はやっぱり gs が縦書き CJK を苦手とすることです。pdfwrite をテキスト保持 PDF に通してしまうとグリフの位置が乱れてしまい、嬉しくありません。なんとか pdfTeX でやりたいですね…

**Comment by doraTeX** [comment]
なるほど，調査ありがとうございます。
お陰様で，色々合点がいきました。

[以前書いた](https://github.com/doraTeX/TeX2img/issues/66#issuecomment-160493384)ように，Preview.app は半透明PDFの表示を苦手としています。
これと根が同じと思うのですが，Quartz API は，

* PDF 1.3 準拠
* 半透明PDFの取り扱いは苦手

という仕様のようです（明文化した仕様が見つからないのですが……）。

Page 6 の影の部分が，変換経路によって維持されたり失われたりするのを怪訝に思っていたのですが，途中で Quartz API を経由する経路だった場合に `/Transparency` が失われる，ということだったのですね。動きが理解できました。

> まさか Quartz も縦書き PDF が苦手ということはないですよね…？（もし苦手だったら背景塗りから pdfTeX でやり直さないといけないことになってしまう…）

少なくとも El Capitan なら大丈夫なようです。PDF描画エンジンはOSのバージョンごとに改善されていますから，過去のOSについては要調査です。

**Comment by aminophen** [comment]
> Page 6 の影の部分が，変換経路によって維持されたり失われたりするのを怪訝に思っていたのですが，途中で Quartz API を経由する経路だった場合に /Transparency が失われる，ということだったのですね。動きが理解できました。

「Quartz による背景塗り」、または「塗らないけど Quartz でロンダリングする」という処理によって逆に汚くなる例はないでしょうか？ （例えば半透明のページそのものがテキスト保持 PDF で汚くなるとかだと、一律に Quartz に通すのは躊躇します）いったん調べておきましょう…

**Comment by doraTeX** [comment]
現状では，「Quartz によるPDFロンダリング」は，最終出力がEPSの場合にのみ行います。
EPS出力では，epswrite / eps2write / pdftops のいずれも元々半透明は苦手としているので，「ロンダリングによってより汚くなる」ということはないと思います。

「背景塗りを行うことによって結果的にロンダリングされる」場合は，確かに半透明部分がロスすることになります。テキスト保持PDF出力などで，背景塗りを行う場合と行わない場合で，サンプルの6ページ目の影の部分の見た目が変化するという状況は確かに発生していたと思います。

**Comment by aminophen** [comment]
> 現状では，「Quartz によるPDFロンダリング」は，最終出力がEPSの場合にのみ行います。EPS出力では，epswrite / eps2write / pdftops のいずれも元々半透明は苦手としているので，「ロンダリングによってより汚くなる」ということはないと思います。

では大丈夫ですね。それなら、仮に Quartz がなかったとしても gs でも全く問題ないことになります。（どうせアウトライン化するなら同じ）

**Comment by aminophen** [comment]
beta 8 はいい感じになっていますね。ありがとうございます。

まだ経路図をよく理解できていないので、あとでもう少しゆっくりテストしてみます。

**Comment by doraTeX** [comment]
補足：

> 現状では，「Quartz によるPDFロンダリング」は，最終出力がEPSの場合にのみ行います。
EPS出力では，epswrite / eps2write / pdftops のいずれも元々半透明は苦手としているので，「ロンダリングによってより汚くなる」ということはないと思います。

この説明は gs 9.15 以上を利用している場合の話です。（最終出力がEPS以外の場合は，eps2write ではなく pdfwrite を使うので，ロンダリングが不要です。）

一方，gs 9.14 以下の場合は，最終出力がEPSの場合でなくても，アウトライン化PDFなどを生成する場合，アウトライン化に epswrite を使用します。その場合同じ問題が生じますので，beta 8 では「epswrite にかける前にPDFロンダリング」を行うようにしています。

**Comment by aminophen** [comment]
ところで「白紙ページ」で「ページサイズ維持 ON」にした場合、どういう画像が出てくるのが正解でしたっけ…？ 維持したなら白画像が出てくるのかなと思ったのですが、手元では、白紙ページだけ「ページサイズ維持 OFF」の場合と同じになっています。

**Comment by doraTeX** [comment]
> ところで EPS 出力の場合ですが、「白紙ページ」で「ページサイズ維持 ON」にした場合、どういう画像が出てくるのが正解でしたっけ…？ 維持したなら白画像が出てくるのかなと思ったのですが、手元では、白紙ページだけ「ページサイズ維持 OFF」の場合と同じになっています。

「維持したなら白画像」となるはずです。こちらの手元ではそうなっているように見えるのですが，問題が生じる場合の各種設定値をお教え頂けますでしょうか。

**Comment by doraTeX** [comment]
すみません，確かに gs 9.10 で再現しました。
[Ver. 2.1.4 beta 9](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.4b9.zip) で修正できたはずです。

**Comment by aminophen** [comment]
> Ver. 2.1.4 beta 9 で修正できたはずです。

直りました。（gs9.16 でも gs9.05 でも白紙ページがサイズ維持されずクロップされていた問題が解消しました）

**Comment by aminophen** [comment]
Mac 版、ベクター画像だけ調べましたがたぶん意図どおりになっていると思います。変換経路図についてですが、pdfTeX をかけているときにそれぞれどういう効果を担っているのかもうすこし知りたいです。

- ページをバラバラにする or マルチページのまま通す
- クロップする or ページサイズ保持
- 余白をつける or つけない

それと「pdfTeX を通す場合・eps(2)write のクロップを信用せずに上書きする場合」に bb が必要になると思いますが、どの段階で取得してその値がどこに使われているのかも知りたいです。

以上の2点がわかれば、目的とする画像がちゃんと出ているかどうかの参考になります。

**Comment by doraTeX** [comment]
そのあたりの詳細は非常に場合分けが多くてややこしく，正確な実装は [Converter.m](https://github.com/doraTeX/TeX2img/blob/master/Sources/Converter.m) の `- (BOOL) compileAndConvert` から追いかけていくしかないのですが，簡単に言いますと：

* [変換経路図](https://github.com/doraTeX/TeX2img/blob/master/info/conversion.pdf)上の表記で「pdfTeXでクロップ」は pdfcrop 類似処理。「＋余白付与」が付いている場合は bp 単位で余白付与，付いていない場合は余白付与しない。ページサイズ維持がONの場合は指定された入力PDFの指定されたBoxを生成ファイルのMediaBoxにする。「ページサイズ維持」かつ「＋余白付与」の場合は「維持したBox＋余白」を新しいMediaBoxに設定。
* epswrite / eps2write 実行後は必ず直後にBBの上書きを実行。「ページサイズ維持」がONのときは元のPDFの指定Box，OFFのときは gs の bbox の結果で上書きする。gs の bbox の取得は原則として「必要になるたびにその場で gs の bbox を実行して取得」。ただし，gs の実行回数を抑えるため，既に取得済みの場合（場合によっては事前に全ページのbboxを一括取得している場合もある）はキャッシュを利用する。（ [Converter.m](https://github.com/doraTeX/TeX2img/blob/master/Sources/Converter.m) のソース上で `bboxDictionary` というディクショナリ（ハッシュ・連想配列）に一度取得したbbox値を収めている。）
* pdfTeX による pdfcrop 類似処理の結果，ページをばらすかばらさないかは，状況による。できるだけ pdfTeX の実行回数を抑えたいが，「Quartz API による背景塗り」「Quartz API によるPDFロンダリング」「mudraw」など，単一ページPDFにしか適用できない操作がその先に控えている場合には，事前にPDFをばらしておく措置を行っている。 [Converter.m](https://github.com/doraTeX/TeX2img/blob/master/Sources/Converter.m) のソース上で `page:0` となっている部分が「全体一括クロップ（マルチページ cropped PDF）」を生成する過程。

**Comment by aminophen** [comment]
それだけ情報があれば追いかけられます。ありがとうございます。

**Comment by doraTeX** [comment]
概ね問題なさそうなので，一旦このあたりで Ver. 2.1.4 としてリリースすることにいたしましょう。

**Comment by aminophen** [comment]
> 一旦このあたりで Ver. 2.1.4 としてリリースすることにいたしましょう。

細かい修正、ありがとうございました。リリースよろしくお願いします！
