### ISSUE TITLE
「クリップボードにコピー」後に自動ペーストする機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#71]
<img width="498" alt="2015-12-11 10 33 00" src="https://cloud.githubusercontent.com/assets/6186180/11733643/d1c4af54-9ff2-11e5-8854-4ed96cfd66fb.png">

この画面において，「生成ファイルをクリップボードにコピー」のサブ項目に

　自動的にペースト：`プルダウンメニュー `

というものを用意すると，Illustrator 自動配置と同様の利便性が生まれて便利そう。

プルダウンメニューの項目には，Finder でコピーした画像ファイルのペーストに対応しているアプリの一覧を並べる。
今までに確認済みのものは以下の通り。

* Word 2016
* PowerPoint 2016
* Pages
* Numbers
* Keynote

**Comment by aminophen** [comment]
そういえば、Illustrator で配置できるのは EPS だけなのでしょうか？ もし PDF も可能ならそれも推奨してはいかがでしょう？ 少なくとも gs9.15 以上では、pdfwrite でアウトライン化した方が綺麗になるわけですし。

**Comment by doraTeX** [comment]
PDFも配置はできるのですが，その場合「配置後にグループ化解除」は効きません。
これは，EPSを配置するとシンプルな構造のオブジェクトが貼られるのに対し，PDFは多重にクリッピングマスクが重なった複雑な構造のオブジェクトが貼られるからです。

次の図をご覧ください。
<img width="1010" alt="2015-12-11 11 12 48" src="https://cloud.githubusercontent.com/assets/6186180/11734203/46ed849a-9ff8-11e5-8b1c-659732c57abb.png">

上半分はEPSを貼った結果，下半分はPDFを貼った結果をアウトライン表示したものです。

PDFの方は，MediaBoxサイズのクリッピングマスクが二重にかかった，複雑なオブジェクトになっていることが分かります。
この状態から一つ一つの文字をばらしたり加工したりしようとすると，「オブジェクト→クリッピングマスク解除」を2回行い，かつこのクリッピングマスクを構成している余計な長方形のパス（二重に重なって二つあります）を削除する必要があります。

EPSの方は，「グループ化解除」を1回実行すれば個別の文字に砕くことができます。

**Comment by aminophen** [comment]
> EPSの方は，「グループ化解除」を1回実行すれば個別の文字に砕くことができます。

なるほど、確かに EPS のほうが便利ですね。（そういえばいつも私はアウトライン化 PDF を出力して Inkscape でグループ解除を何回もやっていました。EPS だとそんなには要らなくなるんですね）

**Comment by doraTeX** [comment]
次のアプリについて，自動ペースト機能を実装しました。

* Word
* PowerPoint
* Pages
* Numbers
* Keynote

<img width="498" alt="2015-12-16 0 09 33" src="https://cloud.githubusercontent.com/assets/6186180/11814293/4ed6e3ba-a389-11e5-934b-71a5038731f5.png">

なお，Word 2016 / PowerPoint 2016 は普通に

1. Finder で画像ファイル（複数可）をコピー
2. Office 上でペースト

とすると画像が貼り込まれます（Excel は不可）。

それに対し，Word 2011 / PowerPoint 2011 は，クリップボードからの画像のペーストには対応していません。

そこで，今回の自動ペースト機能では，貼り付け先の Word や PowerPoint のバージョンを判定し，それが 2011 以下の場合には，ペーストではなく，Office が持っている直接的な画像貼り込み機能を利用して，あたかもペーストしたかのような挙動を実現することにしました。

なお，同じ方法を 2016 に対して適用すると，今度はアクセス許可についての面倒なウィンドウが出てしまいます。

<img width="456" alt="2015-12-16 0 17 10" src="https://cloud.githubusercontent.com/assets/6186180/11814601/0ab4b96c-a38b-11e5-812f-518d0dc67bfe.png">


よって，

* Office 2011（以下）では画像貼り込み機能を利用する
* Office 2016（以上）ではクリップボードからのペーストを利用する

という現状の場合分けが最善と言えるでしょう。

なお，Pages / Numbers / Keynote は，普通にペーストによる画像貼り付けが利用できますので，それをそのまま利用しています。

**Comment by doraTeX** [comment]
[Ver 2.1.5 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.5b2.zip) としてビルドしました。
なお，#64 の名案が見つかるまで，pdftops 経由のアウトライン化SVG生成を行うようにした Ver. 2.1.5 beta 1 での変更は一旦 Revert しておきました。

**Comment by aminophen** [comment]
> 自動ペースト機能を設けた Ver 2.1.5 beta 2 をビルドしました。

Word 2011 / PowerPoint 2011 しか試せていませんが、自動ペーストに成功しました。
