### ISSUE TITLE
文字種一括変換機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#76]
**文字種一括変換機能**を搭載した [Ver. 2.1.6 beta 3](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.6b3.zip) を作成しました。

メインメニューの「編集」，またはテキストエリアの右クリックで現れるコンテクストメニューに，次のような「文字種一括変換」メニューを新設しました。

![2016-09-27 18 20 47](https://cloud.githubusercontent.com/assets/6186180/18867439/2be8784a-84df-11e6-908d-e7c5a6f57d45.png)

# 仕様

* 選択範囲の文字種を一括変更します。
* 選択範囲がない場合は，確認ダイアログを表示の上，文書全体の文字種を変更します。
* 変換後も選択範囲が維持されるので，複数の変換を連続して行えます。
* 「Unicode文字 → ajmacros」というのは，`①` → `\ajMaru{1}` のように，`ajmacros.sty` に定義されたマクロを使うように置換します。
* 例えば `①` が行末に存在する場合，単純に `\ajMaru{1}` に置換してしまうと，改行文字による空白トークンが入ってしまい，組版結果が同じでなくなってしまいます。それを防ぐため，元のUnicode文字が行末にあった場合は `%` も付与します。
* 「`私は☃です`」を単純に「`私は\ajSnowmanです`」に置換してしまうと，Undefined control sequence になってしまうので，引数を伴わないマクロに置換する際には「`私は\ajSnowman です`」のように空白文字を伴って置換します。
* 逆方向の「ajmacros → Unicode文字」は，`\ajMaru{1}` → `①` のように置換します。
* 「`私は\ajSnowman です`」を「`私は☃です`」に復元できるよう，これらの命令は後ろに伴う空白文字の並びも含めてUnicode文字に置換します。
* 「`\ajMaru1`」のように `{}` なしで1桁整数が引数として与えられている場合も，適切にUnicode文字に置換します。
* Unicode文字と ajmacros との対応は，ある程度手動で対応づけていますので，ミスや抜けがあり得るかもしれません。対応は [NSString-Conversion.m](https://github.com/doraTeX/TeX2img/blob/master/Sources/NSString-Conversion.m) に規定されています。

**Comment by aminophen** [comment]
簡単にしかテストしていませんが、正常に動いていると思います（例によって Lion 10.7.5）。ajmacros はあまり使ったことがないため、ミスや抜けまでは確認できていませんが…

**Comment by aminophen** [comment]
昔からある「JIS X 0208 外の文字を \UTF に変換」についても、ファイル保存時だけでなく今回のと同じ使い心地のメニューとして追加して良いのではないか、とふと思いました。

**Comment by doraTeX** [comment]
名案ですね！そうしましょう。

**Comment by doraTeX** [comment]
\UTF 変換機能を用意した [Ver. 2.1.6 beta 4](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.6b4.zip) を作成しました。

<img width="425" alt="2016-09-28 1 06 41" src="https://cloud.githubusercontent.com/assets/6186180/18881837/d826446a-8517-11e6-8c0f-4e87f6830a19.png">

# 仕様

* JIS X 0208 に含まれず，かつUnicodeのBMPに含まれる文字を，`\UTF{xxxx}` の形式に変換できます。また，`\UTF{xxxx}` を元の文字に復元できます。
* 「𠮷」のように，BMP外文字であっても Adobe-Japan1 に含まれる文字であれば，`\CID{xxxxx}` の形式に変換します。ただしこの変換は不可逆です。

# 例

```tex
☃と内田百閒と森鷗外が𠮷野家と髙島屋に行くところを想像した。
```

を `Unicode文字 → \UTF / \CID` で変換すると，

```tex
\UTF{2603}と内田百\UTF{9592}と森\UTF{9DD7}外が\CID{13706}野家と\UTF{9AD9}島屋に行くところを想像した。
```

に変換されます。これを `\UTF → Unicode文字` で復元すると，

```tex
☃と内田百閒と森鷗外が\CID{13706}野家と髙島屋に行くところを想像した。
```

となり，「𠮷」以外は復元できます。

**Comment by doraTeX** [comment]
ajmacros との変換対象に

* 髙 ⇄ \ajHashigoTaka
* 𠮷 ⇄ \ajTsuchiYoshi
* 﨑 ⇄ \ajTatsuSaki
* 濵 ⇄ \ajMayuHama

も加えた [Ver. 2.1.6 beta 5](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.6b5.zip) を作成しました。

こちらであれば，「𠮷野家」の可逆な変換が可能です。

**Comment by doraTeX** [comment]
\CID からUnicode文字への変換（対応する文字が存在する場合）もサポートした [Ver. 2.1.6 beta 6](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac2.1.6b6.zip) を作成しました。

これで，
```tex
☃と内田百閒と森鷗外が𠮷野家と髙島屋に行くところを想像した。
```

と

```tex
\UTF{2603}と内田百\UTF{9592}と森\UTF{9DD7}外が\CID{13706}野家と\UTF{9AD9}島屋に行くところを想像した。
```

の可逆的変換が可能になりました。

**Comment by aminophen** [comment]
Ver. 2.1.6 beta 6 を試してみました。うまくいっていると思います。ありがとうございます！

**Comment by doraTeX** [comment]
テストありがとうございます。半年以上振りの新バージョンとしてリリースしておきました。
（Ver. 2.1.6 としてリリース後，一部の変換忘れを見つけたので，こっそりGUI版バイナリを差し替えました😓）
