### ISSUE TITLE
GUIによるカラーリングの変更

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#8]
[LaTeXiTが勝る点](https://twitter.com/aminophen/status/566884993402540032)の残り1点，「GUIによるシンタックスハイライトの色変更」ができるようにしたい。

* Windows版のUIが参考になる。

![Windows版のUI](http://cdn-ak.f.st-hatena.com/images/fotolife/a/acetaminophen/20141219/20141219113528.png)

* 環境設定パネルに新しいタブを追加し，そこに設定をまとめる。
* そうなると，現在「表示」メニューにある「対応する括弧の強調表示」「不可視文字の表示」も，あわせて環境設定パネルに移すのがよいだろう。
* 「表示」メニューの「ソースのカラー表示」は，OFFにする必要性がないであろうから，廃止でいい気がする。
* 現在ソースウィンドウ，プリアンブルウィンドウのそれぞれに設置されている「表示フォント設定」も，環境設定パネルに一元化するのがよいか。

**Comment by aminophen** [comment]
たしかに Mac 版には「GUIによるシンタックスハイライトの色変更」が無かったですね。

私の例の Tweet は舌足らずで、色を変えるというのは \textcolor にあたるものを指したつもりでした。
GUI で色を選択すると、テキスト全体がその色に変化します。

![2015-02-27 19 49 37](https://cloud.githubusercontent.com/assets/9957466/6411227/d86fb95e-beb9-11e4-9f2c-ef38e204a1c1.png)

特定の部分だけを…ということもできそうですが、ほとんど使ったことがないため仕様がよく分かっていません。

**Comment by aminophen** [comment]
ソースのハイライト色変更は好みの問題で、特に（私の場合は）変更する<b>必要性</b>は無いと思います。それほど重要度は高くないのではないでしょうか。

**Comment by doraTeX** [comment]
自分も特に変更の必要性を感じているわけではありませんが，変更したい人がいるかもしれないので，変更用のインターフェースはあるに越したことはないでしょうね。
優先度は高くないとのことなので，では暇のあるときにでも。

**Comment by aminophen** [comment]
「GUIによるシンタックスハイライトの色変更」を実装するのであれば、Windows 版のような

> - 環境設定パネルに新しいタブを追加し，そこに設定をまとめる。

がよいですね。そうなると、おっしゃるとおり

- 現在「表示」メニューにある「対応する括弧の強調表示」「不可視文字の表示」も，あわせて環境設定パネルに移すのがよいだろう。
- 「表示」メニューの「ソースのカラー表示」は，OFFにする必要性がないであろうから，廃止でいい気がする。

は同じ画面に置いたほうがシンプルですね。

- 現在ソースウィンドウ，プリアンブルウィンドウのそれぞれに設置されている「表示フォント設定」も，環境設定パネルに一元化するのがよいか。

これも、別々にしたい人はそうそういないのではないかと思います。統一して環境設定に含めて良さそうです。

優先順位は高くないので、のちほどゆっくりということで。

**Comment by doraTeX** [comment]
# ToDo

* ソースウィンドウ，プリアンブルウィンドウのそれぞれに設置されている「表示フォント設定」ボタンを廃止
* 代わりに環境設定パネルに「表示」タブを設け，その中に表示フォント設定の項目を設ける
* 「表示」メニューの「ソースのカラー表示」を廃止
* 「表示」メニューの「対応する括弧の強調表示」「不可視文字の表示」は環境設定パネルに移動
* シンタックスカラーリングの変更機能
* タブ幅の変更機能

**Comment by doraTeX** [comment]
![2015-07-27 20 48 41](https://cloud.githubusercontent.com/assets/6186180/8905488/b7391af6-34a1-11e5-8921-e0d55558a271.png)

環境設定パネルに上記のようなタブを設けました。
上記ToDoのうち，

> * 「表示」メニューの「ソースのカラー表示」を廃止
> * 「表示」メニューの「対応する括弧の強調表示」「不可視文字の表示」は環境設定パネルに移動
> * タブ幅の変更機能

は完了。

# 残るToDo
* ソースウィンドウ，プリアンブルウィンドウのそれぞれに設置されている「表示フォント設定」ボタンを廃止
* 代わりに環境設定パネルに「表示」タブを設け，その中に表示フォント設定の項目を設ける
* シンタックスカラーリングの変更機能

**Comment by doraTeX** [comment]
> * ソースウィンドウ，プリアンブルウィンドウのそれぞれに設置されている「表示フォント設定」ボタンを廃止
> * 代わりに環境設定パネルに「表示」タブを設け，その中に表示フォント設定の項目を設ける

まで完了。次のような画面になりました。

<img width="442" alt="2015-07-27 23 57 13" src="https://cloud.githubusercontent.com/assets/6186180/8909250/59513616-34bb-11e5-83bf-860be1458510.png">

ここでいったん Ver. 1.9.5 としてリリースしておきます。

# 残るToDo: シンタックスカラーリング機能

次の色の設定を設定画面から変更できるようにする。

* { } と $
* コメント
* 制御綴
* 対応括弧が強調表示されているときの括弧類
* 対応括弧が強調表示されているときの括弧の内側の背景色
* 不可視文字表示

## ここまでは必要ないかもしれない色変更機能
* エディタ背景色
* エディタ文字色
* カーソル色

**Comment by doraTeX** [comment]
長らく懸案となっていた，GUIによる表示色設定変更機能をとうとう設けました。
[Ver. 1.9.8 beta 2](https://dl.dropboxusercontent.com/u/5807100/TeX2imgMac1.9.8b2.zip) にて，次のような設定画面を搭載しました。
#24（）#25 （現在の環境を閉じる），#26（文字情報），#27（）
よろしければぜひお試しください。

![2015-08-11 21 11 01](https://cloud.githubusercontent.com/assets/6186180/9197273/d45afb40-406d-11e5-82e4-79c9bea38407.png)

**Comment by doraTeX** [comment]
もう一つ，「括弧不一致で点滅している背景」の色を変更できるようにするのを忘れていました。

<img width="442" alt="2015-08-12 23 10 29" src="https://cloud.githubusercontent.com/assets/6186180/9226009/784184d4-4147-11e5-83f7-ca1ef4d8701d.png">
