### ISSUE TITLE
自動インデント機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#80]
TeX2img のソースウィンドウ・プリアンブルウィンドウにおいて，TeXShopなどと同様の「自動インデント機能」を設けたい。

* 現在の行にならって，スペースやタブの連続を全く同じように次の行の冒頭部に挿入する。
* 設定パネル or メニューにON/OFFを切り替える設定項目を設けるか，強制的に常時ONにするか？
* 発動のタイミングの洗い出し，および仕様の策定。単純にリターンキーを押した場合以外に，例えば次のようなケースにおける挙動の仕様はどうあるべきか？
  * 改行コードを含む複数行テキストをペーストした場合の扱いはどうするか
  * コメント中での改行はどう扱うか
  * 複数行コメントをペーストした場合はどうするか
* Undoが期待通りに動くか

**Comment by Yasunari15** [comment]
> 設定パネル or メニューにON/OFFを切り替える設定項目を設けるか，強制的に常時ONにするか？

前の行にインデントを入れておいて，次の行では入れないという状況は基本的に思い浮かびませんね。区別したいならば，再度インデントを入れた上でreturnを押せば良い話ではないでしょうか。

また，強制的にONになっていて困るとすれば`}`の前にインデントが入っていて，その後で改行したケースだと思いますが，`{}`とセットで打っていれば困ることは無いと思いますが，どうでしょうか。

**Comment by doraTeX** [comment]
「編集」メニューの中に「自動インデント」という項目を設けた Ver. 2.2.7 をリリースしました。
これをONにしておくと，概ね期待通りの動きをするのではないかと思います。ぜひお試しください。
