### ISSUE TITLE
Auto Indent

### ISSUE THREAD

**Issue by Yasunari15** [doraTeX/TeX2img#82]
Indentを開けている状態で`\begin{hoge}`とした時に，Auto Completeされた`\end{hoge}`にはIndentが空きません。TeXShopでは出来るにも関わらず，TeX2imgでは出来なくなっていることのようです。対策を講じて頂けると助かります。

**Comment by doraTeX** [comment]
#83 とともに，Ver. 2.2.8 で対応しました。

**Comment by Yasunari15** [comment]
ありがとうございました，Installして確認できましたので寝ます😴Auto Completeの切り替えにShortcutがあると良いなと思いました。
