### ISSUE TITLE
オートコンプリートのショートカットキー

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#84]
（#82 からの派生）

オートコンプリートのショートカットキーがほしいという要望をいただきました。
ショートカットキーの組み合わせですが，

* `Command` + `Shift` + `Control` + `A`

でいかがでしょう。（それほど頻繁に切り替えるわけでもないでしょうから，他の機能とのバッティングを避けるためにやや複雑気味のショートカットキーとしてみました。）

これで問題なさそうならこれでリリースします。

**Comment by Yasunari15** [comment]
ご存知のように，こちらのKeyboardはUSなので，少し押しにくい気がします。Shiftを抜くとTeXShopの関連Filesを削除と同じになってしまいますから，Controlを抜いて頂けますでしょうか。これは，Mail.appのAttach FIles...と一緒ですが，どうでしょうか。

**Comment by doraTeX** [comment]
Command+Shift+A で Ver.2.2.9 としてリリースしました。
