### ISSUE TITLE
White Contents in Transparent PNG

### ISSUE THREAD

**Issue by Yasunari15** [doraTeX/TeX2img#85]
背景に濃い色がついている印刷物やHomepageなどに，TeX2imgで作った画像を貼りこみたいとき，Contentsを白くしておきたいことがありました。

![screen shot 2018-07-15 at 18 18 40](https://user-images.githubusercontent.com/38091102/42732383-96a8212c-885b-11e8-8a77-60c1b9d00c04.png)

この張り込む画像をTeX2imgで一発で作るためには，以下の条件があると考えています。

* 透過PNG
* 「original paper size」は捨てる

ただ，白紙からpdfTeXでCropするのは不可能ですから，現状ではOutline化できる形式に書き出して，IllustratorなどのGUI上で白くして透過PNGに書き出すしか無いと思います。

今回はこの方法で何とかできましたが，`\sqrt`で同じことをやると拡大したときに記号が乱れてしまい，諦めたことがありました。TeX2imgで直接，このようなPNGを作る方法を考えて頂けますでしょうか。

**Comment by doraTeX** [comment]
単に `\color{white}` に続けて本文を書いて透過PNG出力すればよいのではないでしょうか？

**Comment by Yasunari15** [comment]
`TeX2img: Getting the bounding box...`と出てしまい，Buttonは`Generate`に戻ってしまいます。

**Comment by doraTeX** [comment]
こちらでは問題なく出力できています。


<img width="1009" alt="image" src="https://user-images.githubusercontent.com/6186180/42733832-b4f2c8e0-8873-11e8-866a-6a39a3aadb44.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/6186180/42733824-a48083bc-8873-11e8-997d-c576cf1a22ad.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6186180/42733833-bd1c1990-8873-11e8-840d-5976daebe96c.png">

**Comment by Yasunari15** [comment]
いろいろ試してみたところ，Marginが上下方向・左右方向のそれぞれにおいて，無いと出力できないようです。
![screen shot 2018-07-15 at 21 20 22](https://user-images.githubusercontent.com/38091102/42733883-e79dbfb0-8874-11e8-8de6-5b3e191a4ec8.png)

**Comment by doraTeX** [comment]
どうやら #21 で空白ページをスキップする仕様にしたことによる影響ですね。
#21 での議論はかなり複雑だったので，これに手を入れるのは若干不安ではありますが，一応対応を入れるようにしてみましょう。

**Comment by doraTeX** [comment]
Ver. 2.3.0 で対応できたはずです。ご確認ください。

**Comment by Yasunari15** [comment]
確認できました，ありがとうございます。Mailにてご確認致しました通り，東大TeX愛好会の「Members」に特別顧問として紹介させて頂いても宜しいでしょうか。返信，遅くなりまして申し訳ありませんでした。

**Comment by doraTeX** [comment]
あ，すみません，メール返信忘れてました。今返信します。
