### ISSUE TITLE
OutputとView

### ISSUE THREAD

**Issue by Yasunari15** [doraTeX/TeX2img#86]
1. Outputで5つの数値を設定していますが，ここのInterfacesは[Steppers](https://developer.apple.com/design/human-interface-guidelines/macos/selectors/steppers/)よりは，上下の[Sliders](https://developer.apple.com/design/human-interface-guidelines/macos/selectors/sliders/)の方が良い気がします。
2. FontをSF Pro Textに設定していました。違和感を感じたため確認してみたらHiragino Sansに変わっていました。Mojaveが原因かもしれませんが，TeX2imgに問題が無いか確認して頂いてもよろしいでしょうか。
3. 以下のTeXShopの仕様をTeX2imgに取り入れて下さると嬉しいです。
* Fontを選択するときにPreviewできる。
* ConsoleのFont・Colorsも指定できる。
4. Dark Modeの影響でAdvanced...のButtonsが見にくくなるようです。
![screen shot 2018-07-18 at 21 49 12](https://user-images.githubusercontent.com/38091102/42883022-59a99662-8ad5-11e8-9e40-b5184433bd9c.png)

**Comment by doraTeX** [comment]
論点が複数ある場合は，個別にIssueを立ててくださると助かります。案件ごとにOpen, Closeを制御できますので。

# 1点目

昔はスライダーUIにしていましたが，

* マウスでの数値微調整が難しいこと
* UI上の面積を無駄に消費すること（特に，微調整を可能なようにしようとするととても長いスライダーが必要となり，面積を大量消費する。以前 Resolution Level を設定可能なようにスライダーにしていた時代は，数値微調整をできるようにするために画面横幅いっぱいのスライダーが必要になっていた。）
* 上下左右の順番をどう定めても直観的でないこと

により，上下左右が直観的に分かりやすくかつ面積もコンパクトで済む現在のUIに変更しました。

# 2点目，4点目

Mojaveはまだインストールしていないので，Mojaveをインストールした暁に動作確認します。

# 3点目

> Fontを選択するときにPreviewできる。

こんな機能がTeXShopにありましたでしょうか……？

> ConsoleのFont・Colorsも指定できる。

これは技術的には当然可能ではありますが，UIとの兼ね合いの問題ですね。Macアプリ（およびAppleのOSやハードウェアもそうですが）の設計思想として，「ユーザの選択肢は多い方がよいとは限らない」「設定項目をむやみに増やすよりも選択肢を狭めた方が結局ユーザのためになる」という考え方があります。狭い設定画面の中に設定項目が大量に詰め込まれていると，ユーザにとって分かりにくくなります。TeXShopの設計においてもそれは強く意識されており，だからこそあまり細かい設定についてはあえてGUIには載せずに，`defaults write ...` というコマンドラインからのみ変更可能なように，設定項目の棲み分けがなされています。

**Comment by Yasunari15** [comment]
> 論点が複数ある場合は，個別にIssueを立ててくださると助かります。案件ごとにOpen, Closeを制御できますので。

ご迷惑をおかけしました，申し訳ありません。

> 上下左右が直観的に分かりやすくかつ面積もコンパクトで済む現在のUIに変更しました。

IllustratorのOpacityのようなUIであれば，全て解決できると考えました。

> こんな機能がTeXShopにありましたでしょうか……？

![screen shot 2018-07-18 at 23 55 31](https://user-images.githubusercontent.com/38091102/42890003-b51a7406-8ae6-11e8-91ac-41c54220298c.png)

> あまり細かい設定についてはあえてGUIには載せずに，`defaults write ...`というコマンドラインからのみ変更可能なように，設定項目の棲み分けがなされています。

TerminalからTeX2imgのConsoleをCustomizeできるのでしょうか。

**Comment by doraTeX** [comment]
> こんな機能がTeXShopにありましたでしょうか……？

あ，これはつい最近ついたばかりの機能ですね。自分が常用している社内版TeXShopには搭載されていないので気づいていませんでした。

> TerminalからTeX2imgのConsoleをCustomizeできるのでしょうか。

今のところその仕組みは作ってないですね。フォント名の指定がターミナルからでは難しい（フォント名を指定すればいいわけではない）ので，色はともかく，フォントの設定は事実上GUIからしかできないです（TeXShopでも，フォント名の指定を `defaults write...` からすることはないはずです）。すなわち，現状の設定UIの中にコンソールフォントの設定項目を割り込ませる必要がありますが，面積的に厳しいですね……

**Comment by doraTeX** [comment]
> IllustratorのOpacityのようなUIであれば，全て解決できると考えました。

あれはmacOSの標準的なUIではないので，ぱっと作ることは難しいですし，あんまりmacOSらしくもない気がしますね……（Apple純正アプリであのUIは見かけない気がします）。

**Comment by doraTeX** [comment]
> すなわち，現状の設定UIの中にコンソールフォントの設定項目を割り込ませる必要がありますが，面積的に厳しいですね……

考え方を変えて，コンソールビューのフォントもソースウィンドウ・プリアンブルウィンドウのフォントと連動させるようにすれば万事解決では，と思いました。それならば簡単です。

**Comment by Yasunari15** [comment]
Mojaveでは，FontをSF Pro Textに設定すると，同時にConsoleも連動します。ただ，しばらくして両方ともHiragino Sansになってしまうこともあり，High Sierraではどのようになっているのか分かりません。

**Comment by doraTeX** [comment]
> ただ，しばらくして両方ともHiragino Sansになってしまうこともあり，

これは，「コンパイル終了後にアウトプットビューのフォントをソースビューと同フォントにリセットする」という措置が入っているためです。

**Comment by doraTeX** [comment]
> 考え方を変えて，コンソールビューのフォントもソースウィンドウ・プリアンブルウィンドウのフォントと連動させるようにすれば万事解決では，と思いました。それならば簡単です。

というか，既にそのようになっていました。

**Comment by Yasunari15** [comment]
SF Pro Textに固定することはできないのでしょうか。

**Comment by doraTeX** [comment]
TeX2imgのフォント設定で SF Pro Text で指定したのであれば，

> これは，「コンパイル終了後にアウトプットビューのフォントをソースビューと同フォントにリセットする」という措置

により，毎回それにリセットされるはずです。

> しばらくして両方ともHiragino Sansになってしまうこともあり，

というのがどういうことか再現できないのでなんとも分かりません。Mojaveのバグという可能性もありえます。

**Comment by Yasunari15** [comment]
[Screen Recording](https://drive.google.com/open?id=1e-vdpKX9GbY1E1Rh4SnUCOydqqIgNcAY)をご覧ください。

**Comment by doraTeX** [comment]
質問の意図を誤解していましたが，フォントの見た目が変わる（だけ）という話ではなく，フォント設定自体が変化してしまうという話でしたか。これは見たことがない現象ですね。設計上の心当たりもありません。（ユーザから明示的にフォント設定が変更された場合以外に，フォント設定を書き換える動作は入らないはずなので……）
自分のマシンで再現できれば調査もできるのですが，今のところ再現できておらず，調査もできません。

**Comment by doraTeX** [comment]
論点が入り乱れてきたので，いったんcloseして個別にissueを立て直します。
