### ISSUE TITLE
Mojave のダークモードでの視認性

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#88]
（#86 から分離）

Mojaveのダークモードにおいて，環境設定パネルの「詳細...」ボタンが見づらくなるという報告あり。要確認。

**Comment by Yasunari15** [comment]
![screen shot 2018-07-19 at 23 32 39](https://user-images.githubusercontent.com/38091102/42949136-0f05bd2a-8bac-11e8-8972-e814b3110121.png)

**Comment by doraTeX** [comment]
これはダークモードですか？特に見にくくはないと思いますが……

**Comment by doraTeX** [comment]
むしろ通常モードのときと比べてコントラストがくっきりして見やすくなっているような。

<img width="498" alt="2018-07-19 23 36 40" src="https://user-images.githubusercontent.com/6186180/42949388-9b277578-8bac-11e8-98c8-2e820dc11c43.png">

**Comment by Yasunari15** [comment]
Screenshotを撮ったら，なぜか色が変わりましたが，実際の設定画面には「Advanced...」が黒色で出ています。Dark ModeのBugかもしれません。

既存のApplicationはMojaveになったらDark Modeになるわけでは無いようです。私にはよく分かりませんが，[Supporting Dark Mode in Your Interface](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface)に従って対応して頂けますでしょうか。

**Comment by doraTeX** [comment]
Mojaveの実機がないと実験できないので，Mojaveのリリースが迫ってきたら実機にインストールして実験します。

**Comment by Yasunari15** [comment]
TeX2imgのDark Modeを待ち望んでいるので，新しいbranchでBuildして頂いて，こちらのMacで実験してしましょうか。ただ，現在の色分けのままだと黒い背景に青や緑ということになりますので，TeXShopも含めて検討が必要かもしれませんね。

**Comment by doraTeX** [comment]
ガイドラインに沿ったプログラミングをするにもMojaveの実機が必須なので，しばらくは対応できません。

**Comment by Yasunari15** [comment]
分かりました。首を長くして待つことにします。新しい色分けについても，ご検討よろしくお願いします。

**Comment by doraTeX** [comment]
（昔話）
以前，10.7 Lion Beta をインストールしたら，それはそれはひどいもので，Finderで新規ウインドウを開くたびにFinderがクラッシュしまくるという有様でした。その結果使い物にならず，いったんHDDを初期化して10.6をインストール・設定し直すのに丸一日を要したという苦い経験があります。そのトラウマにより，Golden Master が出るくらいまでは仕事で使うMacにはベータ版新OSは入れないようにしております。

**Comment by doraTeX** [comment]
> ただ，現在の色分けのままだと黒い背景に青や緑ということになりますので，TeXShopも含めて検討が必要かもしれませんね。

これはシンタックスハイライトのデフォルトカラーのことですね。確かに現状のままでは視認性が悪そうです。Mojaveのリリースが迫ってくればTeXShopの側でも対策が打たれると思いますので，それに足並みをそろえた対応をしたいところです。

**Comment by doraTeX** [comment]
#91 に立て直しました。
