### ISSUE TITLE
GUIによる生成画像全体の文字色変更

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#9]
LaTeXiTには[GUIによる生成画像全体の文字色変更機能がある](https://github.com/doraTeX/TeX2img/issues/8#issuecomment-76375668)とのこと。

![LaTeXiT](https://cloud.githubusercontent.com/assets/9957466/6411227/d86fb95e-beb9-11e4-9f2c-ef38e204a1c1.png)

## この機能は必要？

全体の文字色を変えたいユーザは，プリアンブルに

```tex
\usepackage{color}
\color{red}
```

などと入れておけば済む話ではあるが，GUIからそれを可能とする機能は必要だろうか。

## 仮に入れるとした場合の仕様と課題

* 仕様としては，プリアンブルに自動的に上記のような文字列を挿入した上で一時ファイルを生成してコンパイルすることになるだろう。
* ユーザが既にプリアンブルに color や xcolor パッケージを \usepackage していた場合，重複して color パッケージなどをロードしてはいけないといった判断が必要になる。
* 多数のTeXエンジンをサポート対象としているTeX2imgの場合，color / xcolor パッケージの[ドライバ依存性の問題](http://qiita.com/zr_tex8r/items/442b75b452b11bee8049)が生じる。LaTeXのパス設定が他の挙動に影響を及ぼさないとするTeX2imgの現在の設計思想からすると，パス設定に指定されたエンジンに応じて，自動挿入する color / xcolor パッケージのドライバ指定を変えるという挙動は再び「有毒」となってしまう。

上記のようなことを考えると，ユーザが自由にプリアンブルを設定できるTeX2imgでは，この機能は特に必要なさそうな気がします。
公式サイトのTips集に「文字色を変えるには」という項目を設けておけば済む話のような。

**Comment by aminophen** [comment]
LaTeXiT の場合は常に

> \usepackage[usenames]{color}

がプリアンブルに入っていました（ドライバ指定については考慮されているのかどうか不明）。対応しているフローは pdflatex, xelatex, latex + dvipdfmx です。ただ、どうやら <a href="http://www.fukudat.com/wiki/ja/TeXCrop">TeXCrop</a> と似た操作性で一部だけに色を付けるためにも使えるらしく、その機能は便利かもしれません。全体の色を変えるだけであればまったく必要ありませんね。

**Comment by aminophen** [comment]
LaTeXiT では、ボタンクリック数回で

![2015-02-27 20 22 49](https://cloud.githubusercontent.com/assets/9957466/6411701/7572d4ee-bebe-11e4-97bd-2a81a5bc1e26.png)

こんなふうになりました。

**Comment by doraTeX** [comment]
なるほど，つまりGUIによる \color 挿入補助機能というわけですね。
自分はあまり必要性を感じたことはないのですが，プレゼン用に部分部分で色が変わった数式画像を作成したい人にとっては確かにあると便利かもしれません。

ただ，Mac版TeX2imgには，TeXShopと同等の補完機能があるので，「よく使うコマンドの入力支援」はそちらで実現可能ではあります。

たとえば，補完用語リストに
```tex
\textcolor{•‹色›}{•‹内容›}
```
などと登録しておき，\textc あたりまで入力してからESCキーを押してこの文字列を補完入力します。さらに，control + / を押すとカーソルが •‹色› と •‹内容› の部分を行き来できます（control + shift + / で逆順）。

このように，汎用的な入力支援機能が既に存在しますので，\color だけ特別な入力支援機能を用意する必要性はあまり高くないかなと思います。

**Comment by aminophen** [comment]
LaTeXiT のカラーパレットはもしかすると便利かもしれないと思いましたが…

![2015-02-27 21 07 16](https://cloud.githubusercontent.com/assets/9957466/6412245/a6c7627a-bec4-11e4-833f-ee15864b4ddd.png)

どこまでサポートすべきかよくわかりませんし、そこまでしなくても良いのかなと思います。

 # 実際 LaTeXiT の color 指定も、特定部分だけを着色するのに少々手間取りました。仕様がいまいち理解できません…

ただ、白黒反転オプションなんかはあってもいいかもしれませんね。黒地に白文字というのはスライドで結構使います。

**Comment by doraTeX** [comment]
なるほど，GUIでカラーパレットから選んだ色を \color[rgb]{1,0.5,0} のような形に自動翻訳して入力する入力支援ボタンみたいなのはあってもいいかもしれませんね。

> ただ、白黒反転オプションなんかはあってもいいかもしれませんね。黒地に白文字というのはスライドで結構使います。

そういえば，TeXShopに似たような機能はありますね。環境設定＞コピー＞カラーマップ の設定を変更すると，プレビューウィンドウ上で範囲選択してクリップボードにコピーする際，黒と白をそれぞれ何色に変換してクリップボードに保存するかを指定できます。これは，コピー対象領域の全ピクセルの色を調べて，黒と白をそれぞれ指定された色に変換（それ以外の色は線形補間）してコピーするという動きをします。

TeX2img にもそのような機能があってもいいかもしれませんが，そのようなピクセルごとの変換はビットマップ形式の画像出力の場合のみ意味をなします。

ベクトル形式出力の場合も含めての色の変換となると，やはりソース側で指定しておくのが簡単でしょうね。

プリアンブル部に
```tex
\documentclass{standalone}
\usepackage{color}
\pagecolor{black}
\color{white}
```
と指定しておけば，「黒地に白」の画像出力が可能です。
（これもTips集に含めるとよさそう。）

**Comment by aminophen** [comment]
> （これもTips集に含めるとよさそう。）

私も Tips 集をもっと増やせればいいなあと思っていました。確かに「黒地に白のときは…」というのは Tips 集に入れておくのがよさそうですね。
私が今までに思いついたことがあるのは、黒地に白文字 (EPS/PDF/JPG/PNG) の

<pre class="code" lang="tex">
\usepackage{color}
\pagecolor{black}
\color{white}
</pre>

と、単に文字をすべて白く（背景は透明）の (EPS/PDF/PNG)

<pre class="code" lang="tex">
\usepackage{color}
\color{white}
</pre>

くらいです。背景透明かつ白文字の PNG は意外に曲者で、今試したところ Windows 版の ImageMagick を通すスキームでは現状では不可能でした（gs を通す方は大丈夫。Mac 版では試したことがない）。Win の ImageMagick スキームで不可能なのは、初めに「透明」のはずの背景はビットマップ化と同時に「白背景」となり、最後の -transparent white で同化するからですね。

何を新機能に加えるべきか難しいですが、新機能でサポートすべき点と Tips で対処すべき点を列挙していく必要がありますね。

**Comment by doraTeX** [comment]
#11 へ統合につきクローズ。
