### ISSUE TITLE
フォント設定が元に戻る現象

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#90]
（#86 から分離）

[Mojaveでフォント設定が元に戻るという報告](https://github.com/doraTeX/TeX2img/issues/86#issuecomment-406273763)があり。
想像するに，これはフォント云々の問題ではなくて，単に「終了時の設定保存に失敗していて，2回前の終了時の状態が復元されている」のではなかろうか。
TeX2imgはアプリ終了時にGUIの状態を `~/Library/Preferences/com.loveinequality.TeX2img.plist` に保存している。何らかの理由でこれの書き出しに失敗しているのではなかろうか？
とはいっても手元で現象を再現できていないのでなんとも分からない。

**Comment by doraTeX** [comment]
とりあえず，ないよりはあった方がいいと思われます。

**Comment by Yasunari15** [comment]
いろいろ試してみた所，日本語の文字から始まるCompileを行うとBugが発生するのかもしれないと思えるようになりました。なぜHiragino Sansなのか気になりますね。

**Comment by Yasunari15** [comment]
Bugが起きてSF Pro Textに戻してからQuitすると設定は正常に保存されています。

![screen shot 2018-07-20 at 1 30 31](https://user-images.githubusercontent.com/38091102/42957464-bc4a0930-8bbd-11e8-8e9d-fe8e4308cb5e.png)

**Comment by doraTeX** [comment]
なるほど，すると設定保存の問題というよりは，使用途中で設定が変わってしまい，それが終了時に保存されてしまう，ということのようですね。フォント設定が途中で勝手に変わる現象が再現できず，原因の特定もできません。Mojaveのバグの可能性もそれなりに大きいです。

**Comment by Yasunari15** [comment]
> フォント設定が途中で勝手に変わる現象が再現できず，原因の特定もできません。Mojaveのバグの可能性もそれなりに大きいです。

そうでしたか。このままだと，気になってしまって普通に使うことが難しいので，Appleに適切な形でFeedbackするためにも，こちらで実行できる診断方法や実験があれば，教えて下さい。実際に，見て頂いた方が早いということでも構いません。

**Comment by doraTeX** [comment]
これはMojaveの実機でデバッガを走らせるしかありませんので，私がMojaveをインストールするまでどうしようもありません。

**Comment by doraTeX** [comment]
> 気になってしまって普通に使うことが難しい

ベータ版OSをインストールするということは，各種ソフトウェアが不具合をきたすことを覚悟せねばなりません。場合によってはまともに使えなくなることも多いですので，実用環境にベータ版OSをインストールすることは推奨されません。主に開発者が開発専用マシンで自分のアプリやOSの動作確認をするためにベータ版が公開されているわけですので……。

**Comment by Yasunari15** [comment]
> 実用環境にベータ版OSをインストールすることは推奨されません。

Dark ModeとDynamic Desktopをどうしても試してみたくなってInstallしてしまいました。

**Comment by doraTeX** [comment]
自分は過去の経験上，Appleの出すベータ版というものの完成度を全然信用していないのです……😅

**Comment by Yasunari15** [comment]
Dark Modeは慣れると魅力的でした。講師室にEl CapitanのMacが置いてあると伺いましたが，さすがにHigh Sierraにしても良いかと思っています。

**Comment by doraTeX** [comment]
> 講師室にEl CapitanのMacが置いてある

いえ、そんなものは当然存在しません。

**Comment by Yasunari15** [comment]
数学科のK先生の「新Versionを信頼しない」というPolicyによるものです。Updateをお勧めしています。ちなみに，我々をFollowingし始めた @softlondonというのはWindows君のようです。

**Comment by doraTeX** [comment]
「今問題なく動いている環境をむやみに変えない」というのは一つの見識ではあります。特に企業での使用においてはトラブル発生は致命的となりえるので、アップデートには慎重にならざるを得ません。
そんな中でも私は最新版原理主義なので、私の管理下にあるマシンはOSもアプリも常に最新版を保っています。
しかしそんな自分でも躊躇してしまうくらい、Appleのベータ版OSというのは恐ろしいものなのです……😨 まだ当面は実機にMojaveをインストールする予定はありません。

**Comment by Yasunari15** [comment]
「APFSにおけるPDF」のときと同じように，こちらのMacでDebugして原因だけでも，突き止めては頂けないでしょうか。Mojaveに原因があるとして，Appleが気付かないまま正式Releaseとなると，この奇妙な現象がTeX2imgの全Usersに響くことになる気がします。InstallされているXcodeのBetaではありますが。

**Comment by doraTeX** [comment]
それでしたら可能ではありますが、来週は自分が講習で多忙としているため、次に時間が取れるのは7/30（月）となります。

**Comment by Yasunari15** [comment]
7/30に伺えるどうかは分かりませんが，いずれNMFでお会いしましょう。Calendarを見たら，来週は自分も講習であることが分かりました😂
