### ISSUE TITLE
Mojave のダークモード対応

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#91]
(#88 からIssue立て直し）

Mojaveのダークモード対応のために考えるべきこと。

* [Supporting Dark Mode in Your Interface](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface) のガイドラインに沿って設計する。
* ウィンドウ配色を全体的に暗くする。
* 環境設定パネルの「詳細...」ボタンの見え方を確認する。
* シンタックスハイライトのデフォルトカラーをどうするか検討する。
  * ユーザがデフォルトカラーから明示的に変えていた場合はどうするか？
  * 使用途中にカラーモード切り替えをした場合はどう対応するか？

**Comment by Yasunari15** [comment]
> Golden Masterが出るくらいまでは仕事で使うMacにはベータ版新OSは入れないようにしております。

最終的にどうなるかは分かりませんが，今日のBetaではSan Franciscoがあらゆる所で太くなりました。

![screen shot 2018-07-20 at 0 01 58](https://user-images.githubusercontent.com/38091102/42950984-27088afc-8bb0-11e8-81eb-26945d18292a.png)

> Mojaveのリリースが迫ってくればTeXShopの側でも対策が打たれると思いますので，それに足並みをそろえた対応をしたいところです。

洒落た色分けになることを期待しています。Atomの色分けは個人的に気に入っているので，同じような感じになると良いと思います。Dark Mode対応に紛れて今までご報告させて頂いた，要望を開発者の皆さんに「Mailで」伝えておいて頂けると嬉しいです。
![screen shot 2018-07-20 at 0 06 35](https://user-images.githubusercontent.com/38091102/42951331-eca830d2-8bb0-11e8-83b8-6c216ce25a85.png)

**Comment by Yasunari15** [comment]
macOS Deployment Targetを10.14に設定してBuildしたら，自動でDark Modeになりました。Doesn't it look cool?

![screen shot 2018-07-24 at 1 53 30](https://user-images.githubusercontent.com/38091102/43091191-683b3d58-8ee4-11e8-8868-143e93d1ca92.png)

![screen shot 2018-07-24 at 1 41 53](https://user-images.githubusercontent.com/38091102/43090600-cc48bce6-8ee2-11e8-8fbe-f563193839e2.png)

最初にこのようなErrorが出てしまって困ったのですが，Yusuke Teradaは`Developer ID Application`と表示されYasunari Yoshidaは`Mac Developer`となっていますが，これは一体何ですか。

```
error: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "86GWZ48925" with a private key was found. (in target 'tex2img')
```

**Comment by doraTeX** [comment]
> macOS Deployment Targetを10.14に設定してBuild

そうすると10.13以下で起動できなくなります。

> これは一体何ですか。

「developer id gatekeeper」「mac developer vs developer id」などで検索してみてください。

**Comment by doraTeX** [comment]
> * シンタックスハイライトのデフォルトカラーをどうするか検討する。

次のように，配色をデフォルトに戻すボタンを2つ用意して対応する予定。ダークモードのデフォルト配色は TeXShop のダークモードテーマにあわせる。

<img width="498" alt="image" src="https://user-images.githubusercontent.com/6186180/50882705-03b63c00-1429-11e9-9d7f-3647a5ae40e5.png">

初回起動時は現在のモードに応じて適切な方のデフォルト配色を選ぶようにする。

> * ユーザがデフォルトカラーから明示的に変えていた場合はどうするか？
> * 使用途中にカラーモード切り替えをした場合はどう対応するか？

ユーザのカスタマイズ結果を尊重するため，アプリ側が勝手に配色を変更することはしないことにする。「初回起動時はライトモードだったが今回起動時はダークモードだから配色が見にくい」というようなケースについては，ユーザが自分で「ダークモードのデフォルトに戻す」ボタンを押して対応（または各自の好きなように配色変更）すればよい。

**Comment by doraTeX** [comment]
次のように，ライトモード・ダークモードそれぞれの色を指定するUIを設置し，ダークモード対応が完了しました。

![image](https://user-images.githubusercontent.com/6186180/94365637-78557080-010d-11eb-8d92-b522f6581a4b.png)
