### ISSUE TITLE
完了時の通知センターへの通知機能

### ISSUE THREAD

**Issue by doraTeX** [doraTeX/TeX2img#94]
次のような仕様で「完了時の通知センターへの通知機能」の設置を検討する。

* 環境設定パネルの「コンパイル後処理」のところに「通知」のチェックボックスを設置しておく。
* 通知メッセージの中身は各言語別の `Localizable.strings` に保持しておく。（成功時・失敗時のそれぞれのメッセージについて）
* 通知アイコンはTeX2imgのアプリアイコンとなる。
* 通知音は（うるさいと思う人が多いだろうから）なしとする。

**Comment by Yasunari15** [comment]
ご検討いただき，ありがとうございます。通知アイコンがTeX2imgになるのは確かに魅力的ですが，要望を出した私にとっては通知音とEmojiがあって，満足できるものです。

![screen shot 2018-08-05 at 16 24 56](https://user-images.githubusercontent.com/38091102/43683715-41041ab0-98cc-11e8-9bae-b42fefba62ce.png)

ただ，これを共通仕様として取り込んで頂くと「それを嫌って使わない人が出てくる」に繋がりかねません。もう少し考えさせて頂く材料として，メッセージにファイル名を`TeX2img.pdf`のように表示することは可能なのか，教えて頂けますでしょうか。

**Comment by Yasunari15** [comment]
良さそうですね。私はYasunariスクリプトをデフォルトに戻すことになりそうです。よろしくお願い致します。

**Comment by doraTeX** [comment]
1682c0a6ae78422bc985dc0edf953d1ec6a423a7 で次のような通知機能を実装してみました。

![image](https://user-images.githubusercontent.com/6186180/94012033-32359f80-fde3-11ea-8761-2c074c1b128f.png)
