### ISSUE TITLE
Command Completion's Marks

### ISSUE THREAD

**Issue by Yasunari** [doraTeX/TeX2img#95]
TeXShopと補完機能を共有できる機能は，最も気に入っているものの1つですが，以下が実装されていると，使い慣れている人にとっては，さらに便利かと思われます。

Function | Keyboard Shortcuts
---: | :---:
Next Mark | ⌃⌘F
Previous Mark | ⌃⌘G
Insert Mark | ⌘8

よろしくお願いいたします。

**Comment by doraTeX** [comment]
f6738acb92ab4e91f859296cc6f0c8456a6743b7  で TeXShop と同等の機能を導入完了。
