### ISSUE TITLE
オリジナルスクリプトが残すsynctex.gzファイル

### ISSUE THREAD

**Issue by Yasunari** [doraTeX/TeX2img#96]
かわいい通知を出すためにTeX2imgに登録している`Yasunari`スクリプトでは，ご存知の通り`ptex2pdf`を用いておりTeXShopでも登録しているため`-synctex=1`が渡っています。そのため`Auto Detect`させて`uplatex`を使った場合には残らない`synctex.gz`ファイルがソースと同一のディレクトリに残ってしまいます。`aux`ファイルなどは削除されているように，`synctex.gz`ファイルも削除する仕様にしていただけますでしょうか。

**Comment by Yasunari15** [comment]
> 補助ファイルの`basename.*` の形をしたファイルを全部補助ファイルと見なして一斉消去する，という手もあり得そうです。

意外にも同じディレクトリに，同名の画像を保存している例を見つけました。このような場合は少し困ってしまうかもしれません。

![screen shot 2018-09-20 at 1 09 15](https://user-images.githubusercontent.com/38091102/45766138-d2dfaa80-bc71-11e8-9e2c-565bb0e2cba0.png)

synctex.gzも含めて削除してくれるTeXShopの`Trash Aux Files`における仕様を，そのまま使えれば実装は楽だと思います。

**Comment by doraTeX** [comment]
いえ，そのようなケースにおいて他のファイルを巻き込むケースはありません。`補助ファイルのbasename.*` と書いたのは，TeX2img が作成する `temp37607-404B373D-14E1-435A-9F29-76538AD7F775.aux` のような名前のファイルのことです。

**Comment by doraTeX** [comment]
> いえ，そのようなケースにおいて他のファイルを巻き込むケースはありません。

「外部ファイル入力」かつ「入力ファイルと同じフォルダ上で作業」の場合は，巻き込みの危険が高いことに気づきました。やはり，ホワイトリスト方式で，消去すべき拡張子を個別に列挙する方が無難そうです。

> synctex.gzも含めて削除してくれるTeXShopのTrash Aux Filesにおける仕様を，そのまま使えれば実装は楽だと思います。

TeXShopの `Trash AUX Files` では，次の拡張子を一括削除しています。

* `aux` 
* `blg` 
* `brf` 
* `glo` 
* `idx` 
* `ilg` 
* `ind` 
* `loa` 
* `lof` 
* `log` 
* `lot` 
* `mtc` 
* `mlf` 
* `out` 
* `ttt` 
* `fff` 
* `ent` 
* `css` 
* `idv` 
* `wrm` 
* `4ct` 
* `4tc` 
* `lg` 
* `xref` 
* `bcf` 
* `gtex` 
* `gaux` 
* `glog` 
* `pdfsync` 
* `synctex` 
* `synctex(busy)` 
* `fdb_latexmk` 
* `fls` 
* `toc` 

ただ，よく分からない拡張子も多いし，`css` とかは無関係なファイルの巻き込みの危険性が高そうなので，この仕様に沿うのは気が乗りません。もっと安全側に倒した設計にした方がよさそうです。

**Comment by doraTeX** [comment]
自分が去年書いていたことの意味がわからなくなりました……😓

> 「外部ファイル入力」かつ「入力ファイルと同じフォルダ上で作業」の場合は，巻き込みの危険が高いことに気づきました。

「外部ファイル入力」かつ「入力ファイルと同じフォルダ上で作業」の場合であっても，入力ファイルをいったん `temp37607-404B373D-14E1-435A-9F29-76538AD7F775.aux` のような長いテンポラリな名前でそのフォルダ内にコピーしてから作業を始めるのだから，作業後に `補助ファイルのbasename.*` を一括削除する分には「巻き込み」の危険性はなさそうに思います。

**Comment by doraTeX** [comment]
が，とりあえず，安全側に倒して，[有名どころの拡張子を列挙](https://github.com/doraTeX/TeX2img/commit/ecd72b6892398694cfff7edaf73d97e23c13321f#diff-4a638eb2751e2d5a61f8108855ef4caeR2204-R2219)して削除対象に加えておきました。
