### ISSUE TITLE
gs9.25 での PDF-1.7 デフォルト化の影響はあるか？

### ISSUE THREAD

**Issue by aminophen** [doraTeX/TeX2img#97]
gs が出力する PDF のバージョンが，gs9.25 から（もしかするとバグだらけだった gs9.24 から？）PDF-1.7 に上がりました。従って，

````
gs -sDEVICE=pdfwrite -dBATCH -dNOPAUSE -dNoOutputFonts -sOutputFile=out.pdf in.pdf
````

などあらゆる使い方で PDF-1.7 が出力されるようになりました。

なお，macOS 版は epstopdf も内蔵していますが，TeX Live に収録されている最新版ではこの変更へ対処されているため，PDF-1.5 で出力するようになっています。

変換経路を見る限り，PDF を Ghostscript 経由で出す時は最後に Quartz API を通っているように見えますが（El Capitan 10.11.6 では 1.3 になるらしい），念のため影響ないか確認した方が良いかもしれません。

**Comment by doraTeX** [comment]
内蔵の epstopdf を TeX Live の最新版に更新するとともに，そのデフォルト挙動にあわせて，TeX2img から `gs -sDEVICE=pdfwrite` を呼ぶときには `-dCompatibilityLevel=1.5` を付けるようにしてみました。
